from ._vulkan_enum import (
    StdVideoAV1ChromaSamplePosition,
    StdVideoAV1ColorPrimaries,
    StdVideoAV1FrameRestorationType,
    StdVideoAV1FrameType,
    StdVideoAV1InterpolationFilter,
    StdVideoAV1Level,
    StdVideoAV1MatrixCoefficients,
    StdVideoAV1Profile,
    StdVideoAV1ReferenceName,
    StdVideoAV1TransferCharacteristics,
    StdVideoAV1TxMode,
    StdVideoDecodeH264FieldOrderCount,
    StdVideoH264AspectRatioIdc,
    StdVideoH264CabacInitIdc,
    StdVideoH264ChromaFormatIdc,
    StdVideoH264DisableDeblockingFilterIdc,
    StdVideoH264LevelIdc,
    StdVideoH264MemMgmtControlOp,
    StdVideoH264ModificationOfPicNumsIdc,
    StdVideoH264NonVclNaluType,
    StdVideoH264PictureType,
    StdVideoH264PocType,
    StdVideoH264ProfileIdc,
    StdVideoH264SliceType,
    StdVideoH264WeightedBipredIdc,
    StdVideoH265AspectRatioIdc,
    StdVideoH265ChromaFormatIdc,
    StdVideoH265LevelIdc,
    StdVideoH265PictureType,
    StdVideoH265ProfileIdc,
    StdVideoH265SliceType,
    VkAccelerationStructureBuildTypeKHR,
    VkAccelerationStructureCompatibilityKHR,
    VkAccelerationStructureCreateFlagsKHR,
    VkAccelerationStructureMemoryRequirementsTypeNV,
    VkAccelerationStructureMotionInfoFlagsNV,
    VkAccelerationStructureMotionInstanceFlagsNV,
    VkAccelerationStructureMotionInstanceTypeNV,
    VkAccelerationStructureTypeKHR,
    VkAccessFlags,
    VkAccessFlags2,
    VkAcquireProfilingLockFlagsKHR,
    VkAndroidSurfaceCreateFlagsKHR,
    VkAttachmentDescriptionFlags,
    VkAttachmentLoadOp,
    VkAttachmentStoreOp,
    VkBlendFactor,
    VkBlendOp,
    VkBlendOverlapEXT,
    VkBlockMatchWindowCompareModeQCOM,
    VkBorderColor,
    VkBufferCreateFlags,
    VkBufferUsageFlags,
    VkBufferUsageFlags2KHR,
    VkBufferViewCreateFlags,
    VkBuildAccelerationStructureFlagsKHR,
    VkBuildAccelerationStructureModeKHR,
    VkBuildMicromapFlagsEXT,
    VkBuildMicromapModeEXT,
    VkChromaLocation,
    VkCoarseSampleOrderTypeNV,
    VkColorComponentFlags,
    VkColorSpaceKHR,
    VkCommandBufferLevel,
    VkCommandBufferResetFlags,
    VkCommandBufferUsageFlags,
    VkCommandPoolCreateFlags,
    VkCommandPoolResetFlags,
    VkCommandPoolTrimFlags,
    VkCompareOp,
    VkComponentSwizzle,
    VkComponentTypeKHR,
    VkCompositeAlphaFlagsKHR,
    VkConditionalRenderingFlagsEXT,
    VkConservativeRasterizationModeEXT,
    VkCopyAccelerationStructureModeKHR,
    VkCopyMicromapModeEXT,
    VkCoverageModulationModeNV,
    VkCoverageReductionModeNV,
    VkCubicFilterWeightsQCOM,
    VkCullModeFlags,
    VkDebugReportFlagsEXT,
    VkDebugReportObjectTypeEXT,
    VkDebugUtilsMessageSeverityFlagsEXT,
    VkDebugUtilsMessageTypeFlagsEXT,
    VkDebugUtilsMessengerCallbackDataFlagsEXT,
    VkDebugUtilsMessengerCreateFlagsEXT,
    VkDependencyFlags,
    VkDepthBiasRepresentationEXT,
    VkDescriptorBindingFlags,
    VkDescriptorPoolCreateFlags,
    VkDescriptorPoolResetFlags,
    VkDescriptorSetLayoutCreateFlags,
    VkDescriptorType,
    VkDescriptorUpdateTemplateCreateFlags,
    VkDescriptorUpdateTemplateType,
    VkDeviceAddressBindingFlagsEXT,
    VkDeviceAddressBindingTypeEXT,
    VkDeviceCreateFlags,
    VkDeviceDiagnosticsConfigFlagsNV,
    VkDeviceEventTypeEXT,
    VkDeviceFaultAddressTypeEXT,
    VkDeviceFaultVendorBinaryHeaderVersionEXT,
    VkDeviceGroupPresentModeFlagsKHR,
    VkDeviceMemoryReportEventTypeEXT,
    VkDeviceMemoryReportFlagsEXT,
    VkDeviceQueueCreateFlags,
    VkDirectDriverLoadingFlagsLUNARG,
    VkDirectDriverLoadingModeLUNARG,
    VkDirectFBSurfaceCreateFlagsEXT,
    VkDiscardRectangleModeEXT,
    VkDisplacementMicromapFormatNV,
    VkDisplayEventTypeEXT,
    VkDisplayModeCreateFlagsKHR,
    VkDisplayPlaneAlphaFlagsKHR,
    VkDisplayPowerStateEXT,
    VkDisplaySurfaceCreateFlagsKHR,
    VkDriverId,
    VkDynamicState,
    VkEventCreateFlags,
    VkExportMetalObjectTypeFlagsEXT,
    VkExternalFenceFeatureFlags,
    VkExternalFenceHandleTypeFlags,
    VkExternalMemoryFeatureFlags,
    VkExternalMemoryFeatureFlagsNV,
    VkExternalMemoryHandleTypeFlags,
    VkExternalMemoryHandleTypeFlagsNV,
    VkExternalSemaphoreFeatureFlags,
    VkExternalSemaphoreHandleTypeFlags,
    VkFaultLevel,
    VkFaultQueryBehavior,
    VkFaultType,
    VkFenceCreateFlags,
    VkFenceImportFlags,
    VkFilter,
    VkFormat,
    VkFormatFeatureFlags,
    VkFormatFeatureFlags2,
    VkFragmentShadingRateCombinerOpKHR,
    VkFragmentShadingRateNV,
    VkFragmentShadingRateTypeNV,
    VkFrameBoundaryFlagsEXT,
    VkFramebufferCreateFlags,
    VkFrontFace,
    VkFullScreenExclusiveEXT,
    VkGeometryFlagsKHR,
    VkGeometryInstanceFlagsKHR,
    VkGeometryTypeKHR,
    VkGraphicsPipelineLibraryFlagsEXT,
    VkHeadlessSurfaceCreateFlagsEXT,
    VkHostImageCopyFlagsEXT,
    VkIOSSurfaceCreateFlagsMVK,
    VkImageAspectFlags,
    VkImageCompressionFixedRateFlagsEXT,
    VkImageCompressionFlagsEXT,
    VkImageConstraintsInfoFlagsFUCHSIA,
    VkImageCreateFlags,
    VkImageFormatConstraintsFlagBitsFUCHSIA,
    VkImageFormatConstraintsFlagsFUCHSIA,
    VkImageLayout,
    VkImagePipeSurfaceCreateFlagsFUCHSIA,
    VkImageTiling,
    VkImageType,
    VkImageUsageFlags,
    VkImageViewCreateFlags,
    VkImageViewType,
    VkIndexType,
    VkIndirectCommandsLayoutUsageFlagsNV,
    VkIndirectCommandsTokenTypeNV,
    VkIndirectStateFlagsNV,
    VkInstanceCreateFlags,
    VkInternalAllocationType,
    VkLatencyMarkerNV,
    VkLayerSettingTypeEXT,
    VkLayeredDriverUnderlyingApiMSFT,
    VkLineRasterizationModeKHR,
    VkLogicOp,
    VkMacOSSurfaceCreateFlagsMVK,
    VkMemoryAllocateFlags,
    VkMemoryDecompressionMethodFlagsNV,
    VkMemoryHeapFlags,
    VkMemoryMapFlags,
    VkMemoryOverallocationBehaviorAMD,
    VkMemoryPropertyFlags,
    VkMemoryUnmapFlagsKHR,
    VkMetalSurfaceCreateFlagsEXT,
    VkMicromapCreateFlagsEXT,
    VkMicromapTypeEXT,
    VkObjectType,
    VkOpacityMicromapFormatEXT,
    VkOpacityMicromapSpecialIndexEXT,
    VkOpticalFlowExecuteFlagsNV,
    VkOpticalFlowGridSizeFlagsNV,
    VkOpticalFlowPerformanceLevelNV,
    VkOpticalFlowSessionBindingPointNV,
    VkOpticalFlowSessionCreateFlagsNV,
    VkOpticalFlowUsageFlagsNV,
    VkOutOfBandQueueTypeNV,
    VkPeerMemoryFeatureFlags,
    VkPerformanceConfigurationTypeINTEL,
    VkPerformanceCounterDescriptionFlagsKHR,
    VkPerformanceCounterScopeKHR,
    VkPerformanceCounterStorageKHR,
    VkPerformanceCounterUnitKHR,
    VkPerformanceOverrideTypeINTEL,
    VkPerformanceParameterTypeINTEL,
    VkPerformanceValueTypeINTEL,
    VkPhysicalDeviceSchedulingControlsFlagsARM,
    VkPhysicalDeviceType,
    VkPipelineBindPoint,
    VkPipelineCacheCreateFlags,
    VkPipelineCacheHeaderVersion,
    VkPipelineCacheValidationVersion,
    VkPipelineColorBlendStateCreateFlags,
    VkPipelineCompilerControlFlagsAMD,
    VkPipelineCoverageModulationStateCreateFlagsNV,
    VkPipelineCoverageReductionStateCreateFlagsNV,
    VkPipelineCoverageToColorStateCreateFlagsNV,
    VkPipelineCreateFlags,
    VkPipelineCreateFlags2KHR,
    VkPipelineCreationFeedbackFlags,
    VkPipelineDepthStencilStateCreateFlags,
    VkPipelineDiscardRectangleStateCreateFlagsEXT,
    VkPipelineDynamicStateCreateFlags,
    VkPipelineExecutableStatisticFormatKHR,
    VkPipelineInputAssemblyStateCreateFlags,
    VkPipelineLayoutCreateFlags,
    VkPipelineMatchControl,
    VkPipelineMultisampleStateCreateFlags,
    VkPipelineRasterizationConservativeStateCreateFlagsEXT,
    VkPipelineRasterizationDepthClipStateCreateFlagsEXT,
    VkPipelineRasterizationStateCreateFlags,
    VkPipelineRasterizationStateStreamCreateFlagsEXT,
    VkPipelineRobustnessBufferBehaviorEXT,
    VkPipelineRobustnessImageBehaviorEXT,
    VkPipelineShaderStageCreateFlags,
    VkPipelineStageFlags,
    VkPipelineStageFlags2,
    VkPipelineTessellationStateCreateFlags,
    VkPipelineVertexInputStateCreateFlags,
    VkPipelineViewportStateCreateFlags,
    VkPipelineViewportSwizzleStateCreateFlagsNV,
    VkPointClippingBehavior,
    VkPolygonMode,
    VkPresentGravityFlagsEXT,
    VkPresentModeKHR,
    VkPresentScalingFlagsEXT,
    VkPrimitiveTopology,
    VkPrivateDataSlotCreateFlagBits,
    VkPrivateDataSlotCreateFlags,
    VkProvokingVertexModeEXT,
    VkQueryControlFlags,
    VkQueryPipelineStatisticFlags,
    VkQueryPoolCreateFlags,
    VkQueryPoolSamplingModeINTEL,
    VkQueryResultFlags,
    VkQueryResultStatusKHR,
    VkQueryType,
    VkQueueFlags,
    VkQueueGlobalPriorityKHR,
    VkRasterizationOrderAMD,
    VkRayTracingInvocationReorderModeNV,
    VkRayTracingShaderGroupTypeKHR,
    VkRefreshObjectFlagsKHR,
    VkRenderPassCreateFlags,
    VkRenderingFlags,
    VkResolveModeFlags,
    VkResult,
    VkSampleCountFlags,
    VkSamplerAddressMode,
    VkSamplerCreateFlags,
    VkSamplerMipmapMode,
    VkSamplerReductionMode,
    VkSamplerYcbcrModelConversion,
    VkSamplerYcbcrRange,
    VkSciSyncClientTypeNV,
    VkSciSyncPrimitiveTypeNV,
    VkScopeKHR,
    VkScreenSurfaceCreateFlagsQNX,
    VkSemaphoreCreateFlagBits,
    VkSemaphoreCreateFlags,
    VkSemaphoreImportFlags,
    VkSemaphoreType,
    VkSemaphoreWaitFlags,
    VkShaderCodeTypeEXT,
    VkShaderCorePropertiesFlagsAMD,
    VkShaderCreateFlagsEXT,
    VkShaderFloatControlsIndependence,
    VkShaderGroupShaderKHR,
    VkShaderInfoTypeAMD,
    VkShaderModuleCreateFlagBits,
    VkShaderModuleCreateFlags,
    VkShaderStageFlags,
    VkShadingRatePaletteEntryNV,
    VkSharingMode,
    VkSparseImageFormatFlags,
    VkSparseMemoryBindFlags,
    VkStencilFaceFlags,
    VkStencilOp,
    VkStreamDescriptorSurfaceCreateFlagsGGP,
    VkStructureType,
    VkSubgroupFeatureFlags,
    VkSubmitFlags,
    VkSubpassContents,
    VkSubpassDescriptionFlags,
    VkSubpassMergeStatusEXT,
    VkSurfaceCounterFlagsEXT,
    VkSurfaceTransformFlagsKHR,
    VkSwapchainCreateFlagsKHR,
    VkSwapchainImageUsageFlagsANDROID,
    VkSystemAllocationScope,
    VkTessellationDomainOrigin,
    VkTimeDomainKHR,
    VkToolPurposeFlags,
    VkValidationCacheCreateFlagsEXT,
    VkValidationCacheHeaderVersionEXT,
    VkValidationCheckEXT,
    VkValidationFeatureDisableEXT,
    VkValidationFeatureEnableEXT,
    VkVendorId,
    VkVertexInputRate,
    VkViSurfaceCreateFlagsNN,
    VkVideoBeginCodingFlagsKHR,
    VkVideoCapabilityFlagsKHR,
    VkVideoChromaSubsamplingFlagsKHR,
    VkVideoCodecOperationFlagsKHR,
    VkVideoCodingControlFlagsKHR,
    VkVideoComponentBitDepthFlagsKHR,
    VkVideoDecodeCapabilityFlagsKHR,
    VkVideoDecodeFlagsKHR,
    VkVideoDecodeH264PictureLayoutFlagsKHR,
    VkVideoDecodeUsageFlagsKHR,
    VkVideoEncodeCapabilityFlagsKHR,
    VkVideoEncodeContentFlagsKHR,
    VkVideoEncodeFeedbackFlagsKHR,
    VkVideoEncodeFlagsKHR,
    VkVideoEncodeH264CapabilityFlagsKHR,
    VkVideoEncodeH264RateControlFlagsKHR,
    VkVideoEncodeH264StdFlagsKHR,
    VkVideoEncodeH265CapabilityFlagsKHR,
    VkVideoEncodeH265CtbSizeFlagsKHR,
    VkVideoEncodeH265RateControlFlagsKHR,
    VkVideoEncodeH265StdFlagsKHR,
    VkVideoEncodeH265TransformBlockSizeFlagsKHR,
    VkVideoEncodeRateControlFlagsKHR,
    VkVideoEncodeRateControlModeFlagsKHR,
    VkVideoEncodeTuningModeKHR,
    VkVideoEncodeUsageFlagsKHR,
    VkVideoEndCodingFlagsKHR,
    VkVideoSessionCreateFlagsKHR,
    VkVideoSessionParametersCreateFlagsKHR,
    VkViewportCoordinateSwizzleNV,
    VkWaylandSurfaceCreateFlagsKHR,
    VkWin32SurfaceCreateFlagsKHR,
    VkXcbSurfaceCreateFlagsKHR,
    VkXlibSurfaceCreateFlagsKHR,
)

VkAccelerationStructureTypeNV = VkAccelerationStructureTypeKHR
VkAccessFlags2KHR = VkAccessFlags2
VkBuildAccelerationStructureFlagsNV = VkBuildAccelerationStructureFlagsKHR
VkChromaLocationKHR = VkChromaLocation
VkCommandPoolTrimFlagsKHR = VkCommandPoolTrimFlags
VkComponentTypeNV = VkComponentTypeKHR
VkCopyAccelerationStructureModeNV = VkCopyAccelerationStructureModeKHR
VkDescriptorBindingFlagsEXT = VkDescriptorBindingFlags
VkDescriptorUpdateTemplateCreateFlagsKHR = VkDescriptorUpdateTemplateCreateFlags
VkDescriptorUpdateTemplateTypeKHR = VkDescriptorUpdateTemplateType
VkDriverIdKHR = VkDriverId
VkExternalFenceFeatureFlagsKHR = VkExternalFenceFeatureFlags
VkExternalFenceHandleTypeFlagsKHR = VkExternalFenceHandleTypeFlags
VkExternalMemoryFeatureFlagsKHR = VkExternalMemoryFeatureFlags
VkExternalMemoryHandleTypeFlagsKHR = VkExternalMemoryHandleTypeFlags
VkExternalSemaphoreFeatureFlagsKHR = VkExternalSemaphoreFeatureFlags
VkExternalSemaphoreHandleTypeFlagsKHR = VkExternalSemaphoreHandleTypeFlags
VkFenceImportFlagsKHR = VkFenceImportFlags
VkFormatFeatureFlags2KHR = VkFormatFeatureFlags2
VkGeometryFlagsNV = VkGeometryFlagsKHR
VkGeometryInstanceFlagsNV = VkGeometryInstanceFlagsKHR
VkGeometryTypeNV = VkGeometryTypeKHR
VkLineRasterizationModeEXT = VkLineRasterizationModeKHR
VkMemoryAllocateFlagsKHR = VkMemoryAllocateFlags
VkPeerMemoryFeatureFlagsKHR = VkPeerMemoryFeatureFlags
VkPipelineCreationFeedbackFlagsEXT = VkPipelineCreationFeedbackFlags
VkPipelineStageFlags2KHR = VkPipelineStageFlags2
VkPointClippingBehaviorKHR = VkPointClippingBehavior
VkPrivateDataSlotCreateFlagBitsEXT = VkPrivateDataSlotCreateFlagBits
VkPrivateDataSlotCreateFlagsEXT = VkPrivateDataSlotCreateFlags
VkQueueGlobalPriorityEXT = VkQueueGlobalPriorityKHR
VkRayTracingShaderGroupTypeNV = VkRayTracingShaderGroupTypeKHR
VkRenderingFlagsKHR = VkRenderingFlags
VkResolveModeFlagsKHR = VkResolveModeFlags
VkSamplerReductionModeEXT = VkSamplerReductionMode
VkSamplerYcbcrModelConversionKHR = VkSamplerYcbcrModelConversion
VkSamplerYcbcrRangeKHR = VkSamplerYcbcrRange
VkScopeNV = VkScopeKHR
VkSemaphoreImportFlagsKHR = VkSemaphoreImportFlags
VkSemaphoreTypeKHR = VkSemaphoreType
VkSemaphoreWaitFlagsKHR = VkSemaphoreWaitFlags
VkShaderFloatControlsIndependenceKHR = VkShaderFloatControlsIndependence
VkSubmitFlagsKHR = VkSubmitFlags
VkTessellationDomainOriginKHR = VkTessellationDomainOrigin
VkTimeDomainEXT = VkTimeDomainKHR
VkToolPurposeFlagsEXT = VkToolPurposeFlags
