from ._vulkan_procedure.vkAcquireDrmDisplayEXT import vkAcquireDrmDisplayEXT
from ._vulkan_procedure.vkAcquireFullScreenExclusiveModeEXT import vkAcquireFullScreenExclusiveModeEXT
from ._vulkan_procedure.vkAcquireImageANDROID import vkAcquireImageANDROID
from ._vulkan_procedure.vkAcquireNextImage2KHR import vkAcquireNextImage2KHR
from ._vulkan_procedure.vkAcquireNextImageKHR import vkAcquireNextImageKHR
from ._vulkan_procedure.vkAcquirePerformanceConfigurationINTEL import vkAcquirePerformanceConfigurationINTEL
from ._vulkan_procedure.vkAcquireProfilingLockKHR import vkAcquireProfilingLockKHR
from ._vulkan_procedure.vkAcquireWinrtDisplayNV import vkAcquireWinrtDisplayNV
from ._vulkan_procedure.vkAcquireXlibDisplayEXT import vkAcquireXlibDisplayEXT
from ._vulkan_procedure.vkAllocateCommandBuffers import vkAllocateCommandBuffers
from ._vulkan_procedure.vkAllocateDescriptorSets import vkAllocateDescriptorSets
from ._vulkan_procedure.vkAllocateMemory import vkAllocateMemory
from ._vulkan_procedure.vkBeginCommandBuffer import vkBeginCommandBuffer
from ._vulkan_procedure.vkBindAccelerationStructureMemoryNV import vkBindAccelerationStructureMemoryNV
from ._vulkan_procedure.vkBindBufferMemory import vkBindBufferMemory
from ._vulkan_procedure.vkBindBufferMemory2 import vkBindBufferMemory2
from ._vulkan_procedure.vkBindImageMemory import vkBindImageMemory
from ._vulkan_procedure.vkBindImageMemory2 import vkBindImageMemory2
from ._vulkan_procedure.vkBindOpticalFlowSessionImageNV import vkBindOpticalFlowSessionImageNV
from ._vulkan_procedure.vkBindVideoSessionMemoryKHR import vkBindVideoSessionMemoryKHR
from ._vulkan_procedure.vkBuildAccelerationStructuresKHR import vkBuildAccelerationStructuresKHR
from ._vulkan_procedure.vkBuildMicromapsEXT import vkBuildMicromapsEXT
from ._vulkan_procedure.vkCmdBeginConditionalRenderingEXT import vkCmdBeginConditionalRenderingEXT
from ._vulkan_procedure.vkCmdBeginDebugUtilsLabelEXT import vkCmdBeginDebugUtilsLabelEXT
from ._vulkan_procedure.vkCmdBeginQuery import vkCmdBeginQuery
from ._vulkan_procedure.vkCmdBeginQueryIndexedEXT import vkCmdBeginQueryIndexedEXT
from ._vulkan_procedure.vkCmdBeginRenderPass import vkCmdBeginRenderPass
from ._vulkan_procedure.vkCmdBeginRenderPass2 import vkCmdBeginRenderPass2
from ._vulkan_procedure.vkCmdBeginRendering import vkCmdBeginRendering
from ._vulkan_procedure.vkCmdBeginTransformFeedbackEXT import vkCmdBeginTransformFeedbackEXT
from ._vulkan_procedure.vkCmdBeginVideoCodingKHR import vkCmdBeginVideoCodingKHR
from ._vulkan_procedure.vkCmdBindDescriptorBufferEmbeddedSamplers2EXT import vkCmdBindDescriptorBufferEmbeddedSamplers2EXT
from ._vulkan_procedure.vkCmdBindDescriptorBufferEmbeddedSamplersEXT import vkCmdBindDescriptorBufferEmbeddedSamplersEXT
from ._vulkan_procedure.vkCmdBindDescriptorBuffersEXT import vkCmdBindDescriptorBuffersEXT
from ._vulkan_procedure.vkCmdBindDescriptorSets import vkCmdBindDescriptorSets
from ._vulkan_procedure.vkCmdBindDescriptorSets2KHR import vkCmdBindDescriptorSets2KHR
from ._vulkan_procedure.vkCmdBindIndexBuffer import vkCmdBindIndexBuffer
from ._vulkan_procedure.vkCmdBindIndexBuffer2KHR import vkCmdBindIndexBuffer2KHR
from ._vulkan_procedure.vkCmdBindInvocationMaskHUAWEI import vkCmdBindInvocationMaskHUAWEI
from ._vulkan_procedure.vkCmdBindPipeline import vkCmdBindPipeline
from ._vulkan_procedure.vkCmdBindPipelineShaderGroupNV import vkCmdBindPipelineShaderGroupNV
from ._vulkan_procedure.vkCmdBindShadersEXT import vkCmdBindShadersEXT
from ._vulkan_procedure.vkCmdBindShadingRateImageNV import vkCmdBindShadingRateImageNV
from ._vulkan_procedure.vkCmdBindTransformFeedbackBuffersEXT import vkCmdBindTransformFeedbackBuffersEXT
from ._vulkan_procedure.vkCmdBindVertexBuffers import vkCmdBindVertexBuffers
from ._vulkan_procedure.vkCmdBindVertexBuffers2 import vkCmdBindVertexBuffers2
from ._vulkan_procedure.vkCmdBlitImage import vkCmdBlitImage
from ._vulkan_procedure.vkCmdBlitImage2 import vkCmdBlitImage2
from ._vulkan_procedure.vkCmdBuildAccelerationStructureNV import vkCmdBuildAccelerationStructureNV
from ._vulkan_procedure.vkCmdBuildAccelerationStructuresIndirectKHR import vkCmdBuildAccelerationStructuresIndirectKHR
from ._vulkan_procedure.vkCmdBuildAccelerationStructuresKHR import vkCmdBuildAccelerationStructuresKHR
from ._vulkan_procedure.vkCmdBuildMicromapsEXT import vkCmdBuildMicromapsEXT
from ._vulkan_procedure.vkCmdClearAttachments import vkCmdClearAttachments
from ._vulkan_procedure.vkCmdClearColorImage import vkCmdClearColorImage
from ._vulkan_procedure.vkCmdClearDepthStencilImage import vkCmdClearDepthStencilImage
from ._vulkan_procedure.vkCmdControlVideoCodingKHR import vkCmdControlVideoCodingKHR
from ._vulkan_procedure.vkCmdCopyAccelerationStructureKHR import vkCmdCopyAccelerationStructureKHR
from ._vulkan_procedure.vkCmdCopyAccelerationStructureNV import vkCmdCopyAccelerationStructureNV
from ._vulkan_procedure.vkCmdCopyAccelerationStructureToMemoryKHR import vkCmdCopyAccelerationStructureToMemoryKHR
from ._vulkan_procedure.vkCmdCopyBuffer import vkCmdCopyBuffer
from ._vulkan_procedure.vkCmdCopyBuffer2 import vkCmdCopyBuffer2
from ._vulkan_procedure.vkCmdCopyBufferToImage import vkCmdCopyBufferToImage
from ._vulkan_procedure.vkCmdCopyBufferToImage2 import vkCmdCopyBufferToImage2
from ._vulkan_procedure.vkCmdCopyImage import vkCmdCopyImage
from ._vulkan_procedure.vkCmdCopyImage2 import vkCmdCopyImage2
from ._vulkan_procedure.vkCmdCopyImageToBuffer import vkCmdCopyImageToBuffer
from ._vulkan_procedure.vkCmdCopyImageToBuffer2 import vkCmdCopyImageToBuffer2
from ._vulkan_procedure.vkCmdCopyMemoryIndirectNV import vkCmdCopyMemoryIndirectNV
from ._vulkan_procedure.vkCmdCopyMemoryToAccelerationStructureKHR import vkCmdCopyMemoryToAccelerationStructureKHR
from ._vulkan_procedure.vkCmdCopyMemoryToImageIndirectNV import vkCmdCopyMemoryToImageIndirectNV
from ._vulkan_procedure.vkCmdCopyMemoryToMicromapEXT import vkCmdCopyMemoryToMicromapEXT
from ._vulkan_procedure.vkCmdCopyMicromapEXT import vkCmdCopyMicromapEXT
from ._vulkan_procedure.vkCmdCopyMicromapToMemoryEXT import vkCmdCopyMicromapToMemoryEXT
from ._vulkan_procedure.vkCmdCopyQueryPoolResults import vkCmdCopyQueryPoolResults
from ._vulkan_procedure.vkCmdCuLaunchKernelNVX import vkCmdCuLaunchKernelNVX
from ._vulkan_procedure.vkCmdCudaLaunchKernelNV import vkCmdCudaLaunchKernelNV
from ._vulkan_procedure.vkCmdDebugMarkerBeginEXT import vkCmdDebugMarkerBeginEXT
from ._vulkan_procedure.vkCmdDebugMarkerEndEXT import vkCmdDebugMarkerEndEXT
from ._vulkan_procedure.vkCmdDebugMarkerInsertEXT import vkCmdDebugMarkerInsertEXT
from ._vulkan_procedure.vkCmdDecodeVideoKHR import vkCmdDecodeVideoKHR
from ._vulkan_procedure.vkCmdDecompressMemoryIndirectCountNV import vkCmdDecompressMemoryIndirectCountNV
from ._vulkan_procedure.vkCmdDecompressMemoryNV import vkCmdDecompressMemoryNV
from ._vulkan_procedure.vkCmdDispatch import vkCmdDispatch
from ._vulkan_procedure.vkCmdDispatchBase import vkCmdDispatchBase
from ._vulkan_procedure.vkCmdDispatchGraphAMDX import vkCmdDispatchGraphAMDX
from ._vulkan_procedure.vkCmdDispatchGraphIndirectAMDX import vkCmdDispatchGraphIndirectAMDX
from ._vulkan_procedure.vkCmdDispatchGraphIndirectCountAMDX import vkCmdDispatchGraphIndirectCountAMDX
from ._vulkan_procedure.vkCmdDispatchIndirect import vkCmdDispatchIndirect
from ._vulkan_procedure.vkCmdDraw import vkCmdDraw
from ._vulkan_procedure.vkCmdDrawClusterHUAWEI import vkCmdDrawClusterHUAWEI
from ._vulkan_procedure.vkCmdDrawClusterIndirectHUAWEI import vkCmdDrawClusterIndirectHUAWEI
from ._vulkan_procedure.vkCmdDrawIndexed import vkCmdDrawIndexed
from ._vulkan_procedure.vkCmdDrawIndexedIndirect import vkCmdDrawIndexedIndirect
from ._vulkan_procedure.vkCmdDrawIndexedIndirectCount import vkCmdDrawIndexedIndirectCount
from ._vulkan_procedure.vkCmdDrawIndirect import vkCmdDrawIndirect
from ._vulkan_procedure.vkCmdDrawIndirectByteCountEXT import vkCmdDrawIndirectByteCountEXT
from ._vulkan_procedure.vkCmdDrawIndirectCount import vkCmdDrawIndirectCount
from ._vulkan_procedure.vkCmdDrawMeshTasksEXT import vkCmdDrawMeshTasksEXT
from ._vulkan_procedure.vkCmdDrawMeshTasksIndirectCountEXT import vkCmdDrawMeshTasksIndirectCountEXT
from ._vulkan_procedure.vkCmdDrawMeshTasksIndirectCountNV import vkCmdDrawMeshTasksIndirectCountNV
from ._vulkan_procedure.vkCmdDrawMeshTasksIndirectEXT import vkCmdDrawMeshTasksIndirectEXT
from ._vulkan_procedure.vkCmdDrawMeshTasksIndirectNV import vkCmdDrawMeshTasksIndirectNV
from ._vulkan_procedure.vkCmdDrawMeshTasksNV import vkCmdDrawMeshTasksNV
from ._vulkan_procedure.vkCmdDrawMultiEXT import vkCmdDrawMultiEXT
from ._vulkan_procedure.vkCmdDrawMultiIndexedEXT import vkCmdDrawMultiIndexedEXT
from ._vulkan_procedure.vkCmdEncodeVideoKHR import vkCmdEncodeVideoKHR
from ._vulkan_procedure.vkCmdEndConditionalRenderingEXT import vkCmdEndConditionalRenderingEXT
from ._vulkan_procedure.vkCmdEndDebugUtilsLabelEXT import vkCmdEndDebugUtilsLabelEXT
from ._vulkan_procedure.vkCmdEndQuery import vkCmdEndQuery
from ._vulkan_procedure.vkCmdEndQueryIndexedEXT import vkCmdEndQueryIndexedEXT
from ._vulkan_procedure.vkCmdEndRenderPass import vkCmdEndRenderPass
from ._vulkan_procedure.vkCmdEndRenderPass2 import vkCmdEndRenderPass2
from ._vulkan_procedure.vkCmdEndRendering import vkCmdEndRendering
from ._vulkan_procedure.vkCmdEndTransformFeedbackEXT import vkCmdEndTransformFeedbackEXT
from ._vulkan_procedure.vkCmdEndVideoCodingKHR import vkCmdEndVideoCodingKHR
from ._vulkan_procedure.vkCmdExecuteCommands import vkCmdExecuteCommands
from ._vulkan_procedure.vkCmdExecuteGeneratedCommandsNV import vkCmdExecuteGeneratedCommandsNV
from ._vulkan_procedure.vkCmdFillBuffer import vkCmdFillBuffer
from ._vulkan_procedure.vkCmdInitializeGraphScratchMemoryAMDX import vkCmdInitializeGraphScratchMemoryAMDX
from ._vulkan_procedure.vkCmdInsertDebugUtilsLabelEXT import vkCmdInsertDebugUtilsLabelEXT
from ._vulkan_procedure.vkCmdNextSubpass import vkCmdNextSubpass
from ._vulkan_procedure.vkCmdNextSubpass2 import vkCmdNextSubpass2
from ._vulkan_procedure.vkCmdOpticalFlowExecuteNV import vkCmdOpticalFlowExecuteNV
from ._vulkan_procedure.vkCmdPipelineBarrier import vkCmdPipelineBarrier
from ._vulkan_procedure.vkCmdPipelineBarrier2 import vkCmdPipelineBarrier2
from ._vulkan_procedure.vkCmdPreprocessGeneratedCommandsNV import vkCmdPreprocessGeneratedCommandsNV
from ._vulkan_procedure.vkCmdPushConstants import vkCmdPushConstants
from ._vulkan_procedure.vkCmdPushConstants2KHR import vkCmdPushConstants2KHR
from ._vulkan_procedure.vkCmdPushDescriptorSet2KHR import vkCmdPushDescriptorSet2KHR
from ._vulkan_procedure.vkCmdPushDescriptorSetKHR import vkCmdPushDescriptorSetKHR
from ._vulkan_procedure.vkCmdPushDescriptorSetWithTemplate2KHR import vkCmdPushDescriptorSetWithTemplate2KHR
from ._vulkan_procedure.vkCmdPushDescriptorSetWithTemplateKHR import vkCmdPushDescriptorSetWithTemplateKHR
from ._vulkan_procedure.vkCmdResetEvent import vkCmdResetEvent
from ._vulkan_procedure.vkCmdResetEvent2 import vkCmdResetEvent2
from ._vulkan_procedure.vkCmdResetQueryPool import vkCmdResetQueryPool
from ._vulkan_procedure.vkCmdResolveImage import vkCmdResolveImage
from ._vulkan_procedure.vkCmdResolveImage2 import vkCmdResolveImage2
from ._vulkan_procedure.vkCmdSetAlphaToCoverageEnableEXT import vkCmdSetAlphaToCoverageEnableEXT
from ._vulkan_procedure.vkCmdSetAlphaToOneEnableEXT import vkCmdSetAlphaToOneEnableEXT
from ._vulkan_procedure.vkCmdSetAttachmentFeedbackLoopEnableEXT import vkCmdSetAttachmentFeedbackLoopEnableEXT
from ._vulkan_procedure.vkCmdSetBlendConstants import vkCmdSetBlendConstants
from ._vulkan_procedure.vkCmdSetCheckpointNV import vkCmdSetCheckpointNV
from ._vulkan_procedure.vkCmdSetCoarseSampleOrderNV import vkCmdSetCoarseSampleOrderNV
from ._vulkan_procedure.vkCmdSetColorBlendAdvancedEXT import vkCmdSetColorBlendAdvancedEXT
from ._vulkan_procedure.vkCmdSetColorBlendEnableEXT import vkCmdSetColorBlendEnableEXT
from ._vulkan_procedure.vkCmdSetColorBlendEquationEXT import vkCmdSetColorBlendEquationEXT
from ._vulkan_procedure.vkCmdSetColorWriteEnableEXT import vkCmdSetColorWriteEnableEXT
from ._vulkan_procedure.vkCmdSetColorWriteMaskEXT import vkCmdSetColorWriteMaskEXT
from ._vulkan_procedure.vkCmdSetConservativeRasterizationModeEXT import vkCmdSetConservativeRasterizationModeEXT
from ._vulkan_procedure.vkCmdSetCoverageModulationModeNV import vkCmdSetCoverageModulationModeNV
from ._vulkan_procedure.vkCmdSetCoverageModulationTableEnableNV import vkCmdSetCoverageModulationTableEnableNV
from ._vulkan_procedure.vkCmdSetCoverageModulationTableNV import vkCmdSetCoverageModulationTableNV
from ._vulkan_procedure.vkCmdSetCoverageReductionModeNV import vkCmdSetCoverageReductionModeNV
from ._vulkan_procedure.vkCmdSetCoverageToColorEnableNV import vkCmdSetCoverageToColorEnableNV
from ._vulkan_procedure.vkCmdSetCoverageToColorLocationNV import vkCmdSetCoverageToColorLocationNV
from ._vulkan_procedure.vkCmdSetCullMode import vkCmdSetCullMode
from ._vulkan_procedure.vkCmdSetDepthBias import vkCmdSetDepthBias
from ._vulkan_procedure.vkCmdSetDepthBias2EXT import vkCmdSetDepthBias2EXT
from ._vulkan_procedure.vkCmdSetDepthBiasEnable import vkCmdSetDepthBiasEnable
from ._vulkan_procedure.vkCmdSetDepthBounds import vkCmdSetDepthBounds
from ._vulkan_procedure.vkCmdSetDepthBoundsTestEnable import vkCmdSetDepthBoundsTestEnable
from ._vulkan_procedure.vkCmdSetDepthClampEnableEXT import vkCmdSetDepthClampEnableEXT
from ._vulkan_procedure.vkCmdSetDepthClipEnableEXT import vkCmdSetDepthClipEnableEXT
from ._vulkan_procedure.vkCmdSetDepthClipNegativeOneToOneEXT import vkCmdSetDepthClipNegativeOneToOneEXT
from ._vulkan_procedure.vkCmdSetDepthCompareOp import vkCmdSetDepthCompareOp
from ._vulkan_procedure.vkCmdSetDepthTestEnable import vkCmdSetDepthTestEnable
from ._vulkan_procedure.vkCmdSetDepthWriteEnable import vkCmdSetDepthWriteEnable
from ._vulkan_procedure.vkCmdSetDescriptorBufferOffsets2EXT import vkCmdSetDescriptorBufferOffsets2EXT
from ._vulkan_procedure.vkCmdSetDescriptorBufferOffsetsEXT import vkCmdSetDescriptorBufferOffsetsEXT
from ._vulkan_procedure.vkCmdSetDeviceMask import vkCmdSetDeviceMask
from ._vulkan_procedure.vkCmdSetDiscardRectangleEXT import vkCmdSetDiscardRectangleEXT
from ._vulkan_procedure.vkCmdSetDiscardRectangleEnableEXT import vkCmdSetDiscardRectangleEnableEXT
from ._vulkan_procedure.vkCmdSetDiscardRectangleModeEXT import vkCmdSetDiscardRectangleModeEXT
from ._vulkan_procedure.vkCmdSetEvent import vkCmdSetEvent
from ._vulkan_procedure.vkCmdSetEvent2 import vkCmdSetEvent2
from ._vulkan_procedure.vkCmdSetExclusiveScissorEnableNV import vkCmdSetExclusiveScissorEnableNV
from ._vulkan_procedure.vkCmdSetExclusiveScissorNV import vkCmdSetExclusiveScissorNV
from ._vulkan_procedure.vkCmdSetExtraPrimitiveOverestimationSizeEXT import vkCmdSetExtraPrimitiveOverestimationSizeEXT
from ._vulkan_procedure.vkCmdSetFragmentShadingRateEnumNV import vkCmdSetFragmentShadingRateEnumNV
from ._vulkan_procedure.vkCmdSetFragmentShadingRateKHR import vkCmdSetFragmentShadingRateKHR
from ._vulkan_procedure.vkCmdSetFrontFace import vkCmdSetFrontFace
from ._vulkan_procedure.vkCmdSetLineRasterizationModeEXT import vkCmdSetLineRasterizationModeEXT
from ._vulkan_procedure.vkCmdSetLineStippleEnableEXT import vkCmdSetLineStippleEnableEXT
from ._vulkan_procedure.vkCmdSetLineStippleKHR import vkCmdSetLineStippleKHR
from ._vulkan_procedure.vkCmdSetLineWidth import vkCmdSetLineWidth
from ._vulkan_procedure.vkCmdSetLogicOpEXT import vkCmdSetLogicOpEXT
from ._vulkan_procedure.vkCmdSetLogicOpEnableEXT import vkCmdSetLogicOpEnableEXT
from ._vulkan_procedure.vkCmdSetPatchControlPointsEXT import vkCmdSetPatchControlPointsEXT
from ._vulkan_procedure.vkCmdSetPerformanceMarkerINTEL import vkCmdSetPerformanceMarkerINTEL
from ._vulkan_procedure.vkCmdSetPerformanceOverrideINTEL import vkCmdSetPerformanceOverrideINTEL
from ._vulkan_procedure.vkCmdSetPerformanceStreamMarkerINTEL import vkCmdSetPerformanceStreamMarkerINTEL
from ._vulkan_procedure.vkCmdSetPolygonModeEXT import vkCmdSetPolygonModeEXT
from ._vulkan_procedure.vkCmdSetPrimitiveRestartEnable import vkCmdSetPrimitiveRestartEnable
from ._vulkan_procedure.vkCmdSetPrimitiveTopology import vkCmdSetPrimitiveTopology
from ._vulkan_procedure.vkCmdSetProvokingVertexModeEXT import vkCmdSetProvokingVertexModeEXT
from ._vulkan_procedure.vkCmdSetRasterizationSamplesEXT import vkCmdSetRasterizationSamplesEXT
from ._vulkan_procedure.vkCmdSetRasterizationStreamEXT import vkCmdSetRasterizationStreamEXT
from ._vulkan_procedure.vkCmdSetRasterizerDiscardEnable import vkCmdSetRasterizerDiscardEnable
from ._vulkan_procedure.vkCmdSetRayTracingPipelineStackSizeKHR import vkCmdSetRayTracingPipelineStackSizeKHR
from ._vulkan_procedure.vkCmdSetRenderingAttachmentLocationsKHR import vkCmdSetRenderingAttachmentLocationsKHR
from ._vulkan_procedure.vkCmdSetRenderingInputAttachmentIndicesKHR import vkCmdSetRenderingInputAttachmentIndicesKHR
from ._vulkan_procedure.vkCmdSetRepresentativeFragmentTestEnableNV import vkCmdSetRepresentativeFragmentTestEnableNV
from ._vulkan_procedure.vkCmdSetSampleLocationsEXT import vkCmdSetSampleLocationsEXT
from ._vulkan_procedure.vkCmdSetSampleLocationsEnableEXT import vkCmdSetSampleLocationsEnableEXT
from ._vulkan_procedure.vkCmdSetSampleMaskEXT import vkCmdSetSampleMaskEXT
from ._vulkan_procedure.vkCmdSetScissor import vkCmdSetScissor
from ._vulkan_procedure.vkCmdSetScissorWithCount import vkCmdSetScissorWithCount
from ._vulkan_procedure.vkCmdSetShadingRateImageEnableNV import vkCmdSetShadingRateImageEnableNV
from ._vulkan_procedure.vkCmdSetStencilCompareMask import vkCmdSetStencilCompareMask
from ._vulkan_procedure.vkCmdSetStencilOp import vkCmdSetStencilOp
from ._vulkan_procedure.vkCmdSetStencilReference import vkCmdSetStencilReference
from ._vulkan_procedure.vkCmdSetStencilTestEnable import vkCmdSetStencilTestEnable
from ._vulkan_procedure.vkCmdSetStencilWriteMask import vkCmdSetStencilWriteMask
from ._vulkan_procedure.vkCmdSetTessellationDomainOriginEXT import vkCmdSetTessellationDomainOriginEXT
from ._vulkan_procedure.vkCmdSetVertexInputEXT import vkCmdSetVertexInputEXT
from ._vulkan_procedure.vkCmdSetViewport import vkCmdSetViewport
from ._vulkan_procedure.vkCmdSetViewportShadingRatePaletteNV import vkCmdSetViewportShadingRatePaletteNV
from ._vulkan_procedure.vkCmdSetViewportSwizzleNV import vkCmdSetViewportSwizzleNV
from ._vulkan_procedure.vkCmdSetViewportWScalingEnableNV import vkCmdSetViewportWScalingEnableNV
from ._vulkan_procedure.vkCmdSetViewportWScalingNV import vkCmdSetViewportWScalingNV
from ._vulkan_procedure.vkCmdSetViewportWithCount import vkCmdSetViewportWithCount
from ._vulkan_procedure.vkCmdSubpassShadingHUAWEI import vkCmdSubpassShadingHUAWEI
from ._vulkan_procedure.vkCmdTraceRaysIndirect2KHR import vkCmdTraceRaysIndirect2KHR
from ._vulkan_procedure.vkCmdTraceRaysIndirectKHR import vkCmdTraceRaysIndirectKHR
from ._vulkan_procedure.vkCmdTraceRaysKHR import vkCmdTraceRaysKHR
from ._vulkan_procedure.vkCmdTraceRaysNV import vkCmdTraceRaysNV
from ._vulkan_procedure.vkCmdUpdateBuffer import vkCmdUpdateBuffer
from ._vulkan_procedure.vkCmdUpdatePipelineIndirectBufferNV import vkCmdUpdatePipelineIndirectBufferNV
from ._vulkan_procedure.vkCmdWaitEvents import vkCmdWaitEvents
from ._vulkan_procedure.vkCmdWaitEvents2 import vkCmdWaitEvents2
from ._vulkan_procedure.vkCmdWriteAccelerationStructuresPropertiesKHR import vkCmdWriteAccelerationStructuresPropertiesKHR
from ._vulkan_procedure.vkCmdWriteAccelerationStructuresPropertiesNV import vkCmdWriteAccelerationStructuresPropertiesNV
from ._vulkan_procedure.vkCmdWriteBufferMarker2AMD import vkCmdWriteBufferMarker2AMD
from ._vulkan_procedure.vkCmdWriteBufferMarkerAMD import vkCmdWriteBufferMarkerAMD
from ._vulkan_procedure.vkCmdWriteMicromapsPropertiesEXT import vkCmdWriteMicromapsPropertiesEXT
from ._vulkan_procedure.vkCmdWriteTimestamp import vkCmdWriteTimestamp
from ._vulkan_procedure.vkCmdWriteTimestamp2 import vkCmdWriteTimestamp2
from ._vulkan_procedure.vkCompileDeferredNV import vkCompileDeferredNV
from ._vulkan_procedure.vkCopyAccelerationStructureKHR import vkCopyAccelerationStructureKHR
from ._vulkan_procedure.vkCopyAccelerationStructureToMemoryKHR import vkCopyAccelerationStructureToMemoryKHR
from ._vulkan_procedure.vkCopyImageToImageEXT import vkCopyImageToImageEXT
from ._vulkan_procedure.vkCopyImageToMemoryEXT import vkCopyImageToMemoryEXT
from ._vulkan_procedure.vkCopyMemoryToAccelerationStructureKHR import vkCopyMemoryToAccelerationStructureKHR
from ._vulkan_procedure.vkCopyMemoryToImageEXT import vkCopyMemoryToImageEXT
from ._vulkan_procedure.vkCopyMemoryToMicromapEXT import vkCopyMemoryToMicromapEXT
from ._vulkan_procedure.vkCopyMicromapEXT import vkCopyMicromapEXT
from ._vulkan_procedure.vkCopyMicromapToMemoryEXT import vkCopyMicromapToMemoryEXT
from ._vulkan_procedure.vkCreateAccelerationStructureKHR import vkCreateAccelerationStructureKHR
from ._vulkan_procedure.vkCreateAccelerationStructureNV import vkCreateAccelerationStructureNV
from ._vulkan_procedure.vkCreateAndroidSurfaceKHR import vkCreateAndroidSurfaceKHR
from ._vulkan_procedure.vkCreateBuffer import vkCreateBuffer
from ._vulkan_procedure.vkCreateBufferCollectionFUCHSIA import vkCreateBufferCollectionFUCHSIA
from ._vulkan_procedure.vkCreateBufferView import vkCreateBufferView
from ._vulkan_procedure.vkCreateCommandPool import vkCreateCommandPool
from ._vulkan_procedure.vkCreateComputePipelines import vkCreateComputePipelines
from ._vulkan_procedure.vkCreateCuFunctionNVX import vkCreateCuFunctionNVX
from ._vulkan_procedure.vkCreateCuModuleNVX import vkCreateCuModuleNVX
from ._vulkan_procedure.vkCreateCudaFunctionNV import vkCreateCudaFunctionNV
from ._vulkan_procedure.vkCreateCudaModuleNV import vkCreateCudaModuleNV
from ._vulkan_procedure.vkCreateDebugReportCallbackEXT import vkCreateDebugReportCallbackEXT
from ._vulkan_procedure.vkCreateDebugUtilsMessengerEXT import vkCreateDebugUtilsMessengerEXT
from ._vulkan_procedure.vkCreateDeferredOperationKHR import vkCreateDeferredOperationKHR
from ._vulkan_procedure.vkCreateDescriptorPool import vkCreateDescriptorPool
from ._vulkan_procedure.vkCreateDescriptorSetLayout import vkCreateDescriptorSetLayout
from ._vulkan_procedure.vkCreateDescriptorUpdateTemplate import vkCreateDescriptorUpdateTemplate
from ._vulkan_procedure.vkCreateDevice import vkCreateDevice
from ._vulkan_procedure.vkCreateDirectFBSurfaceEXT import vkCreateDirectFBSurfaceEXT
from ._vulkan_procedure.vkCreateDisplayModeKHR import vkCreateDisplayModeKHR
from ._vulkan_procedure.vkCreateDisplayPlaneSurfaceKHR import vkCreateDisplayPlaneSurfaceKHR
from ._vulkan_procedure.vkCreateEvent import vkCreateEvent
from ._vulkan_procedure.vkCreateExecutionGraphPipelinesAMDX import vkCreateExecutionGraphPipelinesAMDX
from ._vulkan_procedure.vkCreateFence import vkCreateFence
from ._vulkan_procedure.vkCreateFramebuffer import vkCreateFramebuffer
from ._vulkan_procedure.vkCreateGraphicsPipelines import vkCreateGraphicsPipelines
from ._vulkan_procedure.vkCreateHeadlessSurfaceEXT import vkCreateHeadlessSurfaceEXT
from ._vulkan_procedure.vkCreateIOSSurfaceMVK import vkCreateIOSSurfaceMVK
from ._vulkan_procedure.vkCreateImage import vkCreateImage
from ._vulkan_procedure.vkCreateImagePipeSurfaceFUCHSIA import vkCreateImagePipeSurfaceFUCHSIA
from ._vulkan_procedure.vkCreateImageView import vkCreateImageView
from ._vulkan_procedure.vkCreateIndirectCommandsLayoutNV import vkCreateIndirectCommandsLayoutNV
from ._vulkan_procedure.vkCreateInstance import vkCreateInstance
from ._vulkan_procedure.vkCreateMacOSSurfaceMVK import vkCreateMacOSSurfaceMVK
from ._vulkan_procedure.vkCreateMetalSurfaceEXT import vkCreateMetalSurfaceEXT
from ._vulkan_procedure.vkCreateMicromapEXT import vkCreateMicromapEXT
from ._vulkan_procedure.vkCreateOpticalFlowSessionNV import vkCreateOpticalFlowSessionNV
from ._vulkan_procedure.vkCreatePipelineCache import vkCreatePipelineCache
from ._vulkan_procedure.vkCreatePipelineLayout import vkCreatePipelineLayout
from ._vulkan_procedure.vkCreatePrivateDataSlot import vkCreatePrivateDataSlot
from ._vulkan_procedure.vkCreateQueryPool import vkCreateQueryPool
from ._vulkan_procedure.vkCreateRayTracingPipelinesKHR import vkCreateRayTracingPipelinesKHR
from ._vulkan_procedure.vkCreateRayTracingPipelinesNV import vkCreateRayTracingPipelinesNV
from ._vulkan_procedure.vkCreateRenderPass import vkCreateRenderPass
from ._vulkan_procedure.vkCreateRenderPass2 import vkCreateRenderPass2
from ._vulkan_procedure.vkCreateSampler import vkCreateSampler
from ._vulkan_procedure.vkCreateSamplerYcbcrConversion import vkCreateSamplerYcbcrConversion
from ._vulkan_procedure.vkCreateScreenSurfaceQNX import vkCreateScreenSurfaceQNX
from ._vulkan_procedure.vkCreateSemaphore import vkCreateSemaphore
from ._vulkan_procedure.vkCreateShaderModule import vkCreateShaderModule
from ._vulkan_procedure.vkCreateShadersEXT import vkCreateShadersEXT
from ._vulkan_procedure.vkCreateSharedSwapchainsKHR import vkCreateSharedSwapchainsKHR
from ._vulkan_procedure.vkCreateStreamDescriptorSurfaceGGP import vkCreateStreamDescriptorSurfaceGGP
from ._vulkan_procedure.vkCreateSwapchainKHR import vkCreateSwapchainKHR
from ._vulkan_procedure.vkCreateValidationCacheEXT import vkCreateValidationCacheEXT
from ._vulkan_procedure.vkCreateViSurfaceNN import vkCreateViSurfaceNN
from ._vulkan_procedure.vkCreateVideoSessionKHR import vkCreateVideoSessionKHR
from ._vulkan_procedure.vkCreateVideoSessionParametersKHR import vkCreateVideoSessionParametersKHR
from ._vulkan_procedure.vkCreateWaylandSurfaceKHR import vkCreateWaylandSurfaceKHR
from ._vulkan_procedure.vkCreateWin32SurfaceKHR import vkCreateWin32SurfaceKHR
from ._vulkan_procedure.vkCreateXcbSurfaceKHR import vkCreateXcbSurfaceKHR
from ._vulkan_procedure.vkCreateXlibSurfaceKHR import vkCreateXlibSurfaceKHR
from ._vulkan_procedure.vkDebugMarkerSetObjectNameEXT import vkDebugMarkerSetObjectNameEXT
from ._vulkan_procedure.vkDebugMarkerSetObjectTagEXT import vkDebugMarkerSetObjectTagEXT
from ._vulkan_procedure.vkDebugReportMessageEXT import vkDebugReportMessageEXT
from ._vulkan_procedure.vkDeferredOperationJoinKHR import vkDeferredOperationJoinKHR
from ._vulkan_procedure.vkDestroyAccelerationStructureKHR import vkDestroyAccelerationStructureKHR
from ._vulkan_procedure.vkDestroyAccelerationStructureNV import vkDestroyAccelerationStructureNV
from ._vulkan_procedure.vkDestroyBuffer import vkDestroyBuffer
from ._vulkan_procedure.vkDestroyBufferCollectionFUCHSIA import vkDestroyBufferCollectionFUCHSIA
from ._vulkan_procedure.vkDestroyBufferView import vkDestroyBufferView
from ._vulkan_procedure.vkDestroyCommandPool import vkDestroyCommandPool
from ._vulkan_procedure.vkDestroyCuFunctionNVX import vkDestroyCuFunctionNVX
from ._vulkan_procedure.vkDestroyCuModuleNVX import vkDestroyCuModuleNVX
from ._vulkan_procedure.vkDestroyCudaFunctionNV import vkDestroyCudaFunctionNV
from ._vulkan_procedure.vkDestroyCudaModuleNV import vkDestroyCudaModuleNV
from ._vulkan_procedure.vkDestroyDebugReportCallbackEXT import vkDestroyDebugReportCallbackEXT
from ._vulkan_procedure.vkDestroyDebugUtilsMessengerEXT import vkDestroyDebugUtilsMessengerEXT
from ._vulkan_procedure.vkDestroyDeferredOperationKHR import vkDestroyDeferredOperationKHR
from ._vulkan_procedure.vkDestroyDescriptorPool import vkDestroyDescriptorPool
from ._vulkan_procedure.vkDestroyDescriptorSetLayout import vkDestroyDescriptorSetLayout
from ._vulkan_procedure.vkDestroyDescriptorUpdateTemplate import vkDestroyDescriptorUpdateTemplate
from ._vulkan_procedure.vkDestroyDevice import vkDestroyDevice
from ._vulkan_procedure.vkDestroyEvent import vkDestroyEvent
from ._vulkan_procedure.vkDestroyFence import vkDestroyFence
from ._vulkan_procedure.vkDestroyFramebuffer import vkDestroyFramebuffer
from ._vulkan_procedure.vkDestroyImage import vkDestroyImage
from ._vulkan_procedure.vkDestroyImageView import vkDestroyImageView
from ._vulkan_procedure.vkDestroyIndirectCommandsLayoutNV import vkDestroyIndirectCommandsLayoutNV
from ._vulkan_procedure.vkDestroyInstance import vkDestroyInstance
from ._vulkan_procedure.vkDestroyMicromapEXT import vkDestroyMicromapEXT
from ._vulkan_procedure.vkDestroyOpticalFlowSessionNV import vkDestroyOpticalFlowSessionNV
from ._vulkan_procedure.vkDestroyPipeline import vkDestroyPipeline
from ._vulkan_procedure.vkDestroyPipelineCache import vkDestroyPipelineCache
from ._vulkan_procedure.vkDestroyPipelineLayout import vkDestroyPipelineLayout
from ._vulkan_procedure.vkDestroyPrivateDataSlot import vkDestroyPrivateDataSlot
from ._vulkan_procedure.vkDestroyQueryPool import vkDestroyQueryPool
from ._vulkan_procedure.vkDestroyRenderPass import vkDestroyRenderPass
from ._vulkan_procedure.vkDestroySampler import vkDestroySampler
from ._vulkan_procedure.vkDestroySamplerYcbcrConversion import vkDestroySamplerYcbcrConversion
from ._vulkan_procedure.vkDestroySemaphore import vkDestroySemaphore
from ._vulkan_procedure.vkDestroySemaphoreSciSyncPoolNV import vkDestroySemaphoreSciSyncPoolNV
from ._vulkan_procedure.vkDestroyShaderEXT import vkDestroyShaderEXT
from ._vulkan_procedure.vkDestroyShaderModule import vkDestroyShaderModule
from ._vulkan_procedure.vkDestroySurfaceKHR import vkDestroySurfaceKHR
from ._vulkan_procedure.vkDestroySwapchainKHR import vkDestroySwapchainKHR
from ._vulkan_procedure.vkDestroyValidationCacheEXT import vkDestroyValidationCacheEXT
from ._vulkan_procedure.vkDestroyVideoSessionKHR import vkDestroyVideoSessionKHR
from ._vulkan_procedure.vkDestroyVideoSessionParametersKHR import vkDestroyVideoSessionParametersKHR
from ._vulkan_procedure.vkDeviceWaitIdle import vkDeviceWaitIdle
from ._vulkan_procedure.vkDisplayPowerControlEXT import vkDisplayPowerControlEXT
from ._vulkan_procedure.vkEndCommandBuffer import vkEndCommandBuffer
from ._vulkan_procedure.vkEnumerateDeviceExtensionProperties import vkEnumerateDeviceExtensionProperties
from ._vulkan_procedure.vkEnumerateDeviceLayerProperties import vkEnumerateDeviceLayerProperties
from ._vulkan_procedure.vkEnumerateInstanceExtensionProperties import vkEnumerateInstanceExtensionProperties
from ._vulkan_procedure.vkEnumerateInstanceLayerProperties import vkEnumerateInstanceLayerProperties
from ._vulkan_procedure.vkEnumerateInstanceVersion import vkEnumerateInstanceVersion
from ._vulkan_procedure.vkEnumeratePhysicalDeviceGroups import vkEnumeratePhysicalDeviceGroups
from ._vulkan_procedure.vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR import vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR
from ._vulkan_procedure.vkEnumeratePhysicalDevices import vkEnumeratePhysicalDevices
from ._vulkan_procedure.vkExportMetalObjectsEXT import vkExportMetalObjectsEXT
from ._vulkan_procedure.vkFlushMappedMemoryRanges import vkFlushMappedMemoryRanges
from ._vulkan_procedure.vkFreeCommandBuffers import vkFreeCommandBuffers
from ._vulkan_procedure.vkFreeDescriptorSets import vkFreeDescriptorSets
from ._vulkan_procedure.vkFreeMemory import vkFreeMemory
from ._vulkan_procedure.vkGetAccelerationStructureBuildSizesKHR import vkGetAccelerationStructureBuildSizesKHR
from ._vulkan_procedure.vkGetAccelerationStructureDeviceAddressKHR import vkGetAccelerationStructureDeviceAddressKHR
from ._vulkan_procedure.vkGetAccelerationStructureHandleNV import vkGetAccelerationStructureHandleNV
from ._vulkan_procedure.vkGetAccelerationStructureMemoryRequirementsNV import vkGetAccelerationStructureMemoryRequirementsNV
from ._vulkan_procedure.vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT import vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT
from ._vulkan_procedure.vkGetAndroidHardwareBufferPropertiesANDROID import vkGetAndroidHardwareBufferPropertiesANDROID
from ._vulkan_procedure.vkGetBufferCollectionPropertiesFUCHSIA import vkGetBufferCollectionPropertiesFUCHSIA
from ._vulkan_procedure.vkGetBufferDeviceAddress import vkGetBufferDeviceAddress
from ._vulkan_procedure.vkGetBufferMemoryRequirements import vkGetBufferMemoryRequirements
from ._vulkan_procedure.vkGetBufferMemoryRequirements2 import vkGetBufferMemoryRequirements2
from ._vulkan_procedure.vkGetBufferOpaqueCaptureAddress import vkGetBufferOpaqueCaptureAddress
from ._vulkan_procedure.vkGetBufferOpaqueCaptureDescriptorDataEXT import vkGetBufferOpaqueCaptureDescriptorDataEXT
from ._vulkan_procedure.vkGetCalibratedTimestampsKHR import vkGetCalibratedTimestampsKHR
from ._vulkan_procedure.vkGetCudaModuleCacheNV import vkGetCudaModuleCacheNV
from ._vulkan_procedure.vkGetDeferredOperationMaxConcurrencyKHR import vkGetDeferredOperationMaxConcurrencyKHR
from ._vulkan_procedure.vkGetDeferredOperationResultKHR import vkGetDeferredOperationResultKHR
from ._vulkan_procedure.vkGetDescriptorEXT import vkGetDescriptorEXT
from ._vulkan_procedure.vkGetDescriptorSetHostMappingVALVE import vkGetDescriptorSetHostMappingVALVE
from ._vulkan_procedure.vkGetDescriptorSetLayoutBindingOffsetEXT import vkGetDescriptorSetLayoutBindingOffsetEXT
from ._vulkan_procedure.vkGetDescriptorSetLayoutHostMappingInfoVALVE import vkGetDescriptorSetLayoutHostMappingInfoVALVE
from ._vulkan_procedure.vkGetDescriptorSetLayoutSizeEXT import vkGetDescriptorSetLayoutSizeEXT
from ._vulkan_procedure.vkGetDescriptorSetLayoutSupport import vkGetDescriptorSetLayoutSupport
from ._vulkan_procedure.vkGetDeviceAccelerationStructureCompatibilityKHR import vkGetDeviceAccelerationStructureCompatibilityKHR
from ._vulkan_procedure.vkGetDeviceBufferMemoryRequirements import vkGetDeviceBufferMemoryRequirements
from ._vulkan_procedure.vkGetDeviceFaultInfoEXT import vkGetDeviceFaultInfoEXT
from ._vulkan_procedure.vkGetDeviceGroupPeerMemoryFeatures import vkGetDeviceGroupPeerMemoryFeatures
from ._vulkan_procedure.vkGetDeviceGroupPresentCapabilitiesKHR import vkGetDeviceGroupPresentCapabilitiesKHR
from ._vulkan_procedure.vkGetDeviceGroupSurfacePresentModes2EXT import vkGetDeviceGroupSurfacePresentModes2EXT
from ._vulkan_procedure.vkGetDeviceGroupSurfacePresentModesKHR import vkGetDeviceGroupSurfacePresentModesKHR
from ._vulkan_procedure.vkGetDeviceImageMemoryRequirements import vkGetDeviceImageMemoryRequirements
from ._vulkan_procedure.vkGetDeviceImageSparseMemoryRequirements import vkGetDeviceImageSparseMemoryRequirements
from ._vulkan_procedure.vkGetDeviceImageSubresourceLayoutKHR import vkGetDeviceImageSubresourceLayoutKHR
from ._vulkan_procedure.vkGetDeviceMemoryCommitment import vkGetDeviceMemoryCommitment
from ._vulkan_procedure.vkGetDeviceMemoryOpaqueCaptureAddress import vkGetDeviceMemoryOpaqueCaptureAddress
from ._vulkan_procedure.vkGetDeviceMicromapCompatibilityEXT import vkGetDeviceMicromapCompatibilityEXT
from ._vulkan_procedure.vkGetDeviceProcAddr import vkGetDeviceProcAddr
from ._vulkan_procedure.vkGetDeviceQueue import vkGetDeviceQueue
from ._vulkan_procedure.vkGetDeviceQueue2 import vkGetDeviceQueue2
from ._vulkan_procedure.vkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI import vkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI
from ._vulkan_procedure.vkGetDisplayModeProperties2KHR import vkGetDisplayModeProperties2KHR
from ._vulkan_procedure.vkGetDisplayModePropertiesKHR import vkGetDisplayModePropertiesKHR
from ._vulkan_procedure.vkGetDisplayPlaneCapabilities2KHR import vkGetDisplayPlaneCapabilities2KHR
from ._vulkan_procedure.vkGetDisplayPlaneCapabilitiesKHR import vkGetDisplayPlaneCapabilitiesKHR
from ._vulkan_procedure.vkGetDisplayPlaneSupportedDisplaysKHR import vkGetDisplayPlaneSupportedDisplaysKHR
from ._vulkan_procedure.vkGetDrmDisplayEXT import vkGetDrmDisplayEXT
from ._vulkan_procedure.vkGetDynamicRenderingTilePropertiesQCOM import vkGetDynamicRenderingTilePropertiesQCOM
from ._vulkan_procedure.vkGetEncodedVideoSessionParametersKHR import vkGetEncodedVideoSessionParametersKHR
from ._vulkan_procedure.vkGetEventStatus import vkGetEventStatus
from ._vulkan_procedure.vkGetExecutionGraphPipelineNodeIndexAMDX import vkGetExecutionGraphPipelineNodeIndexAMDX
from ._vulkan_procedure.vkGetExecutionGraphPipelineScratchSizeAMDX import vkGetExecutionGraphPipelineScratchSizeAMDX
from ._vulkan_procedure.vkGetFenceFdKHR import vkGetFenceFdKHR
from ._vulkan_procedure.vkGetFenceStatus import vkGetFenceStatus
from ._vulkan_procedure.vkGetFenceWin32HandleKHR import vkGetFenceWin32HandleKHR
from ._vulkan_procedure.vkGetFramebufferTilePropertiesQCOM import vkGetFramebufferTilePropertiesQCOM
from ._vulkan_procedure.vkGetGeneratedCommandsMemoryRequirementsNV import vkGetGeneratedCommandsMemoryRequirementsNV
from ._vulkan_procedure.vkGetImageDrmFormatModifierPropertiesEXT import vkGetImageDrmFormatModifierPropertiesEXT
from ._vulkan_procedure.vkGetImageMemoryRequirements import vkGetImageMemoryRequirements
from ._vulkan_procedure.vkGetImageMemoryRequirements2 import vkGetImageMemoryRequirements2
from ._vulkan_procedure.vkGetImageOpaqueCaptureDescriptorDataEXT import vkGetImageOpaqueCaptureDescriptorDataEXT
from ._vulkan_procedure.vkGetImageSparseMemoryRequirements import vkGetImageSparseMemoryRequirements
from ._vulkan_procedure.vkGetImageSparseMemoryRequirements2 import vkGetImageSparseMemoryRequirements2
from ._vulkan_procedure.vkGetImageSubresourceLayout import vkGetImageSubresourceLayout
from ._vulkan_procedure.vkGetImageSubresourceLayout2KHR import vkGetImageSubresourceLayout2KHR
from ._vulkan_procedure.vkGetImageViewAddressNVX import vkGetImageViewAddressNVX
from ._vulkan_procedure.vkGetImageViewHandleNVX import vkGetImageViewHandleNVX
from ._vulkan_procedure.vkGetImageViewOpaqueCaptureDescriptorDataEXT import vkGetImageViewOpaqueCaptureDescriptorDataEXT
from ._vulkan_procedure.vkGetInstanceProcAddr import vkGetInstanceProcAddr
from ._vulkan_procedure.vkGetLatencyTimingsNV import vkGetLatencyTimingsNV
from ._vulkan_procedure.vkGetMemoryAndroidHardwareBufferANDROID import vkGetMemoryAndroidHardwareBufferANDROID
from ._vulkan_procedure.vkGetMemoryFdKHR import vkGetMemoryFdKHR
from ._vulkan_procedure.vkGetMemoryFdPropertiesKHR import vkGetMemoryFdPropertiesKHR
from ._vulkan_procedure.vkGetMemoryHostPointerPropertiesEXT import vkGetMemoryHostPointerPropertiesEXT
from ._vulkan_procedure.vkGetMemoryRemoteAddressNV import vkGetMemoryRemoteAddressNV
from ._vulkan_procedure.vkGetMemoryWin32HandleKHR import vkGetMemoryWin32HandleKHR
from ._vulkan_procedure.vkGetMemoryWin32HandleNV import vkGetMemoryWin32HandleNV
from ._vulkan_procedure.vkGetMemoryWin32HandlePropertiesKHR import vkGetMemoryWin32HandlePropertiesKHR
from ._vulkan_procedure.vkGetMemoryZirconHandleFUCHSIA import vkGetMemoryZirconHandleFUCHSIA
from ._vulkan_procedure.vkGetMemoryZirconHandlePropertiesFUCHSIA import vkGetMemoryZirconHandlePropertiesFUCHSIA
from ._vulkan_procedure.vkGetMicromapBuildSizesEXT import vkGetMicromapBuildSizesEXT
from ._vulkan_procedure.vkGetPastPresentationTimingGOOGLE import vkGetPastPresentationTimingGOOGLE
from ._vulkan_procedure.vkGetPerformanceParameterINTEL import vkGetPerformanceParameterINTEL
from ._vulkan_procedure.vkGetPhysicalDeviceCalibrateableTimeDomainsKHR import vkGetPhysicalDeviceCalibrateableTimeDomainsKHR
from ._vulkan_procedure.vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR import vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR
from ._vulkan_procedure.vkGetPhysicalDeviceCooperativeMatrixPropertiesNV import vkGetPhysicalDeviceCooperativeMatrixPropertiesNV
from ._vulkan_procedure.vkGetPhysicalDeviceDirectFBPresentationSupportEXT import vkGetPhysicalDeviceDirectFBPresentationSupportEXT
from ._vulkan_procedure.vkGetPhysicalDeviceDisplayPlaneProperties2KHR import vkGetPhysicalDeviceDisplayPlaneProperties2KHR
from ._vulkan_procedure.vkGetPhysicalDeviceDisplayPlanePropertiesKHR import vkGetPhysicalDeviceDisplayPlanePropertiesKHR
from ._vulkan_procedure.vkGetPhysicalDeviceDisplayProperties2KHR import vkGetPhysicalDeviceDisplayProperties2KHR
from ._vulkan_procedure.vkGetPhysicalDeviceDisplayPropertiesKHR import vkGetPhysicalDeviceDisplayPropertiesKHR
from ._vulkan_procedure.vkGetPhysicalDeviceExternalBufferProperties import vkGetPhysicalDeviceExternalBufferProperties
from ._vulkan_procedure.vkGetPhysicalDeviceExternalFenceProperties import vkGetPhysicalDeviceExternalFenceProperties
from ._vulkan_procedure.vkGetPhysicalDeviceExternalImageFormatPropertiesNV import vkGetPhysicalDeviceExternalImageFormatPropertiesNV
from ._vulkan_procedure.vkGetPhysicalDeviceExternalSemaphoreProperties import vkGetPhysicalDeviceExternalSemaphoreProperties
from ._vulkan_procedure.vkGetPhysicalDeviceFeatures import vkGetPhysicalDeviceFeatures
from ._vulkan_procedure.vkGetPhysicalDeviceFeatures2 import vkGetPhysicalDeviceFeatures2
from ._vulkan_procedure.vkGetPhysicalDeviceFormatProperties import vkGetPhysicalDeviceFormatProperties
from ._vulkan_procedure.vkGetPhysicalDeviceFormatProperties2 import vkGetPhysicalDeviceFormatProperties2
from ._vulkan_procedure.vkGetPhysicalDeviceFragmentShadingRatesKHR import vkGetPhysicalDeviceFragmentShadingRatesKHR
from ._vulkan_procedure.vkGetPhysicalDeviceImageFormatProperties import vkGetPhysicalDeviceImageFormatProperties
from ._vulkan_procedure.vkGetPhysicalDeviceImageFormatProperties2 import vkGetPhysicalDeviceImageFormatProperties2
from ._vulkan_procedure.vkGetPhysicalDeviceMemoryProperties import vkGetPhysicalDeviceMemoryProperties
from ._vulkan_procedure.vkGetPhysicalDeviceMemoryProperties2 import vkGetPhysicalDeviceMemoryProperties2
from ._vulkan_procedure.vkGetPhysicalDeviceMultisamplePropertiesEXT import vkGetPhysicalDeviceMultisamplePropertiesEXT
from ._vulkan_procedure.vkGetPhysicalDeviceOpticalFlowImageFormatsNV import vkGetPhysicalDeviceOpticalFlowImageFormatsNV
from ._vulkan_procedure.vkGetPhysicalDevicePresentRectanglesKHR import vkGetPhysicalDevicePresentRectanglesKHR
from ._vulkan_procedure.vkGetPhysicalDeviceProperties import vkGetPhysicalDeviceProperties
from ._vulkan_procedure.vkGetPhysicalDeviceProperties2 import vkGetPhysicalDeviceProperties2
from ._vulkan_procedure.vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR import vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR
from ._vulkan_procedure.vkGetPhysicalDeviceQueueFamilyProperties import vkGetPhysicalDeviceQueueFamilyProperties
from ._vulkan_procedure.vkGetPhysicalDeviceQueueFamilyProperties2 import vkGetPhysicalDeviceQueueFamilyProperties2
from ._vulkan_procedure.vkGetPhysicalDeviceRefreshableObjectTypesKHR import vkGetPhysicalDeviceRefreshableObjectTypesKHR
from ._vulkan_procedure.vkGetPhysicalDeviceSciBufAttributesNV import vkGetPhysicalDeviceSciBufAttributesNV
from ._vulkan_procedure.vkGetPhysicalDeviceScreenPresentationSupportQNX import vkGetPhysicalDeviceScreenPresentationSupportQNX
from ._vulkan_procedure.vkGetPhysicalDeviceSparseImageFormatProperties import vkGetPhysicalDeviceSparseImageFormatProperties
from ._vulkan_procedure.vkGetPhysicalDeviceSparseImageFormatProperties2 import vkGetPhysicalDeviceSparseImageFormatProperties2
from ._vulkan_procedure.vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV import vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV
from ._vulkan_procedure.vkGetPhysicalDeviceSurfaceCapabilities2EXT import vkGetPhysicalDeviceSurfaceCapabilities2EXT
from ._vulkan_procedure.vkGetPhysicalDeviceSurfaceCapabilities2KHR import vkGetPhysicalDeviceSurfaceCapabilities2KHR
from ._vulkan_procedure.vkGetPhysicalDeviceSurfaceCapabilitiesKHR import vkGetPhysicalDeviceSurfaceCapabilitiesKHR
from ._vulkan_procedure.vkGetPhysicalDeviceSurfaceFormats2KHR import vkGetPhysicalDeviceSurfaceFormats2KHR
from ._vulkan_procedure.vkGetPhysicalDeviceSurfaceFormatsKHR import vkGetPhysicalDeviceSurfaceFormatsKHR
from ._vulkan_procedure.vkGetPhysicalDeviceSurfacePresentModes2EXT import vkGetPhysicalDeviceSurfacePresentModes2EXT
from ._vulkan_procedure.vkGetPhysicalDeviceSurfacePresentModesKHR import vkGetPhysicalDeviceSurfacePresentModesKHR
from ._vulkan_procedure.vkGetPhysicalDeviceSurfaceSupportKHR import vkGetPhysicalDeviceSurfaceSupportKHR
from ._vulkan_procedure.vkGetPhysicalDeviceToolProperties import vkGetPhysicalDeviceToolProperties
from ._vulkan_procedure.vkGetPhysicalDeviceVideoCapabilitiesKHR import vkGetPhysicalDeviceVideoCapabilitiesKHR
from ._vulkan_procedure.vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR import vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR
from ._vulkan_procedure.vkGetPhysicalDeviceVideoFormatPropertiesKHR import vkGetPhysicalDeviceVideoFormatPropertiesKHR
from ._vulkan_procedure.vkGetPhysicalDeviceWaylandPresentationSupportKHR import vkGetPhysicalDeviceWaylandPresentationSupportKHR
from ._vulkan_procedure.vkGetPhysicalDeviceWin32PresentationSupportKHR import vkGetPhysicalDeviceWin32PresentationSupportKHR
from ._vulkan_procedure.vkGetPhysicalDeviceXcbPresentationSupportKHR import vkGetPhysicalDeviceXcbPresentationSupportKHR
from ._vulkan_procedure.vkGetPhysicalDeviceXlibPresentationSupportKHR import vkGetPhysicalDeviceXlibPresentationSupportKHR
from ._vulkan_procedure.vkGetPipelineCacheData import vkGetPipelineCacheData
from ._vulkan_procedure.vkGetPipelineExecutableInternalRepresentationsKHR import vkGetPipelineExecutableInternalRepresentationsKHR
from ._vulkan_procedure.vkGetPipelineExecutablePropertiesKHR import vkGetPipelineExecutablePropertiesKHR
from ._vulkan_procedure.vkGetPipelineExecutableStatisticsKHR import vkGetPipelineExecutableStatisticsKHR
from ._vulkan_procedure.vkGetPipelineIndirectDeviceAddressNV import vkGetPipelineIndirectDeviceAddressNV
from ._vulkan_procedure.vkGetPipelineIndirectMemoryRequirementsNV import vkGetPipelineIndirectMemoryRequirementsNV
from ._vulkan_procedure.vkGetPipelinePropertiesEXT import vkGetPipelinePropertiesEXT
from ._vulkan_procedure.vkGetPrivateData import vkGetPrivateData
from ._vulkan_procedure.vkGetQueryPoolResults import vkGetQueryPoolResults
from ._vulkan_procedure.vkGetQueueCheckpointData2NV import vkGetQueueCheckpointData2NV
from ._vulkan_procedure.vkGetQueueCheckpointDataNV import vkGetQueueCheckpointDataNV
from ._vulkan_procedure.vkGetRandROutputDisplayEXT import vkGetRandROutputDisplayEXT
from ._vulkan_procedure.vkGetRayTracingCaptureReplayShaderGroupHandlesKHR import vkGetRayTracingCaptureReplayShaderGroupHandlesKHR
from ._vulkan_procedure.vkGetRayTracingShaderGroupHandlesKHR import vkGetRayTracingShaderGroupHandlesKHR
from ._vulkan_procedure.vkGetRayTracingShaderGroupStackSizeKHR import vkGetRayTracingShaderGroupStackSizeKHR
from ._vulkan_procedure.vkGetRefreshCycleDurationGOOGLE import vkGetRefreshCycleDurationGOOGLE
from ._vulkan_procedure.vkGetRenderAreaGranularity import vkGetRenderAreaGranularity
from ._vulkan_procedure.vkGetRenderingAreaGranularityKHR import vkGetRenderingAreaGranularityKHR
from ._vulkan_procedure.vkGetSamplerOpaqueCaptureDescriptorDataEXT import vkGetSamplerOpaqueCaptureDescriptorDataEXT
from ._vulkan_procedure.vkGetScreenBufferPropertiesQNX import vkGetScreenBufferPropertiesQNX
from ._vulkan_procedure.vkGetSemaphoreCounterValue import vkGetSemaphoreCounterValue
from ._vulkan_procedure.vkGetSemaphoreFdKHR import vkGetSemaphoreFdKHR
from ._vulkan_procedure.vkGetSemaphoreWin32HandleKHR import vkGetSemaphoreWin32HandleKHR
from ._vulkan_procedure.vkGetSemaphoreZirconHandleFUCHSIA import vkGetSemaphoreZirconHandleFUCHSIA
from ._vulkan_procedure.vkGetShaderBinaryDataEXT import vkGetShaderBinaryDataEXT
from ._vulkan_procedure.vkGetShaderInfoAMD import vkGetShaderInfoAMD
from ._vulkan_procedure.vkGetShaderModuleCreateInfoIdentifierEXT import vkGetShaderModuleCreateInfoIdentifierEXT
from ._vulkan_procedure.vkGetShaderModuleIdentifierEXT import vkGetShaderModuleIdentifierEXT
from ._vulkan_procedure.vkGetSwapchainCounterEXT import vkGetSwapchainCounterEXT
from ._vulkan_procedure.vkGetSwapchainGrallocUsage2ANDROID import vkGetSwapchainGrallocUsage2ANDROID
from ._vulkan_procedure.vkGetSwapchainGrallocUsageANDROID import vkGetSwapchainGrallocUsageANDROID
from ._vulkan_procedure.vkGetSwapchainImagesKHR import vkGetSwapchainImagesKHR
from ._vulkan_procedure.vkGetSwapchainStatusKHR import vkGetSwapchainStatusKHR
from ._vulkan_procedure.vkGetValidationCacheDataEXT import vkGetValidationCacheDataEXT
from ._vulkan_procedure.vkGetVideoSessionMemoryRequirementsKHR import vkGetVideoSessionMemoryRequirementsKHR
from ._vulkan_procedure.vkGetWinrtDisplayNV import vkGetWinrtDisplayNV
from ._vulkan_procedure.vkImportFenceFdKHR import vkImportFenceFdKHR
from ._vulkan_procedure.vkImportFenceWin32HandleKHR import vkImportFenceWin32HandleKHR
from ._vulkan_procedure.vkImportSemaphoreFdKHR import vkImportSemaphoreFdKHR
from ._vulkan_procedure.vkImportSemaphoreWin32HandleKHR import vkImportSemaphoreWin32HandleKHR
from ._vulkan_procedure.vkImportSemaphoreZirconHandleFUCHSIA import vkImportSemaphoreZirconHandleFUCHSIA
from ._vulkan_procedure.vkInitializePerformanceApiINTEL import vkInitializePerformanceApiINTEL
from ._vulkan_procedure.vkInvalidateMappedMemoryRanges import vkInvalidateMappedMemoryRanges
from ._vulkan_procedure.vkLatencySleepNV import vkLatencySleepNV
from ._vulkan_procedure.vkMapMemory import vkMapMemory
from ._vulkan_procedure.vkMapMemory2KHR import vkMapMemory2KHR
from ._vulkan_procedure.vkMergePipelineCaches import vkMergePipelineCaches
from ._vulkan_procedure.vkMergeValidationCachesEXT import vkMergeValidationCachesEXT
from ._vulkan_procedure.vkQueueBeginDebugUtilsLabelEXT import vkQueueBeginDebugUtilsLabelEXT
from ._vulkan_procedure.vkQueueBindSparse import vkQueueBindSparse
from ._vulkan_procedure.vkQueueEndDebugUtilsLabelEXT import vkQueueEndDebugUtilsLabelEXT
from ._vulkan_procedure.vkQueueInsertDebugUtilsLabelEXT import vkQueueInsertDebugUtilsLabelEXT
from ._vulkan_procedure.vkQueueNotifyOutOfBandNV import vkQueueNotifyOutOfBandNV
from ._vulkan_procedure.vkQueuePresentKHR import vkQueuePresentKHR
from ._vulkan_procedure.vkQueueSetPerformanceConfigurationINTEL import vkQueueSetPerformanceConfigurationINTEL
from ._vulkan_procedure.vkQueueSignalReleaseImageANDROID import vkQueueSignalReleaseImageANDROID
from ._vulkan_procedure.vkQueueSubmit import vkQueueSubmit
from ._vulkan_procedure.vkQueueSubmit2 import vkQueueSubmit2
from ._vulkan_procedure.vkQueueWaitIdle import vkQueueWaitIdle
from ._vulkan_procedure.vkRegisterDeviceEventEXT import vkRegisterDeviceEventEXT
from ._vulkan_procedure.vkRegisterDisplayEventEXT import vkRegisterDisplayEventEXT
from ._vulkan_procedure.vkReleaseDisplayEXT import vkReleaseDisplayEXT
from ._vulkan_procedure.vkReleaseFullScreenExclusiveModeEXT import vkReleaseFullScreenExclusiveModeEXT
from ._vulkan_procedure.vkReleasePerformanceConfigurationINTEL import vkReleasePerformanceConfigurationINTEL
from ._vulkan_procedure.vkReleaseProfilingLockKHR import vkReleaseProfilingLockKHR
from ._vulkan_procedure.vkReleaseSwapchainImagesEXT import vkReleaseSwapchainImagesEXT
from ._vulkan_procedure.vkResetCommandBuffer import vkResetCommandBuffer
from ._vulkan_procedure.vkResetCommandPool import vkResetCommandPool
from ._vulkan_procedure.vkResetDescriptorPool import vkResetDescriptorPool
from ._vulkan_procedure.vkResetEvent import vkResetEvent
from ._vulkan_procedure.vkResetFences import vkResetFences
from ._vulkan_procedure.vkResetQueryPool import vkResetQueryPool
from ._vulkan_procedure.vkSetBufferCollectionBufferConstraintsFUCHSIA import vkSetBufferCollectionBufferConstraintsFUCHSIA
from ._vulkan_procedure.vkSetBufferCollectionImageConstraintsFUCHSIA import vkSetBufferCollectionImageConstraintsFUCHSIA
from ._vulkan_procedure.vkSetDebugUtilsObjectNameEXT import vkSetDebugUtilsObjectNameEXT
from ._vulkan_procedure.vkSetDebugUtilsObjectTagEXT import vkSetDebugUtilsObjectTagEXT
from ._vulkan_procedure.vkSetDeviceMemoryPriorityEXT import vkSetDeviceMemoryPriorityEXT
from ._vulkan_procedure.vkSetEvent import vkSetEvent
from ._vulkan_procedure.vkSetHdrMetadataEXT import vkSetHdrMetadataEXT
from ._vulkan_procedure.vkSetLatencyMarkerNV import vkSetLatencyMarkerNV
from ._vulkan_procedure.vkSetLatencySleepModeNV import vkSetLatencySleepModeNV
from ._vulkan_procedure.vkSetLocalDimmingAMD import vkSetLocalDimmingAMD
from ._vulkan_procedure.vkSetPrivateData import vkSetPrivateData
from ._vulkan_procedure.vkSignalSemaphore import vkSignalSemaphore
from ._vulkan_procedure.vkSubmitDebugUtilsMessageEXT import vkSubmitDebugUtilsMessageEXT
from ._vulkan_procedure.vkTransitionImageLayoutEXT import vkTransitionImageLayoutEXT
from ._vulkan_procedure.vkTrimCommandPool import vkTrimCommandPool
from ._vulkan_procedure.vkUninitializePerformanceApiINTEL import vkUninitializePerformanceApiINTEL
from ._vulkan_procedure.vkUnmapMemory import vkUnmapMemory
from ._vulkan_procedure.vkUnmapMemory2KHR import vkUnmapMemory2KHR
from ._vulkan_procedure.vkUpdateDescriptorSetWithTemplate import vkUpdateDescriptorSetWithTemplate
from ._vulkan_procedure.vkUpdateDescriptorSets import vkUpdateDescriptorSets
from ._vulkan_procedure.vkUpdateVideoSessionParametersKHR import vkUpdateVideoSessionParametersKHR
from ._vulkan_procedure.vkWaitForFences import vkWaitForFences
from ._vulkan_procedure.vkWaitForPresentKHR import vkWaitForPresentKHR
from ._vulkan_procedure.vkWaitSemaphores import vkWaitSemaphores
from ._vulkan_procedure.vkWriteAccelerationStructuresPropertiesKHR import vkWriteAccelerationStructuresPropertiesKHR
from ._vulkan_procedure.vkWriteMicromapsPropertiesEXT import vkWriteMicromapsPropertiesEXT

vkBindBufferMemory2KHR = vkBindBufferMemory2
vkBindImageMemory2KHR = vkBindImageMemory2
vkCmdBeginRenderPass2KHR = vkCmdBeginRenderPass2
vkCmdBeginRenderingKHR = vkCmdBeginRendering
vkCmdBindVertexBuffers2EXT = vkCmdBindVertexBuffers2
vkCmdBlitImage2KHR = vkCmdBlitImage2
vkCmdCopyBuffer2KHR = vkCmdCopyBuffer2
vkCmdCopyBufferToImage2KHR = vkCmdCopyBufferToImage2
vkCmdCopyImage2KHR = vkCmdCopyImage2
vkCmdCopyImageToBuffer2KHR = vkCmdCopyImageToBuffer2
vkCmdDispatchBaseKHR = vkCmdDispatchBase
vkCmdDrawIndexedIndirectCountAMD = vkCmdDrawIndexedIndirectCount
vkCmdDrawIndexedIndirectCountKHR = vkCmdDrawIndexedIndirectCount
vkCmdDrawIndirectCountAMD = vkCmdDrawIndirectCount
vkCmdDrawIndirectCountKHR = vkCmdDrawIndirectCount
vkCmdEndRenderPass2KHR = vkCmdEndRenderPass2
vkCmdEndRenderingKHR = vkCmdEndRendering
vkCmdNextSubpass2KHR = vkCmdNextSubpass2
vkCmdPipelineBarrier2KHR = vkCmdPipelineBarrier2
vkCmdResetEvent2KHR = vkCmdResetEvent2
vkCmdResolveImage2KHR = vkCmdResolveImage2
vkCmdSetCullModeEXT = vkCmdSetCullMode
vkCmdSetDepthBiasEnableEXT = vkCmdSetDepthBiasEnable
vkCmdSetDepthBoundsTestEnableEXT = vkCmdSetDepthBoundsTestEnable
vkCmdSetDepthCompareOpEXT = vkCmdSetDepthCompareOp
vkCmdSetDepthTestEnableEXT = vkCmdSetDepthTestEnable
vkCmdSetDepthWriteEnableEXT = vkCmdSetDepthWriteEnable
vkCmdSetDeviceMaskKHR = vkCmdSetDeviceMask
vkCmdSetEvent2KHR = vkCmdSetEvent2
vkCmdSetFrontFaceEXT = vkCmdSetFrontFace
vkCmdSetLineStippleEXT = vkCmdSetLineStippleKHR
vkCmdSetPrimitiveRestartEnableEXT = vkCmdSetPrimitiveRestartEnable
vkCmdSetPrimitiveTopologyEXT = vkCmdSetPrimitiveTopology
vkCmdSetRasterizerDiscardEnableEXT = vkCmdSetRasterizerDiscardEnable
vkCmdSetScissorWithCountEXT = vkCmdSetScissorWithCount
vkCmdSetStencilOpEXT = vkCmdSetStencilOp
vkCmdSetStencilTestEnableEXT = vkCmdSetStencilTestEnable
vkCmdSetViewportWithCountEXT = vkCmdSetViewportWithCount
vkCmdWaitEvents2KHR = vkCmdWaitEvents2
vkCmdWriteTimestamp2KHR = vkCmdWriteTimestamp2
vkCreateDescriptorUpdateTemplateKHR = vkCreateDescriptorUpdateTemplate
vkCreatePrivateDataSlotEXT = vkCreatePrivateDataSlot
vkCreateRenderPass2KHR = vkCreateRenderPass2
vkCreateSamplerYcbcrConversionKHR = vkCreateSamplerYcbcrConversion
vkDestroyDescriptorUpdateTemplateKHR = vkDestroyDescriptorUpdateTemplate
vkDestroyPrivateDataSlotEXT = vkDestroyPrivateDataSlot
vkDestroySamplerYcbcrConversionKHR = vkDestroySamplerYcbcrConversion
vkEnumeratePhysicalDeviceGroupsKHR = vkEnumeratePhysicalDeviceGroups
vkGetBufferDeviceAddressEXT = vkGetBufferDeviceAddress
vkGetBufferDeviceAddressKHR = vkGetBufferDeviceAddress
vkGetBufferMemoryRequirements2KHR = vkGetBufferMemoryRequirements2
vkGetBufferOpaqueCaptureAddressKHR = vkGetBufferOpaqueCaptureAddress
vkGetCalibratedTimestampsEXT = vkGetCalibratedTimestampsKHR
vkGetDescriptorSetLayoutSupportKHR = vkGetDescriptorSetLayoutSupport
vkGetDeviceBufferMemoryRequirementsKHR = vkGetDeviceBufferMemoryRequirements
vkGetDeviceGroupPeerMemoryFeaturesKHR = vkGetDeviceGroupPeerMemoryFeatures
vkGetDeviceImageMemoryRequirementsKHR = vkGetDeviceImageMemoryRequirements
vkGetDeviceImageSparseMemoryRequirementsKHR = vkGetDeviceImageSparseMemoryRequirements
vkGetDeviceMemoryOpaqueCaptureAddressKHR = vkGetDeviceMemoryOpaqueCaptureAddress
vkGetImageMemoryRequirements2KHR = vkGetImageMemoryRequirements2
vkGetImageSparseMemoryRequirements2KHR = vkGetImageSparseMemoryRequirements2
vkGetImageSubresourceLayout2EXT = vkGetImageSubresourceLayout2KHR
vkGetPhysicalDeviceCalibrateableTimeDomainsEXT = vkGetPhysicalDeviceCalibrateableTimeDomainsKHR
vkGetPhysicalDeviceExternalBufferPropertiesKHR = vkGetPhysicalDeviceExternalBufferProperties
vkGetPhysicalDeviceExternalFencePropertiesKHR = vkGetPhysicalDeviceExternalFenceProperties
vkGetPhysicalDeviceExternalSemaphorePropertiesKHR = vkGetPhysicalDeviceExternalSemaphoreProperties
vkGetPhysicalDeviceFeatures2KHR = vkGetPhysicalDeviceFeatures2
vkGetPhysicalDeviceFormatProperties2KHR = vkGetPhysicalDeviceFormatProperties2
vkGetPhysicalDeviceImageFormatProperties2KHR = vkGetPhysicalDeviceImageFormatProperties2
vkGetPhysicalDeviceMemoryProperties2KHR = vkGetPhysicalDeviceMemoryProperties2
vkGetPhysicalDeviceProperties2KHR = vkGetPhysicalDeviceProperties2
vkGetPhysicalDeviceQueueFamilyProperties2KHR = vkGetPhysicalDeviceQueueFamilyProperties2
vkGetPhysicalDeviceSparseImageFormatProperties2KHR = vkGetPhysicalDeviceSparseImageFormatProperties2
vkGetPhysicalDeviceToolPropertiesEXT = vkGetPhysicalDeviceToolProperties
vkGetPrivateDataEXT = vkGetPrivateData
vkGetRayTracingShaderGroupHandlesNV = vkGetRayTracingShaderGroupHandlesKHR
vkGetSemaphoreCounterValueKHR = vkGetSemaphoreCounterValue
vkQueueSubmit2KHR = vkQueueSubmit2
vkResetQueryPoolEXT = vkResetQueryPool
vkSetPrivateDataEXT = vkSetPrivateData
vkSignalSemaphoreKHR = vkSignalSemaphore
vkTrimCommandPoolKHR = vkTrimCommandPool
vkUpdateDescriptorSetWithTemplateKHR = vkUpdateDescriptorSetWithTemplate
vkWaitSemaphoresKHR = vkWaitSemaphores
