from ._vulkan_enum.StdVideoAV1ChromaSamplePosition import StdVideoAV1ChromaSamplePosition
from ._vulkan_enum.StdVideoAV1ColorPrimaries import StdVideoAV1ColorPrimaries
from ._vulkan_enum.StdVideoAV1FrameRestorationType import StdVideoAV1FrameRestorationType
from ._vulkan_enum.StdVideoAV1FrameType import StdVideoAV1FrameType
from ._vulkan_enum.StdVideoAV1InterpolationFilter import StdVideoAV1InterpolationFilter
from ._vulkan_enum.StdVideoAV1Level import StdVideoAV1Level
from ._vulkan_enum.StdVideoAV1MatrixCoefficients import StdVideoAV1MatrixCoefficients
from ._vulkan_enum.StdVideoAV1Profile import StdVideoAV1Profile
from ._vulkan_enum.StdVideoAV1ReferenceName import StdVideoAV1ReferenceName
from ._vulkan_enum.StdVideoAV1TransferCharacteristics import StdVideoAV1TransferCharacteristics
from ._vulkan_enum.StdVideoAV1TxMode import StdVideoAV1TxMode
from ._vulkan_enum.StdVideoDecodeH264FieldOrderCount import StdVideoDecodeH264FieldOrderCount
from ._vulkan_enum.StdVideoH264AspectRatioIdc import StdVideoH264AspectRatioIdc
from ._vulkan_enum.StdVideoH264CabacInitIdc import StdVideoH264CabacInitIdc
from ._vulkan_enum.StdVideoH264ChromaFormatIdc import StdVideoH264ChromaFormatIdc
from ._vulkan_enum.StdVideoH264DisableDeblockingFilterIdc import StdVideoH264DisableDeblockingFilterIdc
from ._vulkan_enum.StdVideoH264LevelIdc import StdVideoH264LevelIdc
from ._vulkan_enum.StdVideoH264MemMgmtControlOp import StdVideoH264MemMgmtControlOp
from ._vulkan_enum.StdVideoH264ModificationOfPicNumsIdc import StdVideoH264ModificationOfPicNumsIdc
from ._vulkan_enum.StdVideoH264NonVclNaluType import StdVideoH264NonVclNaluType
from ._vulkan_enum.StdVideoH264PictureType import StdVideoH264PictureType
from ._vulkan_enum.StdVideoH264PocType import StdVideoH264PocType
from ._vulkan_enum.StdVideoH264ProfileIdc import StdVideoH264ProfileIdc
from ._vulkan_enum.StdVideoH264SliceType import StdVideoH264SliceType
from ._vulkan_enum.StdVideoH264WeightedBipredIdc import StdVideoH264WeightedBipredIdc
from ._vulkan_enum.StdVideoH265AspectRatioIdc import StdVideoH265AspectRatioIdc
from ._vulkan_enum.StdVideoH265ChromaFormatIdc import StdVideoH265ChromaFormatIdc
from ._vulkan_enum.StdVideoH265LevelIdc import StdVideoH265LevelIdc
from ._vulkan_enum.StdVideoH265PictureType import StdVideoH265PictureType
from ._vulkan_enum.StdVideoH265ProfileIdc import StdVideoH265ProfileIdc
from ._vulkan_enum.StdVideoH265SliceType import StdVideoH265SliceType
from ._vulkan_enum.VkAccelerationStructureBuildTypeKHR import VkAccelerationStructureBuildTypeKHR
from ._vulkan_enum.VkAccelerationStructureCompatibilityKHR import VkAccelerationStructureCompatibilityKHR
from ._vulkan_enum.VkAccelerationStructureCreateFlagsKHR import VkAccelerationStructureCreateFlagsKHR
from ._vulkan_enum.VkAccelerationStructureMemoryRequirementsTypeNV import VkAccelerationStructureMemoryRequirementsTypeNV
from ._vulkan_enum.VkAccelerationStructureMotionInfoFlagsNV import VkAccelerationStructureMotionInfoFlagsNV
from ._vulkan_enum.VkAccelerationStructureMotionInstanceFlagsNV import VkAccelerationStructureMotionInstanceFlagsNV
from ._vulkan_enum.VkAccelerationStructureMotionInstanceTypeNV import VkAccelerationStructureMotionInstanceTypeNV
from ._vulkan_enum.VkAccelerationStructureTypeKHR import VkAccelerationStructureTypeKHR
from ._vulkan_enum.VkAccessFlags import VkAccessFlags
from ._vulkan_enum.VkAccessFlags2 import VkAccessFlags2
from ._vulkan_enum.VkAcquireProfilingLockFlagsKHR import VkAcquireProfilingLockFlagsKHR
from ._vulkan_enum.VkAndroidSurfaceCreateFlagsKHR import VkAndroidSurfaceCreateFlagsKHR
from ._vulkan_enum.VkAttachmentDescriptionFlags import VkAttachmentDescriptionFlags
from ._vulkan_enum.VkAttachmentLoadOp import VkAttachmentLoadOp
from ._vulkan_enum.VkAttachmentStoreOp import VkAttachmentStoreOp
from ._vulkan_enum.VkBlendFactor import VkBlendFactor
from ._vulkan_enum.VkBlendOp import VkBlendOp
from ._vulkan_enum.VkBlendOverlapEXT import VkBlendOverlapEXT
from ._vulkan_enum.VkBlockMatchWindowCompareModeQCOM import VkBlockMatchWindowCompareModeQCOM
from ._vulkan_enum.VkBorderColor import VkBorderColor
from ._vulkan_enum.VkBufferCreateFlags import VkBufferCreateFlags
from ._vulkan_enum.VkBufferUsageFlags import VkBufferUsageFlags
from ._vulkan_enum.VkBufferUsageFlags2KHR import VkBufferUsageFlags2KHR
from ._vulkan_enum.VkBufferViewCreateFlags import VkBufferViewCreateFlags
from ._vulkan_enum.VkBuildAccelerationStructureFlagsKHR import VkBuildAccelerationStructureFlagsKHR
from ._vulkan_enum.VkBuildAccelerationStructureModeKHR import VkBuildAccelerationStructureModeKHR
from ._vulkan_enum.VkBuildMicromapFlagsEXT import VkBuildMicromapFlagsEXT
from ._vulkan_enum.VkBuildMicromapModeEXT import VkBuildMicromapModeEXT
from ._vulkan_enum.VkChromaLocation import VkChromaLocation
from ._vulkan_enum.VkCoarseSampleOrderTypeNV import VkCoarseSampleOrderTypeNV
from ._vulkan_enum.VkColorComponentFlags import VkColorComponentFlags
from ._vulkan_enum.VkColorSpaceKHR import VkColorSpaceKHR
from ._vulkan_enum.VkCommandBufferLevel import VkCommandBufferLevel
from ._vulkan_enum.VkCommandBufferResetFlags import VkCommandBufferResetFlags
from ._vulkan_enum.VkCommandBufferUsageFlags import VkCommandBufferUsageFlags
from ._vulkan_enum.VkCommandPoolCreateFlags import VkCommandPoolCreateFlags
from ._vulkan_enum.VkCommandPoolResetFlags import VkCommandPoolResetFlags
from ._vulkan_enum.VkCommandPoolTrimFlags import VkCommandPoolTrimFlags
from ._vulkan_enum.VkCompareOp import VkCompareOp
from ._vulkan_enum.VkComponentSwizzle import VkComponentSwizzle
from ._vulkan_enum.VkComponentTypeKHR import VkComponentTypeKHR
from ._vulkan_enum.VkCompositeAlphaFlagsKHR import VkCompositeAlphaFlagsKHR
from ._vulkan_enum.VkConditionalRenderingFlagsEXT import VkConditionalRenderingFlagsEXT
from ._vulkan_enum.VkConservativeRasterizationModeEXT import VkConservativeRasterizationModeEXT
from ._vulkan_enum.VkCopyAccelerationStructureModeKHR import VkCopyAccelerationStructureModeKHR
from ._vulkan_enum.VkCopyMicromapModeEXT import VkCopyMicromapModeEXT
from ._vulkan_enum.VkCoverageModulationModeNV import VkCoverageModulationModeNV
from ._vulkan_enum.VkCoverageReductionModeNV import VkCoverageReductionModeNV
from ._vulkan_enum.VkCubicFilterWeightsQCOM import VkCubicFilterWeightsQCOM
from ._vulkan_enum.VkCullModeFlags import VkCullModeFlags
from ._vulkan_enum.VkDebugReportFlagsEXT import VkDebugReportFlagsEXT
from ._vulkan_enum.VkDebugReportObjectTypeEXT import VkDebugReportObjectTypeEXT
from ._vulkan_enum.VkDebugUtilsMessageSeverityFlagsEXT import VkDebugUtilsMessageSeverityFlagsEXT
from ._vulkan_enum.VkDebugUtilsMessageTypeFlagsEXT import VkDebugUtilsMessageTypeFlagsEXT
from ._vulkan_enum.VkDebugUtilsMessengerCallbackDataFlagsEXT import VkDebugUtilsMessengerCallbackDataFlagsEXT
from ._vulkan_enum.VkDebugUtilsMessengerCreateFlagsEXT import VkDebugUtilsMessengerCreateFlagsEXT
from ._vulkan_enum.VkDependencyFlags import VkDependencyFlags
from ._vulkan_enum.VkDepthBiasRepresentationEXT import VkDepthBiasRepresentationEXT
from ._vulkan_enum.VkDescriptorBindingFlags import VkDescriptorBindingFlags
from ._vulkan_enum.VkDescriptorPoolCreateFlags import VkDescriptorPoolCreateFlags
from ._vulkan_enum.VkDescriptorPoolResetFlags import VkDescriptorPoolResetFlags
from ._vulkan_enum.VkDescriptorSetLayoutCreateFlags import VkDescriptorSetLayoutCreateFlags
from ._vulkan_enum.VkDescriptorType import VkDescriptorType
from ._vulkan_enum.VkDescriptorUpdateTemplateCreateFlags import VkDescriptorUpdateTemplateCreateFlags
from ._vulkan_enum.VkDescriptorUpdateTemplateType import VkDescriptorUpdateTemplateType
from ._vulkan_enum.VkDeviceAddressBindingFlagsEXT import VkDeviceAddressBindingFlagsEXT
from ._vulkan_enum.VkDeviceAddressBindingTypeEXT import VkDeviceAddressBindingTypeEXT
from ._vulkan_enum.VkDeviceCreateFlags import VkDeviceCreateFlags
from ._vulkan_enum.VkDeviceDiagnosticsConfigFlagsNV import VkDeviceDiagnosticsConfigFlagsNV
from ._vulkan_enum.VkDeviceEventTypeEXT import VkDeviceEventTypeEXT
from ._vulkan_enum.VkDeviceFaultAddressTypeEXT import VkDeviceFaultAddressTypeEXT
from ._vulkan_enum.VkDeviceFaultVendorBinaryHeaderVersionEXT import VkDeviceFaultVendorBinaryHeaderVersionEXT
from ._vulkan_enum.VkDeviceGroupPresentModeFlagsKHR import VkDeviceGroupPresentModeFlagsKHR
from ._vulkan_enum.VkDeviceMemoryReportEventTypeEXT import VkDeviceMemoryReportEventTypeEXT
from ._vulkan_enum.VkDeviceMemoryReportFlagsEXT import VkDeviceMemoryReportFlagsEXT
from ._vulkan_enum.VkDeviceQueueCreateFlags import VkDeviceQueueCreateFlags
from ._vulkan_enum.VkDirectDriverLoadingFlagsLUNARG import VkDirectDriverLoadingFlagsLUNARG
from ._vulkan_enum.VkDirectDriverLoadingModeLUNARG import VkDirectDriverLoadingModeLUNARG
from ._vulkan_enum.VkDirectFBSurfaceCreateFlagsEXT import VkDirectFBSurfaceCreateFlagsEXT
from ._vulkan_enum.VkDiscardRectangleModeEXT import VkDiscardRectangleModeEXT
from ._vulkan_enum.VkDisplacementMicromapFormatNV import VkDisplacementMicromapFormatNV
from ._vulkan_enum.VkDisplayEventTypeEXT import VkDisplayEventTypeEXT
from ._vulkan_enum.VkDisplayModeCreateFlagsKHR import VkDisplayModeCreateFlagsKHR
from ._vulkan_enum.VkDisplayPlaneAlphaFlagsKHR import VkDisplayPlaneAlphaFlagsKHR
from ._vulkan_enum.VkDisplayPowerStateEXT import VkDisplayPowerStateEXT
from ._vulkan_enum.VkDisplaySurfaceCreateFlagsKHR import VkDisplaySurfaceCreateFlagsKHR
from ._vulkan_enum.VkDriverId import VkDriverId
from ._vulkan_enum.VkDynamicState import VkDynamicState
from ._vulkan_enum.VkEventCreateFlags import VkEventCreateFlags
from ._vulkan_enum.VkExportMetalObjectTypeFlagsEXT import VkExportMetalObjectTypeFlagsEXT
from ._vulkan_enum.VkExternalFenceFeatureFlags import VkExternalFenceFeatureFlags
from ._vulkan_enum.VkExternalFenceHandleTypeFlags import VkExternalFenceHandleTypeFlags
from ._vulkan_enum.VkExternalMemoryFeatureFlags import VkExternalMemoryFeatureFlags
from ._vulkan_enum.VkExternalMemoryFeatureFlagsNV import VkExternalMemoryFeatureFlagsNV
from ._vulkan_enum.VkExternalMemoryHandleTypeFlags import VkExternalMemoryHandleTypeFlags
from ._vulkan_enum.VkExternalMemoryHandleTypeFlagsNV import VkExternalMemoryHandleTypeFlagsNV
from ._vulkan_enum.VkExternalSemaphoreFeatureFlags import VkExternalSemaphoreFeatureFlags
from ._vulkan_enum.VkExternalSemaphoreHandleTypeFlags import VkExternalSemaphoreHandleTypeFlags
from ._vulkan_enum.VkFaultLevel import VkFaultLevel
from ._vulkan_enum.VkFaultQueryBehavior import VkFaultQueryBehavior
from ._vulkan_enum.VkFaultType import VkFaultType
from ._vulkan_enum.VkFenceCreateFlags import VkFenceCreateFlags
from ._vulkan_enum.VkFenceImportFlags import VkFenceImportFlags
from ._vulkan_enum.VkFilter import VkFilter
from ._vulkan_enum.VkFormat import VkFormat
from ._vulkan_enum.VkFormatFeatureFlags import VkFormatFeatureFlags
from ._vulkan_enum.VkFormatFeatureFlags2 import VkFormatFeatureFlags2
from ._vulkan_enum.VkFragmentShadingRateCombinerOpKHR import VkFragmentShadingRateCombinerOpKHR
from ._vulkan_enum.VkFragmentShadingRateNV import VkFragmentShadingRateNV
from ._vulkan_enum.VkFragmentShadingRateTypeNV import VkFragmentShadingRateTypeNV
from ._vulkan_enum.VkFrameBoundaryFlagsEXT import VkFrameBoundaryFlagsEXT
from ._vulkan_enum.VkFramebufferCreateFlags import VkFramebufferCreateFlags
from ._vulkan_enum.VkFrontFace import VkFrontFace
from ._vulkan_enum.VkFullScreenExclusiveEXT import VkFullScreenExclusiveEXT
from ._vulkan_enum.VkGeometryFlagsKHR import VkGeometryFlagsKHR
from ._vulkan_enum.VkGeometryInstanceFlagsKHR import VkGeometryInstanceFlagsKHR
from ._vulkan_enum.VkGeometryTypeKHR import VkGeometryTypeKHR
from ._vulkan_enum.VkGraphicsPipelineLibraryFlagsEXT import VkGraphicsPipelineLibraryFlagsEXT
from ._vulkan_enum.VkHeadlessSurfaceCreateFlagsEXT import VkHeadlessSurfaceCreateFlagsEXT
from ._vulkan_enum.VkHostImageCopyFlagsEXT import VkHostImageCopyFlagsEXT
from ._vulkan_enum.VkIOSSurfaceCreateFlagsMVK import VkIOSSurfaceCreateFlagsMVK
from ._vulkan_enum.VkImageAspectFlags import VkImageAspectFlags
from ._vulkan_enum.VkImageCompressionFixedRateFlagsEXT import VkImageCompressionFixedRateFlagsEXT
from ._vulkan_enum.VkImageCompressionFlagsEXT import VkImageCompressionFlagsEXT
from ._vulkan_enum.VkImageConstraintsInfoFlagsFUCHSIA import VkImageConstraintsInfoFlagsFUCHSIA
from ._vulkan_enum.VkImageCreateFlags import VkImageCreateFlags
from ._vulkan_enum.VkImageFormatConstraintsFlagBitsFUCHSIA import VkImageFormatConstraintsFlagBitsFUCHSIA
from ._vulkan_enum.VkImageFormatConstraintsFlagsFUCHSIA import VkImageFormatConstraintsFlagsFUCHSIA
from ._vulkan_enum.VkImageLayout import VkImageLayout
from ._vulkan_enum.VkImagePipeSurfaceCreateFlagsFUCHSIA import VkImagePipeSurfaceCreateFlagsFUCHSIA
from ._vulkan_enum.VkImageTiling import VkImageTiling
from ._vulkan_enum.VkImageType import VkImageType
from ._vulkan_enum.VkImageUsageFlags import VkImageUsageFlags
from ._vulkan_enum.VkImageViewCreateFlags import VkImageViewCreateFlags
from ._vulkan_enum.VkImageViewType import VkImageViewType
from ._vulkan_enum.VkIndexType import VkIndexType
from ._vulkan_enum.VkIndirectCommandsLayoutUsageFlagsNV import VkIndirectCommandsLayoutUsageFlagsNV
from ._vulkan_enum.VkIndirectCommandsTokenTypeNV import VkIndirectCommandsTokenTypeNV
from ._vulkan_enum.VkIndirectStateFlagsNV import VkIndirectStateFlagsNV
from ._vulkan_enum.VkInstanceCreateFlags import VkInstanceCreateFlags
from ._vulkan_enum.VkInternalAllocationType import VkInternalAllocationType
from ._vulkan_enum.VkLatencyMarkerNV import VkLatencyMarkerNV
from ._vulkan_enum.VkLayerSettingTypeEXT import VkLayerSettingTypeEXT
from ._vulkan_enum.VkLayeredDriverUnderlyingApiMSFT import VkLayeredDriverUnderlyingApiMSFT
from ._vulkan_enum.VkLineRasterizationModeKHR import VkLineRasterizationModeKHR
from ._vulkan_enum.VkLogicOp import VkLogicOp
from ._vulkan_enum.VkMacOSSurfaceCreateFlagsMVK import VkMacOSSurfaceCreateFlagsMVK
from ._vulkan_enum.VkMemoryAllocateFlags import VkMemoryAllocateFlags
from ._vulkan_enum.VkMemoryDecompressionMethodFlagsNV import VkMemoryDecompressionMethodFlagsNV
from ._vulkan_enum.VkMemoryHeapFlags import VkMemoryHeapFlags
from ._vulkan_enum.VkMemoryMapFlags import VkMemoryMapFlags
from ._vulkan_enum.VkMemoryOverallocationBehaviorAMD import VkMemoryOverallocationBehaviorAMD
from ._vulkan_enum.VkMemoryPropertyFlags import VkMemoryPropertyFlags
from ._vulkan_enum.VkMemoryUnmapFlagsKHR import VkMemoryUnmapFlagsKHR
from ._vulkan_enum.VkMetalSurfaceCreateFlagsEXT import VkMetalSurfaceCreateFlagsEXT
from ._vulkan_enum.VkMicromapCreateFlagsEXT import VkMicromapCreateFlagsEXT
from ._vulkan_enum.VkMicromapTypeEXT import VkMicromapTypeEXT
from ._vulkan_enum.VkObjectType import VkObjectType
from ._vulkan_enum.VkOpacityMicromapFormatEXT import VkOpacityMicromapFormatEXT
from ._vulkan_enum.VkOpacityMicromapSpecialIndexEXT import VkOpacityMicromapSpecialIndexEXT
from ._vulkan_enum.VkOpticalFlowExecuteFlagsNV import VkOpticalFlowExecuteFlagsNV
from ._vulkan_enum.VkOpticalFlowGridSizeFlagsNV import VkOpticalFlowGridSizeFlagsNV
from ._vulkan_enum.VkOpticalFlowPerformanceLevelNV import VkOpticalFlowPerformanceLevelNV
from ._vulkan_enum.VkOpticalFlowSessionBindingPointNV import VkOpticalFlowSessionBindingPointNV
from ._vulkan_enum.VkOpticalFlowSessionCreateFlagsNV import VkOpticalFlowSessionCreateFlagsNV
from ._vulkan_enum.VkOpticalFlowUsageFlagsNV import VkOpticalFlowUsageFlagsNV
from ._vulkan_enum.VkOutOfBandQueueTypeNV import VkOutOfBandQueueTypeNV
from ._vulkan_enum.VkPeerMemoryFeatureFlags import VkPeerMemoryFeatureFlags
from ._vulkan_enum.VkPerformanceConfigurationTypeINTEL import VkPerformanceConfigurationTypeINTEL
from ._vulkan_enum.VkPerformanceCounterDescriptionFlagsKHR import VkPerformanceCounterDescriptionFlagsKHR
from ._vulkan_enum.VkPerformanceCounterScopeKHR import VkPerformanceCounterScopeKHR
from ._vulkan_enum.VkPerformanceCounterStorageKHR import VkPerformanceCounterStorageKHR
from ._vulkan_enum.VkPerformanceCounterUnitKHR import VkPerformanceCounterUnitKHR
from ._vulkan_enum.VkPerformanceOverrideTypeINTEL import VkPerformanceOverrideTypeINTEL
from ._vulkan_enum.VkPerformanceParameterTypeINTEL import VkPerformanceParameterTypeINTEL
from ._vulkan_enum.VkPerformanceValueTypeINTEL import VkPerformanceValueTypeINTEL
from ._vulkan_enum.VkPhysicalDeviceLayeredApiKHR import VkPhysicalDeviceLayeredApiKHR
from ._vulkan_enum.VkPhysicalDeviceSchedulingControlsFlagsARM import VkPhysicalDeviceSchedulingControlsFlagsARM
from ._vulkan_enum.VkPhysicalDeviceType import VkPhysicalDeviceType
from ._vulkan_enum.VkPipelineBindPoint import VkPipelineBindPoint
from ._vulkan_enum.VkPipelineCacheCreateFlags import VkPipelineCacheCreateFlags
from ._vulkan_enum.VkPipelineCacheHeaderVersion import VkPipelineCacheHeaderVersion
from ._vulkan_enum.VkPipelineCacheValidationVersion import VkPipelineCacheValidationVersion
from ._vulkan_enum.VkPipelineColorBlendStateCreateFlags import VkPipelineColorBlendStateCreateFlags
from ._vulkan_enum.VkPipelineCompilerControlFlagsAMD import VkPipelineCompilerControlFlagsAMD
from ._vulkan_enum.VkPipelineCoverageModulationStateCreateFlagsNV import VkPipelineCoverageModulationStateCreateFlagsNV
from ._vulkan_enum.VkPipelineCoverageReductionStateCreateFlagsNV import VkPipelineCoverageReductionStateCreateFlagsNV
from ._vulkan_enum.VkPipelineCoverageToColorStateCreateFlagsNV import VkPipelineCoverageToColorStateCreateFlagsNV
from ._vulkan_enum.VkPipelineCreateFlags import VkPipelineCreateFlags
from ._vulkan_enum.VkPipelineCreateFlags2KHR import VkPipelineCreateFlags2KHR
from ._vulkan_enum.VkPipelineCreationFeedbackFlags import VkPipelineCreationFeedbackFlags
from ._vulkan_enum.VkPipelineDepthStencilStateCreateFlags import VkPipelineDepthStencilStateCreateFlags
from ._vulkan_enum.VkPipelineDiscardRectangleStateCreateFlagsEXT import VkPipelineDiscardRectangleStateCreateFlagsEXT
from ._vulkan_enum.VkPipelineDynamicStateCreateFlags import VkPipelineDynamicStateCreateFlags
from ._vulkan_enum.VkPipelineExecutableStatisticFormatKHR import VkPipelineExecutableStatisticFormatKHR
from ._vulkan_enum.VkPipelineInputAssemblyStateCreateFlags import VkPipelineInputAssemblyStateCreateFlags
from ._vulkan_enum.VkPipelineLayoutCreateFlags import VkPipelineLayoutCreateFlags
from ._vulkan_enum.VkPipelineMatchControl import VkPipelineMatchControl
from ._vulkan_enum.VkPipelineMultisampleStateCreateFlags import VkPipelineMultisampleStateCreateFlags
from ._vulkan_enum.VkPipelineRasterizationConservativeStateCreateFlagsEXT import VkPipelineRasterizationConservativeStateCreateFlagsEXT
from ._vulkan_enum.VkPipelineRasterizationDepthClipStateCreateFlagsEXT import VkPipelineRasterizationDepthClipStateCreateFlagsEXT
from ._vulkan_enum.VkPipelineRasterizationStateCreateFlags import VkPipelineRasterizationStateCreateFlags
from ._vulkan_enum.VkPipelineRasterizationStateStreamCreateFlagsEXT import VkPipelineRasterizationStateStreamCreateFlagsEXT
from ._vulkan_enum.VkPipelineRobustnessBufferBehaviorEXT import VkPipelineRobustnessBufferBehaviorEXT
from ._vulkan_enum.VkPipelineRobustnessImageBehaviorEXT import VkPipelineRobustnessImageBehaviorEXT
from ._vulkan_enum.VkPipelineShaderStageCreateFlags import VkPipelineShaderStageCreateFlags
from ._vulkan_enum.VkPipelineStageFlags import VkPipelineStageFlags
from ._vulkan_enum.VkPipelineStageFlags2 import VkPipelineStageFlags2
from ._vulkan_enum.VkPipelineTessellationStateCreateFlags import VkPipelineTessellationStateCreateFlags
from ._vulkan_enum.VkPipelineVertexInputStateCreateFlags import VkPipelineVertexInputStateCreateFlags
from ._vulkan_enum.VkPipelineViewportStateCreateFlags import VkPipelineViewportStateCreateFlags
from ._vulkan_enum.VkPipelineViewportSwizzleStateCreateFlagsNV import VkPipelineViewportSwizzleStateCreateFlagsNV
from ._vulkan_enum.VkPointClippingBehavior import VkPointClippingBehavior
from ._vulkan_enum.VkPolygonMode import VkPolygonMode
from ._vulkan_enum.VkPresentGravityFlagsEXT import VkPresentGravityFlagsEXT
from ._vulkan_enum.VkPresentModeKHR import VkPresentModeKHR
from ._vulkan_enum.VkPresentScalingFlagsEXT import VkPresentScalingFlagsEXT
from ._vulkan_enum.VkPrimitiveTopology import VkPrimitiveTopology
from ._vulkan_enum.VkPrivateDataSlotCreateFlagBits import VkPrivateDataSlotCreateFlagBits
from ._vulkan_enum.VkPrivateDataSlotCreateFlags import VkPrivateDataSlotCreateFlags
from ._vulkan_enum.VkProvokingVertexModeEXT import VkProvokingVertexModeEXT
from ._vulkan_enum.VkQueryControlFlags import VkQueryControlFlags
from ._vulkan_enum.VkQueryPipelineStatisticFlags import VkQueryPipelineStatisticFlags
from ._vulkan_enum.VkQueryPoolCreateFlags import VkQueryPoolCreateFlags
from ._vulkan_enum.VkQueryPoolSamplingModeINTEL import VkQueryPoolSamplingModeINTEL
from ._vulkan_enum.VkQueryResultFlags import VkQueryResultFlags
from ._vulkan_enum.VkQueryResultStatusKHR import VkQueryResultStatusKHR
from ._vulkan_enum.VkQueryType import VkQueryType
from ._vulkan_enum.VkQueueFlags import VkQueueFlags
from ._vulkan_enum.VkQueueGlobalPriorityKHR import VkQueueGlobalPriorityKHR
from ._vulkan_enum.VkRasterizationOrderAMD import VkRasterizationOrderAMD
from ._vulkan_enum.VkRayTracingInvocationReorderModeNV import VkRayTracingInvocationReorderModeNV
from ._vulkan_enum.VkRayTracingShaderGroupTypeKHR import VkRayTracingShaderGroupTypeKHR
from ._vulkan_enum.VkRefreshObjectFlagsKHR import VkRefreshObjectFlagsKHR
from ._vulkan_enum.VkRenderPassCreateFlags import VkRenderPassCreateFlags
from ._vulkan_enum.VkRenderingFlags import VkRenderingFlags
from ._vulkan_enum.VkResolveModeFlags import VkResolveModeFlags
from ._vulkan_enum.VkResult import VkResult
from ._vulkan_enum.VkSampleCountFlags import VkSampleCountFlags
from ._vulkan_enum.VkSamplerAddressMode import VkSamplerAddressMode
from ._vulkan_enum.VkSamplerCreateFlags import VkSamplerCreateFlags
from ._vulkan_enum.VkSamplerMipmapMode import VkSamplerMipmapMode
from ._vulkan_enum.VkSamplerReductionMode import VkSamplerReductionMode
from ._vulkan_enum.VkSamplerYcbcrModelConversion import VkSamplerYcbcrModelConversion
from ._vulkan_enum.VkSamplerYcbcrRange import VkSamplerYcbcrRange
from ._vulkan_enum.VkSciSyncClientTypeNV import VkSciSyncClientTypeNV
from ._vulkan_enum.VkSciSyncPrimitiveTypeNV import VkSciSyncPrimitiveTypeNV
from ._vulkan_enum.VkScopeKHR import VkScopeKHR
from ._vulkan_enum.VkScreenSurfaceCreateFlagsQNX import VkScreenSurfaceCreateFlagsQNX
from ._vulkan_enum.VkSemaphoreCreateFlagBits import VkSemaphoreCreateFlagBits
from ._vulkan_enum.VkSemaphoreCreateFlags import VkSemaphoreCreateFlags
from ._vulkan_enum.VkSemaphoreImportFlags import VkSemaphoreImportFlags
from ._vulkan_enum.VkSemaphoreType import VkSemaphoreType
from ._vulkan_enum.VkSemaphoreWaitFlags import VkSemaphoreWaitFlags
from ._vulkan_enum.VkShaderCodeTypeEXT import VkShaderCodeTypeEXT
from ._vulkan_enum.VkShaderCorePropertiesFlagsAMD import VkShaderCorePropertiesFlagsAMD
from ._vulkan_enum.VkShaderCreateFlagsEXT import VkShaderCreateFlagsEXT
from ._vulkan_enum.VkShaderFloatControlsIndependence import VkShaderFloatControlsIndependence
from ._vulkan_enum.VkShaderGroupShaderKHR import VkShaderGroupShaderKHR
from ._vulkan_enum.VkShaderInfoTypeAMD import VkShaderInfoTypeAMD
from ._vulkan_enum.VkShaderModuleCreateFlagBits import VkShaderModuleCreateFlagBits
from ._vulkan_enum.VkShaderModuleCreateFlags import VkShaderModuleCreateFlags
from ._vulkan_enum.VkShaderStageFlags import VkShaderStageFlags
from ._vulkan_enum.VkShadingRatePaletteEntryNV import VkShadingRatePaletteEntryNV
from ._vulkan_enum.VkSharingMode import VkSharingMode
from ._vulkan_enum.VkSparseImageFormatFlags import VkSparseImageFormatFlags
from ._vulkan_enum.VkSparseMemoryBindFlags import VkSparseMemoryBindFlags
from ._vulkan_enum.VkStencilFaceFlags import VkStencilFaceFlags
from ._vulkan_enum.VkStencilOp import VkStencilOp
from ._vulkan_enum.VkStreamDescriptorSurfaceCreateFlagsGGP import VkStreamDescriptorSurfaceCreateFlagsGGP
from ._vulkan_enum.VkStructureType import VkStructureType
from ._vulkan_enum.VkSubgroupFeatureFlags import VkSubgroupFeatureFlags
from ._vulkan_enum.VkSubmitFlags import VkSubmitFlags
from ._vulkan_enum.VkSubpassContents import VkSubpassContents
from ._vulkan_enum.VkSubpassDescriptionFlags import VkSubpassDescriptionFlags
from ._vulkan_enum.VkSubpassMergeStatusEXT import VkSubpassMergeStatusEXT
from ._vulkan_enum.VkSurfaceCounterFlagsEXT import VkSurfaceCounterFlagsEXT
from ._vulkan_enum.VkSurfaceTransformFlagsKHR import VkSurfaceTransformFlagsKHR
from ._vulkan_enum.VkSwapchainCreateFlagsKHR import VkSwapchainCreateFlagsKHR
from ._vulkan_enum.VkSwapchainImageUsageFlagsANDROID import VkSwapchainImageUsageFlagsANDROID
from ._vulkan_enum.VkSystemAllocationScope import VkSystemAllocationScope
from ._vulkan_enum.VkTessellationDomainOrigin import VkTessellationDomainOrigin
from ._vulkan_enum.VkTimeDomainKHR import VkTimeDomainKHR
from ._vulkan_enum.VkToolPurposeFlags import VkToolPurposeFlags
from ._vulkan_enum.VkValidationCacheCreateFlagsEXT import VkValidationCacheCreateFlagsEXT
from ._vulkan_enum.VkValidationCacheHeaderVersionEXT import VkValidationCacheHeaderVersionEXT
from ._vulkan_enum.VkValidationCheckEXT import VkValidationCheckEXT
from ._vulkan_enum.VkValidationFeatureDisableEXT import VkValidationFeatureDisableEXT
from ._vulkan_enum.VkValidationFeatureEnableEXT import VkValidationFeatureEnableEXT
from ._vulkan_enum.VkVendorId import VkVendorId
from ._vulkan_enum.VkVertexInputRate import VkVertexInputRate
from ._vulkan_enum.VkViSurfaceCreateFlagsNN import VkViSurfaceCreateFlagsNN
from ._vulkan_enum.VkVideoBeginCodingFlagsKHR import VkVideoBeginCodingFlagsKHR
from ._vulkan_enum.VkVideoCapabilityFlagsKHR import VkVideoCapabilityFlagsKHR
from ._vulkan_enum.VkVideoChromaSubsamplingFlagsKHR import VkVideoChromaSubsamplingFlagsKHR
from ._vulkan_enum.VkVideoCodecOperationFlagsKHR import VkVideoCodecOperationFlagsKHR
from ._vulkan_enum.VkVideoCodingControlFlagsKHR import VkVideoCodingControlFlagsKHR
from ._vulkan_enum.VkVideoComponentBitDepthFlagsKHR import VkVideoComponentBitDepthFlagsKHR
from ._vulkan_enum.VkVideoDecodeCapabilityFlagsKHR import VkVideoDecodeCapabilityFlagsKHR
from ._vulkan_enum.VkVideoDecodeFlagsKHR import VkVideoDecodeFlagsKHR
from ._vulkan_enum.VkVideoDecodeH264PictureLayoutFlagsKHR import VkVideoDecodeH264PictureLayoutFlagsKHR
from ._vulkan_enum.VkVideoDecodeUsageFlagsKHR import VkVideoDecodeUsageFlagsKHR
from ._vulkan_enum.VkVideoEncodeCapabilityFlagsKHR import VkVideoEncodeCapabilityFlagsKHR
from ._vulkan_enum.VkVideoEncodeContentFlagsKHR import VkVideoEncodeContentFlagsKHR
from ._vulkan_enum.VkVideoEncodeFeedbackFlagsKHR import VkVideoEncodeFeedbackFlagsKHR
from ._vulkan_enum.VkVideoEncodeFlagsKHR import VkVideoEncodeFlagsKHR
from ._vulkan_enum.VkVideoEncodeH264CapabilityFlagsKHR import VkVideoEncodeH264CapabilityFlagsKHR
from ._vulkan_enum.VkVideoEncodeH264RateControlFlagsKHR import VkVideoEncodeH264RateControlFlagsKHR
from ._vulkan_enum.VkVideoEncodeH264StdFlagsKHR import VkVideoEncodeH264StdFlagsKHR
from ._vulkan_enum.VkVideoEncodeH265CapabilityFlagsKHR import VkVideoEncodeH265CapabilityFlagsKHR
from ._vulkan_enum.VkVideoEncodeH265CtbSizeFlagsKHR import VkVideoEncodeH265CtbSizeFlagsKHR
from ._vulkan_enum.VkVideoEncodeH265RateControlFlagsKHR import VkVideoEncodeH265RateControlFlagsKHR
from ._vulkan_enum.VkVideoEncodeH265StdFlagsKHR import VkVideoEncodeH265StdFlagsKHR
from ._vulkan_enum.VkVideoEncodeH265TransformBlockSizeFlagsKHR import VkVideoEncodeH265TransformBlockSizeFlagsKHR
from ._vulkan_enum.VkVideoEncodeRateControlFlagsKHR import VkVideoEncodeRateControlFlagsKHR
from ._vulkan_enum.VkVideoEncodeRateControlModeFlagsKHR import VkVideoEncodeRateControlModeFlagsKHR
from ._vulkan_enum.VkVideoEncodeTuningModeKHR import VkVideoEncodeTuningModeKHR
from ._vulkan_enum.VkVideoEncodeUsageFlagsKHR import VkVideoEncodeUsageFlagsKHR
from ._vulkan_enum.VkVideoEndCodingFlagsKHR import VkVideoEndCodingFlagsKHR
from ._vulkan_enum.VkVideoSessionCreateFlagsKHR import VkVideoSessionCreateFlagsKHR
from ._vulkan_enum.VkVideoSessionParametersCreateFlagsKHR import VkVideoSessionParametersCreateFlagsKHR
from ._vulkan_enum.VkViewportCoordinateSwizzleNV import VkViewportCoordinateSwizzleNV
from ._vulkan_enum.VkWaylandSurfaceCreateFlagsKHR import VkWaylandSurfaceCreateFlagsKHR
from ._vulkan_enum.VkWin32SurfaceCreateFlagsKHR import VkWin32SurfaceCreateFlagsKHR
from ._vulkan_enum.VkXcbSurfaceCreateFlagsKHR import VkXcbSurfaceCreateFlagsKHR
from ._vulkan_enum.VkXlibSurfaceCreateFlagsKHR import VkXlibSurfaceCreateFlagsKHR

VkAccelerationStructureTypeNV = VkAccelerationStructureTypeKHR
VkAccessFlags2KHR = VkAccessFlags2
VkBuildAccelerationStructureFlagsNV = VkBuildAccelerationStructureFlagsKHR
VkChromaLocationKHR = VkChromaLocation
VkCommandPoolTrimFlagsKHR = VkCommandPoolTrimFlags
VkComponentTypeNV = VkComponentTypeKHR
VkCopyAccelerationStructureModeNV = VkCopyAccelerationStructureModeKHR
VkDescriptorBindingFlagsEXT = VkDescriptorBindingFlags
VkDescriptorUpdateTemplateCreateFlagsKHR = VkDescriptorUpdateTemplateCreateFlags
VkDescriptorUpdateTemplateTypeKHR = VkDescriptorUpdateTemplateType
VkDriverIdKHR = VkDriverId
VkExternalFenceFeatureFlagsKHR = VkExternalFenceFeatureFlags
VkExternalFenceHandleTypeFlagsKHR = VkExternalFenceHandleTypeFlags
VkExternalMemoryFeatureFlagsKHR = VkExternalMemoryFeatureFlags
VkExternalMemoryHandleTypeFlagsKHR = VkExternalMemoryHandleTypeFlags
VkExternalSemaphoreFeatureFlagsKHR = VkExternalSemaphoreFeatureFlags
VkExternalSemaphoreHandleTypeFlagsKHR = VkExternalSemaphoreHandleTypeFlags
VkFenceImportFlagsKHR = VkFenceImportFlags
VkFormatFeatureFlags2KHR = VkFormatFeatureFlags2
VkGeometryFlagsNV = VkGeometryFlagsKHR
VkGeometryInstanceFlagsNV = VkGeometryInstanceFlagsKHR
VkGeometryTypeNV = VkGeometryTypeKHR
VkLineRasterizationModeEXT = VkLineRasterizationModeKHR
VkMemoryAllocateFlagsKHR = VkMemoryAllocateFlags
VkPeerMemoryFeatureFlagsKHR = VkPeerMemoryFeatureFlags
VkPipelineCreationFeedbackFlagsEXT = VkPipelineCreationFeedbackFlags
VkPipelineStageFlags2KHR = VkPipelineStageFlags2
VkPointClippingBehaviorKHR = VkPointClippingBehavior
VkPrivateDataSlotCreateFlagBitsEXT = VkPrivateDataSlotCreateFlagBits
VkPrivateDataSlotCreateFlagsEXT = VkPrivateDataSlotCreateFlags
VkQueueGlobalPriorityEXT = VkQueueGlobalPriorityKHR
VkRayTracingShaderGroupTypeNV = VkRayTracingShaderGroupTypeKHR
VkRenderingFlagsKHR = VkRenderingFlags
VkResolveModeFlagsKHR = VkResolveModeFlags
VkSamplerReductionModeEXT = VkSamplerReductionMode
VkSamplerYcbcrModelConversionKHR = VkSamplerYcbcrModelConversion
VkSamplerYcbcrRangeKHR = VkSamplerYcbcrRange
VkScopeNV = VkScopeKHR
VkSemaphoreImportFlagsKHR = VkSemaphoreImportFlags
VkSemaphoreTypeKHR = VkSemaphoreType
VkSemaphoreWaitFlagsKHR = VkSemaphoreWaitFlags
VkShaderFloatControlsIndependenceKHR = VkShaderFloatControlsIndependence
VkSubmitFlagsKHR = VkSubmitFlags
VkTessellationDomainOriginKHR = VkTessellationDomainOrigin
VkTimeDomainEXT = VkTimeDomainKHR
VkToolPurposeFlagsEXT = VkToolPurposeFlags
