from ._vulkan_type import (
    StdVideoAV1CDEF,
    StdVideoAV1ColorConfig,
    StdVideoAV1ColorConfigFlags,
    StdVideoAV1FilmGrain,
    StdVideoAV1FilmGrainFlags,
    StdVideoAV1GlobalMotion,
    StdVideoAV1LoopFilter,
    StdVideoAV1LoopFilterFlags,
    StdVideoAV1LoopRestoration,
    StdVideoAV1Quantization,
    StdVideoAV1QuantizationFlags,
    StdVideoAV1Segmentation,
    StdVideoAV1SequenceHeader,
    StdVideoAV1SequenceHeaderFlags,
    StdVideoAV1TileInfo,
    StdVideoAV1TileInfoFlags,
    StdVideoAV1TimingInfo,
    StdVideoAV1TimingInfoFlags,
    StdVideoDecodeAV1PictureInfo,
    StdVideoDecodeAV1PictureInfoFlags,
    StdVideoDecodeAV1ReferenceInfo,
    StdVideoDecodeAV1ReferenceInfoFlags,
    StdVideoDecodeH264PictureInfo,
    StdVideoDecodeH264PictureInfoFlags,
    StdVideoDecodeH264ReferenceInfo,
    StdVideoDecodeH264ReferenceInfoFlags,
    StdVideoDecodeH265PictureInfo,
    StdVideoDecodeH265PictureInfoFlags,
    StdVideoDecodeH265ReferenceInfo,
    StdVideoDecodeH265ReferenceInfoFlags,
    StdVideoEncodeH264PictureInfo,
    StdVideoEncodeH264PictureInfoFlags,
    StdVideoEncodeH264RefListModEntry,
    StdVideoEncodeH264RefPicMarkingEntry,
    StdVideoEncodeH264ReferenceInfo,
    StdVideoEncodeH264ReferenceInfoFlags,
    StdVideoEncodeH264ReferenceListsInfo,
    StdVideoEncodeH264ReferenceListsInfoFlags,
    StdVideoEncodeH264SliceHeader,
    StdVideoEncodeH264SliceHeaderFlags,
    StdVideoEncodeH264WeightTable,
    StdVideoEncodeH264WeightTableFlags,
    StdVideoEncodeH265LongTermRefPics,
    StdVideoEncodeH265PictureInfo,
    StdVideoEncodeH265PictureInfoFlags,
    StdVideoEncodeH265ReferenceInfo,
    StdVideoEncodeH265ReferenceInfoFlags,
    StdVideoEncodeH265ReferenceListsInfo,
    StdVideoEncodeH265ReferenceListsInfoFlags,
    StdVideoEncodeH265SliceSegmentHeader,
    StdVideoEncodeH265SliceSegmentHeaderFlags,
    StdVideoEncodeH265WeightTable,
    StdVideoEncodeH265WeightTableFlags,
    StdVideoH264HrdParameters,
    StdVideoH264PictureParameterSet,
    StdVideoH264PpsFlags,
    StdVideoH264ScalingLists,
    StdVideoH264SequenceParameterSet,
    StdVideoH264SequenceParameterSetVui,
    StdVideoH264SpsFlags,
    StdVideoH264SpsVuiFlags,
    StdVideoH265DecPicBufMgr,
    StdVideoH265HrdFlags,
    StdVideoH265HrdParameters,
    StdVideoH265LongTermRefPicsSps,
    StdVideoH265PictureParameterSet,
    StdVideoH265PpsFlags,
    StdVideoH265PredictorPaletteEntries,
    StdVideoH265ProfileTierLevel,
    StdVideoH265ProfileTierLevelFlags,
    StdVideoH265ScalingLists,
    StdVideoH265SequenceParameterSet,
    StdVideoH265SequenceParameterSetVui,
    StdVideoH265ShortTermRefPicSet,
    StdVideoH265ShortTermRefPicSetFlags,
    StdVideoH265SpsFlags,
    StdVideoH265SpsVuiFlags,
    StdVideoH265SubLayerHrdParameters,
    StdVideoH265VideoParameterSet,
    StdVideoH265VpsFlags,
    VkAabbPositionsKHR,
    VkAccelerationStructureBuildGeometryInfoKHR,
    VkAccelerationStructureBuildRangeInfoKHR,
    VkAccelerationStructureBuildSizesInfoKHR,
    VkAccelerationStructureCaptureDescriptorDataInfoEXT,
    VkAccelerationStructureCreateInfoKHR,
    VkAccelerationStructureCreateInfoNV,
    VkAccelerationStructureDeviceAddressInfoKHR,
    VkAccelerationStructureGeometryAabbsDataKHR,
    VkAccelerationStructureGeometryDataKHR,
    VkAccelerationStructureGeometryInstancesDataKHR,
    VkAccelerationStructureGeometryKHR,
    VkAccelerationStructureGeometryMotionTrianglesDataNV,
    VkAccelerationStructureGeometryTrianglesDataKHR,
    VkAccelerationStructureInfoNV,
    VkAccelerationStructureInstanceKHR,
    VkAccelerationStructureMatrixMotionInstanceNV,
    VkAccelerationStructureMemoryRequirementsInfoNV,
    VkAccelerationStructureMotionInfoNV,
    VkAccelerationStructureMotionInstanceDataNV,
    VkAccelerationStructureMotionInstanceNV,
    VkAccelerationStructureSRTMotionInstanceNV,
    VkAccelerationStructureTrianglesDisplacementMicromapNV,
    VkAccelerationStructureTrianglesOpacityMicromapEXT,
    VkAccelerationStructureVersionInfoKHR,
    VkAcquireNextImageInfoKHR,
    VkAcquireProfilingLockInfoKHR,
    VkAllocationCallbacks,
    VkAmigoProfilingSubmitInfoSEC,
    VkAndroidHardwareBufferFormatProperties2ANDROID,
    VkAndroidHardwareBufferFormatPropertiesANDROID,
    VkAndroidHardwareBufferFormatResolvePropertiesANDROID,
    VkAndroidHardwareBufferPropertiesANDROID,
    VkAndroidHardwareBufferUsageANDROID,
    VkAndroidSurfaceCreateInfoKHR,
    VkApplicationInfo,
    VkApplicationParametersEXT,
    VkAttachmentDescription,
    VkAttachmentDescription2,
    VkAttachmentDescriptionStencilLayout,
    VkAttachmentReference,
    VkAttachmentReference2,
    VkAttachmentReferenceStencilLayout,
    VkAttachmentSampleCountInfoAMD,
    VkAttachmentSampleLocationsEXT,
    VkBaseInStructure,
    VkBaseOutStructure,
    VkBindAccelerationStructureMemoryInfoNV,
    VkBindBufferMemoryDeviceGroupInfo,
    VkBindBufferMemoryInfo,
    VkBindDescriptorBufferEmbeddedSamplersInfoEXT,
    VkBindDescriptorSetsInfoKHR,
    VkBindImageMemoryDeviceGroupInfo,
    VkBindImageMemoryInfo,
    VkBindImageMemorySwapchainInfoKHR,
    VkBindImagePlaneMemoryInfo,
    VkBindIndexBufferIndirectCommandNV,
    VkBindMemoryStatusKHR,
    VkBindPipelineIndirectCommandNV,
    VkBindShaderGroupIndirectCommandNV,
    VkBindSparseInfo,
    VkBindVertexBufferIndirectCommandNV,
    VkBindVideoSessionMemoryInfoKHR,
    VkBlitImageCubicWeightsInfoQCOM,
    VkBlitImageInfo2,
    VkBufferCaptureDescriptorDataInfoEXT,
    VkBufferCollectionBufferCreateInfoFUCHSIA,
    VkBufferCollectionConstraintsInfoFUCHSIA,
    VkBufferCollectionCreateInfoFUCHSIA,
    VkBufferCollectionImageCreateInfoFUCHSIA,
    VkBufferCollectionPropertiesFUCHSIA,
    VkBufferConstraintsInfoFUCHSIA,
    VkBufferCopy,
    VkBufferCopy2,
    VkBufferCreateInfo,
    VkBufferDeviceAddressCreateInfoEXT,
    VkBufferDeviceAddressInfo,
    VkBufferImageCopy,
    VkBufferImageCopy2,
    VkBufferMemoryBarrier,
    VkBufferMemoryBarrier2,
    VkBufferMemoryRequirementsInfo2,
    VkBufferOpaqueCaptureAddressCreateInfo,
    VkBufferUsageFlags2CreateInfoKHR,
    VkBufferViewCreateInfo,
    VkCalibratedTimestampInfoKHR,
    VkCheckpointData2NV,
    VkCheckpointDataNV,
    VkClearAttachment,
    VkClearColorValue,
    VkClearDepthStencilValue,
    VkClearRect,
    VkClearValue,
    VkCoarseSampleLocationNV,
    VkCoarseSampleOrderCustomNV,
    VkColorBlendAdvancedEXT,
    VkColorBlendEquationEXT,
    VkCommandBufferAllocateInfo,
    VkCommandBufferBeginInfo,
    VkCommandBufferInheritanceConditionalRenderingInfoEXT,
    VkCommandBufferInheritanceInfo,
    VkCommandBufferInheritanceRenderPassTransformInfoQCOM,
    VkCommandBufferInheritanceRenderingInfo,
    VkCommandBufferInheritanceViewportScissorInfoNV,
    VkCommandBufferSubmitInfo,
    VkCommandPoolCreateInfo,
    VkCommandPoolMemoryConsumption,
    VkCommandPoolMemoryReservationCreateInfo,
    VkComponentMapping,
    VkComputePipelineCreateInfo,
    VkComputePipelineIndirectBufferInfoNV,
    VkConditionalRenderingBeginInfoEXT,
    VkConformanceVersion,
    VkCooperativeMatrixPropertiesKHR,
    VkCooperativeMatrixPropertiesNV,
    VkCopyAccelerationStructureInfoKHR,
    VkCopyAccelerationStructureToMemoryInfoKHR,
    VkCopyBufferInfo2,
    VkCopyBufferToImageInfo2,
    VkCopyCommandTransformInfoQCOM,
    VkCopyDescriptorSet,
    VkCopyImageInfo2,
    VkCopyImageToBufferInfo2,
    VkCopyImageToImageInfoEXT,
    VkCopyImageToMemoryInfoEXT,
    VkCopyMemoryIndirectCommandNV,
    VkCopyMemoryToAccelerationStructureInfoKHR,
    VkCopyMemoryToImageIndirectCommandNV,
    VkCopyMemoryToImageInfoEXT,
    VkCopyMemoryToMicromapInfoEXT,
    VkCopyMicromapInfoEXT,
    VkCopyMicromapToMemoryInfoEXT,
    VkCuFunctionCreateInfoNVX,
    VkCuLaunchInfoNVX,
    VkCuModuleCreateInfoNVX,
    VkCudaFunctionCreateInfoNV,
    VkCudaLaunchInfoNV,
    VkCudaModuleCreateInfoNV,
    VkD3D12FenceSubmitInfoKHR,
    VkDebugMarkerMarkerInfoEXT,
    VkDebugMarkerObjectNameInfoEXT,
    VkDebugMarkerObjectTagInfoEXT,
    VkDebugReportCallbackCreateInfoEXT,
    VkDebugUtilsLabelEXT,
    VkDebugUtilsMessengerCallbackDataEXT,
    VkDebugUtilsMessengerCreateInfoEXT,
    VkDebugUtilsObjectNameInfoEXT,
    VkDebugUtilsObjectTagInfoEXT,
    VkDecompressMemoryRegionNV,
    VkDedicatedAllocationBufferCreateInfoNV,
    VkDedicatedAllocationImageCreateInfoNV,
    VkDedicatedAllocationMemoryAllocateInfoNV,
    VkDependencyInfo,
    VkDepthBiasInfoEXT,
    VkDepthBiasRepresentationInfoEXT,
    VkDescriptorAddressInfoEXT,
    VkDescriptorBufferBindingInfoEXT,
    VkDescriptorBufferBindingPushDescriptorBufferHandleEXT,
    VkDescriptorBufferInfo,
    VkDescriptorDataEXT,
    VkDescriptorGetInfoEXT,
    VkDescriptorImageInfo,
    VkDescriptorPoolCreateInfo,
    VkDescriptorPoolInlineUniformBlockCreateInfo,
    VkDescriptorPoolSize,
    VkDescriptorSetAllocateInfo,
    VkDescriptorSetBindingReferenceVALVE,
    VkDescriptorSetLayoutBinding,
    VkDescriptorSetLayoutBindingFlagsCreateInfo,
    VkDescriptorSetLayoutCreateInfo,
    VkDescriptorSetLayoutHostMappingInfoVALVE,
    VkDescriptorSetLayoutSupport,
    VkDescriptorSetVariableDescriptorCountAllocateInfo,
    VkDescriptorSetVariableDescriptorCountLayoutSupport,
    VkDescriptorUpdateTemplateCreateInfo,
    VkDescriptorUpdateTemplateEntry,
    VkDeviceAddressBindingCallbackDataEXT,
    VkDeviceBufferMemoryRequirements,
    VkDeviceCreateInfo,
    VkDeviceDeviceMemoryReportCreateInfoEXT,
    VkDeviceDiagnosticsConfigCreateInfoNV,
    VkDeviceEventInfoEXT,
    VkDeviceFaultAddressInfoEXT,
    VkDeviceFaultCountsEXT,
    VkDeviceFaultInfoEXT,
    VkDeviceFaultVendorBinaryHeaderVersionOneEXT,
    VkDeviceFaultVendorInfoEXT,
    VkDeviceGroupBindSparseInfo,
    VkDeviceGroupCommandBufferBeginInfo,
    VkDeviceGroupDeviceCreateInfo,
    VkDeviceGroupPresentCapabilitiesKHR,
    VkDeviceGroupPresentInfoKHR,
    VkDeviceGroupRenderPassBeginInfo,
    VkDeviceGroupSubmitInfo,
    VkDeviceGroupSwapchainCreateInfoKHR,
    VkDeviceImageMemoryRequirements,
    VkDeviceImageSubresourceInfoKHR,
    VkDeviceMemoryOpaqueCaptureAddressInfo,
    VkDeviceMemoryOverallocationCreateInfoAMD,
    VkDeviceMemoryReportCallbackDataEXT,
    VkDeviceObjectReservationCreateInfo,
    VkDeviceOrHostAddressConstAMDX,
    VkDeviceOrHostAddressConstKHR,
    VkDeviceOrHostAddressKHR,
    VkDevicePrivateDataCreateInfo,
    VkDeviceQueueCreateInfo,
    VkDeviceQueueGlobalPriorityCreateInfoKHR,
    VkDeviceQueueInfo2,
    VkDeviceQueueShaderCoreControlCreateInfoARM,
    VkDeviceSemaphoreSciSyncPoolReservationCreateInfoNV,
    VkDirectDriverLoadingInfoLUNARG,
    VkDirectDriverLoadingListLUNARG,
    VkDirectFBSurfaceCreateInfoEXT,
    VkDispatchGraphCountInfoAMDX,
    VkDispatchGraphInfoAMDX,
    VkDispatchIndirectCommand,
    VkDisplayEventInfoEXT,
    VkDisplayModeCreateInfoKHR,
    VkDisplayModeParametersKHR,
    VkDisplayModeProperties2KHR,
    VkDisplayModePropertiesKHR,
    VkDisplayNativeHdrSurfaceCapabilitiesAMD,
    VkDisplayPlaneCapabilities2KHR,
    VkDisplayPlaneCapabilitiesKHR,
    VkDisplayPlaneInfo2KHR,
    VkDisplayPlaneProperties2KHR,
    VkDisplayPlanePropertiesKHR,
    VkDisplayPowerInfoEXT,
    VkDisplayPresentInfoKHR,
    VkDisplayProperties2KHR,
    VkDisplayPropertiesKHR,
    VkDisplaySurfaceCreateInfoKHR,
    VkDrawIndexedIndirectCommand,
    VkDrawIndirectCommand,
    VkDrawMeshTasksIndirectCommandEXT,
    VkDrawMeshTasksIndirectCommandNV,
    VkDrmFormatModifierProperties2EXT,
    VkDrmFormatModifierPropertiesEXT,
    VkDrmFormatModifierPropertiesList2EXT,
    VkDrmFormatModifierPropertiesListEXT,
    VkEventCreateInfo,
    VkExecutionGraphPipelineCreateInfoAMDX,
    VkExecutionGraphPipelineScratchSizeAMDX,
    VkExportFenceCreateInfo,
    VkExportFenceSciSyncInfoNV,
    VkExportFenceWin32HandleInfoKHR,
    VkExportMemoryAllocateInfo,
    VkExportMemoryAllocateInfoNV,
    VkExportMemorySciBufInfoNV,
    VkExportMemoryWin32HandleInfoKHR,
    VkExportMemoryWin32HandleInfoNV,
    VkExportMetalBufferInfoEXT,
    VkExportMetalCommandQueueInfoEXT,
    VkExportMetalDeviceInfoEXT,
    VkExportMetalIOSurfaceInfoEXT,
    VkExportMetalObjectCreateInfoEXT,
    VkExportMetalObjectsInfoEXT,
    VkExportMetalSharedEventInfoEXT,
    VkExportMetalTextureInfoEXT,
    VkExportSemaphoreCreateInfo,
    VkExportSemaphoreSciSyncInfoNV,
    VkExportSemaphoreWin32HandleInfoKHR,
    VkExtensionProperties,
    VkExtent2D,
    VkExtent3D,
    VkExternalBufferProperties,
    VkExternalFenceProperties,
    VkExternalFormatANDROID,
    VkExternalFormatQNX,
    VkExternalImageFormatProperties,
    VkExternalImageFormatPropertiesNV,
    VkExternalMemoryAcquireUnmodifiedEXT,
    VkExternalMemoryBufferCreateInfo,
    VkExternalMemoryImageCreateInfo,
    VkExternalMemoryImageCreateInfoNV,
    VkExternalMemoryProperties,
    VkExternalSemaphoreProperties,
    VkFaultCallbackInfo,
    VkFaultData,
    VkFenceCreateInfo,
    VkFenceGetFdInfoKHR,
    VkFenceGetSciSyncInfoNV,
    VkFenceGetWin32HandleInfoKHR,
    VkFilterCubicImageViewImageFormatPropertiesEXT,
    VkFormatProperties,
    VkFormatProperties2,
    VkFormatProperties3,
    VkFragmentShadingRateAttachmentInfoKHR,
    VkFrameBoundaryEXT,
    VkFramebufferAttachmentImageInfo,
    VkFramebufferAttachmentsCreateInfo,
    VkFramebufferCreateInfo,
    VkFramebufferMixedSamplesCombinationNV,
    VkGeneratedCommandsInfoNV,
    VkGeneratedCommandsMemoryRequirementsInfoNV,
    VkGeometryAABBNV,
    VkGeometryDataNV,
    VkGeometryNV,
    VkGeometryTrianglesNV,
    VkGetLatencyMarkerInfoNV,
    VkGraphicsPipelineCreateInfo,
    VkGraphicsPipelineLibraryCreateInfoEXT,
    VkGraphicsPipelineShaderGroupsCreateInfoNV,
    VkGraphicsShaderGroupCreateInfoNV,
    VkHdrMetadataEXT,
    VkHeadlessSurfaceCreateInfoEXT,
    VkHostImageCopyDevicePerformanceQueryEXT,
    VkHostImageLayoutTransitionInfoEXT,
    VkIOSSurfaceCreateInfoMVK,
    VkImageAlignmentControlCreateInfoMESA,
    VkImageBlit,
    VkImageBlit2,
    VkImageCaptureDescriptorDataInfoEXT,
    VkImageCompressionControlEXT,
    VkImageCompressionPropertiesEXT,
    VkImageConstraintsInfoFUCHSIA,
    VkImageCopy,
    VkImageCopy2,
    VkImageCreateInfo,
    VkImageDrmFormatModifierExplicitCreateInfoEXT,
    VkImageDrmFormatModifierListCreateInfoEXT,
    VkImageDrmFormatModifierPropertiesEXT,
    VkImageFormatConstraintsInfoFUCHSIA,
    VkImageFormatListCreateInfo,
    VkImageFormatProperties,
    VkImageFormatProperties2,
    VkImageMemoryBarrier,
    VkImageMemoryBarrier2,
    VkImageMemoryRequirementsInfo2,
    VkImagePipeSurfaceCreateInfoFUCHSIA,
    VkImagePlaneMemoryRequirementsInfo,
    VkImageResolve,
    VkImageResolve2,
    VkImageSparseMemoryRequirementsInfo2,
    VkImageStencilUsageCreateInfo,
    VkImageSubresource,
    VkImageSubresource2KHR,
    VkImageSubresourceLayers,
    VkImageSubresourceRange,
    VkImageSwapchainCreateInfoKHR,
    VkImageToMemoryCopyEXT,
    VkImageViewASTCDecodeModeEXT,
    VkImageViewAddressPropertiesNVX,
    VkImageViewCaptureDescriptorDataInfoEXT,
    VkImageViewCreateInfo,
    VkImageViewHandleInfoNVX,
    VkImageViewMinLodCreateInfoEXT,
    VkImageViewSampleWeightCreateInfoQCOM,
    VkImageViewSlicedCreateInfoEXT,
    VkImageViewUsageCreateInfo,
    VkImportAndroidHardwareBufferInfoANDROID,
    VkImportFenceFdInfoKHR,
    VkImportFenceSciSyncInfoNV,
    VkImportFenceWin32HandleInfoKHR,
    VkImportMemoryBufferCollectionFUCHSIA,
    VkImportMemoryFdInfoKHR,
    VkImportMemoryHostPointerInfoEXT,
    VkImportMemorySciBufInfoNV,
    VkImportMemoryWin32HandleInfoKHR,
    VkImportMemoryWin32HandleInfoNV,
    VkImportMemoryZirconHandleInfoFUCHSIA,
    VkImportMetalBufferInfoEXT,
    VkImportMetalIOSurfaceInfoEXT,
    VkImportMetalSharedEventInfoEXT,
    VkImportMetalTextureInfoEXT,
    VkImportScreenBufferInfoQNX,
    VkImportSemaphoreFdInfoKHR,
    VkImportSemaphoreSciSyncInfoNV,
    VkImportSemaphoreWin32HandleInfoKHR,
    VkImportSemaphoreZirconHandleInfoFUCHSIA,
    VkIndirectCommandsLayoutCreateInfoNV,
    VkIndirectCommandsLayoutTokenNV,
    VkIndirectCommandsStreamNV,
    VkInitializePerformanceApiInfoINTEL,
    VkInputAttachmentAspectReference,
    VkInstanceCreateInfo,
    VkLatencySleepInfoNV,
    VkLatencySleepModeInfoNV,
    VkLatencySubmissionPresentIdNV,
    VkLatencySurfaceCapabilitiesNV,
    VkLatencyTimingsFrameReportNV,
    VkLayerProperties,
    VkLayerSettingEXT,
    VkLayerSettingsCreateInfoEXT,
    VkMacOSSurfaceCreateInfoMVK,
    VkMappedMemoryRange,
    VkMemoryAllocateFlagsInfo,
    VkMemoryAllocateInfo,
    VkMemoryBarrier,
    VkMemoryBarrier2,
    VkMemoryDedicatedAllocateInfo,
    VkMemoryDedicatedRequirements,
    VkMemoryFdPropertiesKHR,
    VkMemoryGetAndroidHardwareBufferInfoANDROID,
    VkMemoryGetFdInfoKHR,
    VkMemoryGetRemoteAddressInfoNV,
    VkMemoryGetSciBufInfoNV,
    VkMemoryGetWin32HandleInfoKHR,
    VkMemoryGetZirconHandleInfoFUCHSIA,
    VkMemoryHeap,
    VkMemoryHostPointerPropertiesEXT,
    VkMemoryMapInfoKHR,
    VkMemoryMapPlacedInfoEXT,
    VkMemoryOpaqueCaptureAddressAllocateInfo,
    VkMemoryPriorityAllocateInfoEXT,
    VkMemoryRequirements,
    VkMemoryRequirements2,
    VkMemorySciBufPropertiesNV,
    VkMemoryToImageCopyEXT,
    VkMemoryType,
    VkMemoryUnmapInfoKHR,
    VkMemoryWin32HandlePropertiesKHR,
    VkMemoryZirconHandlePropertiesFUCHSIA,
    VkMetalSurfaceCreateInfoEXT,
    VkMicromapBuildInfoEXT,
    VkMicromapBuildSizesInfoEXT,
    VkMicromapCreateInfoEXT,
    VkMicromapTriangleEXT,
    VkMicromapUsageEXT,
    VkMicromapVersionInfoEXT,
    VkMultiDrawIndexedInfoEXT,
    VkMultiDrawInfoEXT,
    VkMultisamplePropertiesEXT,
    VkMultisampledRenderToSingleSampledInfoEXT,
    VkMultiviewPerViewAttributesInfoNVX,
    VkMultiviewPerViewRenderAreasRenderPassBeginInfoQCOM,
    VkMutableDescriptorTypeCreateInfoEXT,
    VkMutableDescriptorTypeListEXT,
    VkNativeBufferANDROID,
    VkNativeBufferUsage2ANDROID,
    VkOffset2D,
    VkOffset3D,
    VkOpaqueCaptureDescriptorDataCreateInfoEXT,
    VkOpticalFlowExecuteInfoNV,
    VkOpticalFlowImageFormatInfoNV,
    VkOpticalFlowImageFormatPropertiesNV,
    VkOpticalFlowSessionCreateInfoNV,
    VkOpticalFlowSessionCreatePrivateDataInfoNV,
    VkOutOfBandQueueTypeInfoNV,
    VkPastPresentationTimingGOOGLE,
    VkPerformanceConfigurationAcquireInfoINTEL,
    VkPerformanceCounterDescriptionKHR,
    VkPerformanceCounterKHR,
    VkPerformanceCounterResultKHR,
    VkPerformanceMarkerInfoINTEL,
    VkPerformanceOverrideInfoINTEL,
    VkPerformanceQueryReservationInfoKHR,
    VkPerformanceQuerySubmitInfoKHR,
    VkPerformanceStreamMarkerInfoINTEL,
    VkPerformanceValueDataINTEL,
    VkPerformanceValueINTEL,
    VkPhysicalDevice16BitStorageFeatures,
    VkPhysicalDevice4444FormatsFeaturesEXT,
    VkPhysicalDevice8BitStorageFeatures,
    VkPhysicalDeviceASTCDecodeFeaturesEXT,
    VkPhysicalDeviceAccelerationStructureFeaturesKHR,
    VkPhysicalDeviceAccelerationStructurePropertiesKHR,
    VkPhysicalDeviceAddressBindingReportFeaturesEXT,
    VkPhysicalDeviceAmigoProfilingFeaturesSEC,
    VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXT,
    VkPhysicalDeviceAttachmentFeedbackLoopLayoutFeaturesEXT,
    VkPhysicalDeviceBlendOperationAdvancedFeaturesEXT,
    VkPhysicalDeviceBlendOperationAdvancedPropertiesEXT,
    VkPhysicalDeviceBorderColorSwizzleFeaturesEXT,
    VkPhysicalDeviceBufferDeviceAddressFeatures,
    VkPhysicalDeviceBufferDeviceAddressFeaturesEXT,
    VkPhysicalDeviceClusterCullingShaderFeaturesHUAWEI,
    VkPhysicalDeviceClusterCullingShaderPropertiesHUAWEI,
    VkPhysicalDeviceClusterCullingShaderVrsFeaturesHUAWEI,
    VkPhysicalDeviceCoherentMemoryFeaturesAMD,
    VkPhysicalDeviceColorWriteEnableFeaturesEXT,
    VkPhysicalDeviceComputeShaderDerivativesFeaturesNV,
    VkPhysicalDeviceConditionalRenderingFeaturesEXT,
    VkPhysicalDeviceConservativeRasterizationPropertiesEXT,
    VkPhysicalDeviceCooperativeMatrixFeaturesKHR,
    VkPhysicalDeviceCooperativeMatrixFeaturesNV,
    VkPhysicalDeviceCooperativeMatrixPropertiesKHR,
    VkPhysicalDeviceCooperativeMatrixPropertiesNV,
    VkPhysicalDeviceCopyMemoryIndirectFeaturesNV,
    VkPhysicalDeviceCopyMemoryIndirectPropertiesNV,
    VkPhysicalDeviceCornerSampledImageFeaturesNV,
    VkPhysicalDeviceCoverageReductionModeFeaturesNV,
    VkPhysicalDeviceCubicClampFeaturesQCOM,
    VkPhysicalDeviceCubicWeightsFeaturesQCOM,
    VkPhysicalDeviceCudaKernelLaunchFeaturesNV,
    VkPhysicalDeviceCudaKernelLaunchPropertiesNV,
    VkPhysicalDeviceCustomBorderColorFeaturesEXT,
    VkPhysicalDeviceCustomBorderColorPropertiesEXT,
    VkPhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV,
    VkPhysicalDeviceDepthBiasControlFeaturesEXT,
    VkPhysicalDeviceDepthClampZeroOneFeaturesEXT,
    VkPhysicalDeviceDepthClipControlFeaturesEXT,
    VkPhysicalDeviceDepthClipEnableFeaturesEXT,
    VkPhysicalDeviceDepthStencilResolveProperties,
    VkPhysicalDeviceDescriptorBufferDensityMapPropertiesEXT,
    VkPhysicalDeviceDescriptorBufferFeaturesEXT,
    VkPhysicalDeviceDescriptorBufferPropertiesEXT,
    VkPhysicalDeviceDescriptorIndexingFeatures,
    VkPhysicalDeviceDescriptorIndexingProperties,
    VkPhysicalDeviceDescriptorPoolOverallocationFeaturesNV,
    VkPhysicalDeviceDescriptorSetHostMappingFeaturesVALVE,
    VkPhysicalDeviceDeviceGeneratedCommandsComputeFeaturesNV,
    VkPhysicalDeviceDeviceGeneratedCommandsFeaturesNV,
    VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV,
    VkPhysicalDeviceDeviceMemoryReportFeaturesEXT,
    VkPhysicalDeviceDiagnosticsConfigFeaturesNV,
    VkPhysicalDeviceDiscardRectanglePropertiesEXT,
    VkPhysicalDeviceDisplacementMicromapFeaturesNV,
    VkPhysicalDeviceDisplacementMicromapPropertiesNV,
    VkPhysicalDeviceDriverProperties,
    VkPhysicalDeviceDrmPropertiesEXT,
    VkPhysicalDeviceDynamicRenderingFeatures,
    VkPhysicalDeviceDynamicRenderingLocalReadFeaturesKHR,
    VkPhysicalDeviceDynamicRenderingUnusedAttachmentsFeaturesEXT,
    VkPhysicalDeviceExclusiveScissorFeaturesNV,
    VkPhysicalDeviceExtendedDynamicState2FeaturesEXT,
    VkPhysicalDeviceExtendedDynamicState3FeaturesEXT,
    VkPhysicalDeviceExtendedDynamicState3PropertiesEXT,
    VkPhysicalDeviceExtendedDynamicStateFeaturesEXT,
    VkPhysicalDeviceExtendedSparseAddressSpaceFeaturesNV,
    VkPhysicalDeviceExtendedSparseAddressSpacePropertiesNV,
    VkPhysicalDeviceExternalBufferInfo,
    VkPhysicalDeviceExternalFenceInfo,
    VkPhysicalDeviceExternalFormatResolveFeaturesANDROID,
    VkPhysicalDeviceExternalFormatResolvePropertiesANDROID,
    VkPhysicalDeviceExternalImageFormatInfo,
    VkPhysicalDeviceExternalMemoryHostPropertiesEXT,
    VkPhysicalDeviceExternalMemoryRDMAFeaturesNV,
    VkPhysicalDeviceExternalMemorySciBufFeaturesNV,
    VkPhysicalDeviceExternalMemoryScreenBufferFeaturesQNX,
    VkPhysicalDeviceExternalSciSync2FeaturesNV,
    VkPhysicalDeviceExternalSciSyncFeaturesNV,
    VkPhysicalDeviceExternalSemaphoreInfo,
    VkPhysicalDeviceFaultFeaturesEXT,
    VkPhysicalDeviceFeatures,
    VkPhysicalDeviceFeatures2,
    VkPhysicalDeviceFloatControlsProperties,
    VkPhysicalDeviceFragmentDensityMap2FeaturesEXT,
    VkPhysicalDeviceFragmentDensityMap2PropertiesEXT,
    VkPhysicalDeviceFragmentDensityMapFeaturesEXT,
    VkPhysicalDeviceFragmentDensityMapOffsetFeaturesQCOM,
    VkPhysicalDeviceFragmentDensityMapOffsetPropertiesQCOM,
    VkPhysicalDeviceFragmentDensityMapPropertiesEXT,
    VkPhysicalDeviceFragmentShaderBarycentricFeaturesKHR,
    VkPhysicalDeviceFragmentShaderBarycentricPropertiesKHR,
    VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT,
    VkPhysicalDeviceFragmentShadingRateEnumsFeaturesNV,
    VkPhysicalDeviceFragmentShadingRateEnumsPropertiesNV,
    VkPhysicalDeviceFragmentShadingRateFeaturesKHR,
    VkPhysicalDeviceFragmentShadingRateKHR,
    VkPhysicalDeviceFragmentShadingRatePropertiesKHR,
    VkPhysicalDeviceFrameBoundaryFeaturesEXT,
    VkPhysicalDeviceGlobalPriorityQueryFeaturesKHR,
    VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT,
    VkPhysicalDeviceGraphicsPipelineLibraryPropertiesEXT,
    VkPhysicalDeviceGroupProperties,
    VkPhysicalDeviceHostImageCopyFeaturesEXT,
    VkPhysicalDeviceHostImageCopyPropertiesEXT,
    VkPhysicalDeviceHostQueryResetFeatures,
    VkPhysicalDeviceIDProperties,
    VkPhysicalDeviceImage2DViewOf3DFeaturesEXT,
    VkPhysicalDeviceImageAlignmentControlFeaturesMESA,
    VkPhysicalDeviceImageAlignmentControlPropertiesMESA,
    VkPhysicalDeviceImageCompressionControlFeaturesEXT,
    VkPhysicalDeviceImageCompressionControlSwapchainFeaturesEXT,
    VkPhysicalDeviceImageDrmFormatModifierInfoEXT,
    VkPhysicalDeviceImageFormatInfo2,
    VkPhysicalDeviceImageProcessing2FeaturesQCOM,
    VkPhysicalDeviceImageProcessing2PropertiesQCOM,
    VkPhysicalDeviceImageProcessingFeaturesQCOM,
    VkPhysicalDeviceImageProcessingPropertiesQCOM,
    VkPhysicalDeviceImageRobustnessFeatures,
    VkPhysicalDeviceImageSlicedViewOf3DFeaturesEXT,
    VkPhysicalDeviceImageViewImageFormatInfoEXT,
    VkPhysicalDeviceImageViewMinLodFeaturesEXT,
    VkPhysicalDeviceImagelessFramebufferFeatures,
    VkPhysicalDeviceIndexTypeUint8FeaturesKHR,
    VkPhysicalDeviceInheritedViewportScissorFeaturesNV,
    VkPhysicalDeviceInlineUniformBlockFeatures,
    VkPhysicalDeviceInlineUniformBlockProperties,
    VkPhysicalDeviceInvocationMaskFeaturesHUAWEI,
    VkPhysicalDeviceLayeredDriverPropertiesMSFT,
    VkPhysicalDeviceLegacyDitheringFeaturesEXT,
    VkPhysicalDeviceLegacyVertexAttributesFeaturesEXT,
    VkPhysicalDeviceLegacyVertexAttributesPropertiesEXT,
    VkPhysicalDeviceLimits,
    VkPhysicalDeviceLineRasterizationFeaturesKHR,
    VkPhysicalDeviceLineRasterizationPropertiesKHR,
    VkPhysicalDeviceLinearColorAttachmentFeaturesNV,
    VkPhysicalDeviceMaintenance3Properties,
    VkPhysicalDeviceMaintenance4Features,
    VkPhysicalDeviceMaintenance4Properties,
    VkPhysicalDeviceMaintenance5FeaturesKHR,
    VkPhysicalDeviceMaintenance5PropertiesKHR,
    VkPhysicalDeviceMaintenance6FeaturesKHR,
    VkPhysicalDeviceMaintenance6PropertiesKHR,
    VkPhysicalDeviceMapMemoryPlacedFeaturesEXT,
    VkPhysicalDeviceMapMemoryPlacedPropertiesEXT,
    VkPhysicalDeviceMemoryBudgetPropertiesEXT,
    VkPhysicalDeviceMemoryDecompressionFeaturesNV,
    VkPhysicalDeviceMemoryDecompressionPropertiesNV,
    VkPhysicalDeviceMemoryPriorityFeaturesEXT,
    VkPhysicalDeviceMemoryProperties,
    VkPhysicalDeviceMemoryProperties2,
    VkPhysicalDeviceMeshShaderFeaturesEXT,
    VkPhysicalDeviceMeshShaderFeaturesNV,
    VkPhysicalDeviceMeshShaderPropertiesEXT,
    VkPhysicalDeviceMeshShaderPropertiesNV,
    VkPhysicalDeviceMultiDrawFeaturesEXT,
    VkPhysicalDeviceMultiDrawPropertiesEXT,
    VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT,
    VkPhysicalDeviceMultiviewFeatures,
    VkPhysicalDeviceMultiviewPerViewAttributesPropertiesNVX,
    VkPhysicalDeviceMultiviewPerViewRenderAreasFeaturesQCOM,
    VkPhysicalDeviceMultiviewPerViewViewportsFeaturesQCOM,
    VkPhysicalDeviceMultiviewProperties,
    VkPhysicalDeviceMutableDescriptorTypeFeaturesEXT,
    VkPhysicalDeviceNestedCommandBufferFeaturesEXT,
    VkPhysicalDeviceNestedCommandBufferPropertiesEXT,
    VkPhysicalDeviceNonSeamlessCubeMapFeaturesEXT,
    VkPhysicalDeviceOpacityMicromapFeaturesEXT,
    VkPhysicalDeviceOpacityMicromapPropertiesEXT,
    VkPhysicalDeviceOpticalFlowFeaturesNV,
    VkPhysicalDeviceOpticalFlowPropertiesNV,
    VkPhysicalDevicePCIBusInfoPropertiesEXT,
    VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT,
    VkPhysicalDevicePerStageDescriptorSetFeaturesNV,
    VkPhysicalDevicePerformanceQueryFeaturesKHR,
    VkPhysicalDevicePerformanceQueryPropertiesKHR,
    VkPhysicalDevicePipelineCreationCacheControlFeatures,
    VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR,
    VkPhysicalDevicePipelineLibraryGroupHandlesFeaturesEXT,
    VkPhysicalDevicePipelinePropertiesFeaturesEXT,
    VkPhysicalDevicePipelineProtectedAccessFeaturesEXT,
    VkPhysicalDevicePipelineRobustnessFeaturesEXT,
    VkPhysicalDevicePipelineRobustnessPropertiesEXT,
    VkPhysicalDevicePointClippingProperties,
    VkPhysicalDevicePortabilitySubsetFeaturesKHR,
    VkPhysicalDevicePortabilitySubsetPropertiesKHR,
    VkPhysicalDevicePresentBarrierFeaturesNV,
    VkPhysicalDevicePresentIdFeaturesKHR,
    VkPhysicalDevicePresentWaitFeaturesKHR,
    VkPhysicalDevicePresentationPropertiesANDROID,
    VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT,
    VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT,
    VkPhysicalDevicePrivateDataFeatures,
    VkPhysicalDeviceProperties,
    VkPhysicalDeviceProperties2,
    VkPhysicalDeviceProtectedMemoryFeatures,
    VkPhysicalDeviceProtectedMemoryProperties,
    VkPhysicalDeviceProvokingVertexFeaturesEXT,
    VkPhysicalDeviceProvokingVertexPropertiesEXT,
    VkPhysicalDevicePushDescriptorPropertiesKHR,
    VkPhysicalDeviceRGBA10X6FormatsFeaturesEXT,
    VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT,
    VkPhysicalDeviceRawAccessChainsFeaturesNV,
    VkPhysicalDeviceRayQueryFeaturesKHR,
    VkPhysicalDeviceRayTracingInvocationReorderFeaturesNV,
    VkPhysicalDeviceRayTracingInvocationReorderPropertiesNV,
    VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR,
    VkPhysicalDeviceRayTracingMotionBlurFeaturesNV,
    VkPhysicalDeviceRayTracingPipelineFeaturesKHR,
    VkPhysicalDeviceRayTracingPipelinePropertiesKHR,
    VkPhysicalDeviceRayTracingPositionFetchFeaturesKHR,
    VkPhysicalDeviceRayTracingPropertiesNV,
    VkPhysicalDeviceRayTracingValidationFeaturesNV,
    VkPhysicalDeviceRelaxedLineRasterizationFeaturesIMG,
    VkPhysicalDeviceRenderPassStripedFeaturesARM,
    VkPhysicalDeviceRenderPassStripedPropertiesARM,
    VkPhysicalDeviceRepresentativeFragmentTestFeaturesNV,
    VkPhysicalDeviceRobustness2FeaturesEXT,
    VkPhysicalDeviceRobustness2PropertiesEXT,
    VkPhysicalDeviceSampleLocationsPropertiesEXT,
    VkPhysicalDeviceSamplerFilterMinmaxProperties,
    VkPhysicalDeviceSamplerYcbcrConversionFeatures,
    VkPhysicalDeviceScalarBlockLayoutFeatures,
    VkPhysicalDeviceSchedulingControlsFeaturesARM,
    VkPhysicalDeviceSchedulingControlsPropertiesARM,
    VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures,
    VkPhysicalDeviceShaderAtomicFloat16VectorFeaturesNV,
    VkPhysicalDeviceShaderAtomicFloat2FeaturesEXT,
    VkPhysicalDeviceShaderAtomicFloatFeaturesEXT,
    VkPhysicalDeviceShaderAtomicInt64Features,
    VkPhysicalDeviceShaderClockFeaturesKHR,
    VkPhysicalDeviceShaderCoreBuiltinsFeaturesARM,
    VkPhysicalDeviceShaderCoreBuiltinsPropertiesARM,
    VkPhysicalDeviceShaderCoreProperties2AMD,
    VkPhysicalDeviceShaderCorePropertiesAMD,
    VkPhysicalDeviceShaderCorePropertiesARM,
    VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures,
    VkPhysicalDeviceShaderDrawParametersFeatures,
    VkPhysicalDeviceShaderEarlyAndLateFragmentTestsFeaturesAMD,
    VkPhysicalDeviceShaderEnqueueFeaturesAMDX,
    VkPhysicalDeviceShaderEnqueuePropertiesAMDX,
    VkPhysicalDeviceShaderExpectAssumeFeaturesKHR,
    VkPhysicalDeviceShaderFloat16Int8Features,
    VkPhysicalDeviceShaderFloatControls2FeaturesKHR,
    VkPhysicalDeviceShaderImageAtomicInt64FeaturesEXT,
    VkPhysicalDeviceShaderImageFootprintFeaturesNV,
    VkPhysicalDeviceShaderIntegerDotProductFeatures,
    VkPhysicalDeviceShaderIntegerDotProductProperties,
    VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL,
    VkPhysicalDeviceShaderMaximalReconvergenceFeaturesKHR,
    VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT,
    VkPhysicalDeviceShaderModuleIdentifierPropertiesEXT,
    VkPhysicalDeviceShaderObjectFeaturesEXT,
    VkPhysicalDeviceShaderObjectPropertiesEXT,
    VkPhysicalDeviceShaderQuadControlFeaturesKHR,
    VkPhysicalDeviceShaderRelaxedExtendedInstructionFeaturesKHR,
    VkPhysicalDeviceShaderReplicatedCompositesFeaturesEXT,
    VkPhysicalDeviceShaderSMBuiltinsFeaturesNV,
    VkPhysicalDeviceShaderSMBuiltinsPropertiesNV,
    VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures,
    VkPhysicalDeviceShaderSubgroupRotateFeaturesKHR,
    VkPhysicalDeviceShaderSubgroupUniformControlFlowFeaturesKHR,
    VkPhysicalDeviceShaderTerminateInvocationFeatures,
    VkPhysicalDeviceShaderTileImageFeaturesEXT,
    VkPhysicalDeviceShaderTileImagePropertiesEXT,
    VkPhysicalDeviceShadingRateImageFeaturesNV,
    VkPhysicalDeviceShadingRateImagePropertiesNV,
    VkPhysicalDeviceSparseImageFormatInfo2,
    VkPhysicalDeviceSparseProperties,
    VkPhysicalDeviceSubgroupProperties,
    VkPhysicalDeviceSubgroupSizeControlFeatures,
    VkPhysicalDeviceSubgroupSizeControlProperties,
    VkPhysicalDeviceSubpassMergeFeedbackFeaturesEXT,
    VkPhysicalDeviceSubpassShadingFeaturesHUAWEI,
    VkPhysicalDeviceSubpassShadingPropertiesHUAWEI,
    VkPhysicalDeviceSurfaceInfo2KHR,
    VkPhysicalDeviceSwapchainMaintenance1FeaturesEXT,
    VkPhysicalDeviceSynchronization2Features,
    VkPhysicalDeviceTexelBufferAlignmentFeaturesEXT,
    VkPhysicalDeviceTexelBufferAlignmentProperties,
    VkPhysicalDeviceTextureCompressionASTCHDRFeatures,
    VkPhysicalDeviceTilePropertiesFeaturesQCOM,
    VkPhysicalDeviceTimelineSemaphoreFeatures,
    VkPhysicalDeviceTimelineSemaphoreProperties,
    VkPhysicalDeviceToolProperties,
    VkPhysicalDeviceTransformFeedbackFeaturesEXT,
    VkPhysicalDeviceTransformFeedbackPropertiesEXT,
    VkPhysicalDeviceUniformBufferStandardLayoutFeatures,
    VkPhysicalDeviceVariablePointersFeatures,
    VkPhysicalDeviceVertexAttributeDivisorFeaturesKHR,
    VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT,
    VkPhysicalDeviceVertexAttributeDivisorPropertiesKHR,
    VkPhysicalDeviceVertexInputDynamicStateFeaturesEXT,
    VkPhysicalDeviceVideoEncodeQualityLevelInfoKHR,
    VkPhysicalDeviceVideoFormatInfoKHR,
    VkPhysicalDeviceVideoMaintenance1FeaturesKHR,
    VkPhysicalDeviceVulkan11Features,
    VkPhysicalDeviceVulkan11Properties,
    VkPhysicalDeviceVulkan12Features,
    VkPhysicalDeviceVulkan12Properties,
    VkPhysicalDeviceVulkan13Features,
    VkPhysicalDeviceVulkan13Properties,
    VkPhysicalDeviceVulkanMemoryModelFeatures,
    VkPhysicalDeviceVulkanSC10Features,
    VkPhysicalDeviceVulkanSC10Properties,
    VkPhysicalDeviceWorkgroupMemoryExplicitLayoutFeaturesKHR,
    VkPhysicalDeviceYcbcr2Plane444FormatsFeaturesEXT,
    VkPhysicalDeviceYcbcrDegammaFeaturesQCOM,
    VkPhysicalDeviceYcbcrImageArraysFeaturesEXT,
    VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures,
    VkPipelineCacheCreateInfo,
    VkPipelineCacheHeaderVersionOne,
    VkPipelineCacheHeaderVersionSafetyCriticalOne,
    VkPipelineCacheSafetyCriticalIndexEntry,
    VkPipelineCacheStageValidationIndexEntry,
    VkPipelineColorBlendAdvancedStateCreateInfoEXT,
    VkPipelineColorBlendAttachmentState,
    VkPipelineColorBlendStateCreateInfo,
    VkPipelineColorWriteCreateInfoEXT,
    VkPipelineCompilerControlCreateInfoAMD,
    VkPipelineCoverageModulationStateCreateInfoNV,
    VkPipelineCoverageReductionStateCreateInfoNV,
    VkPipelineCoverageToColorStateCreateInfoNV,
    VkPipelineCreateFlags2CreateInfoKHR,
    VkPipelineCreationFeedback,
    VkPipelineCreationFeedbackCreateInfo,
    VkPipelineDepthStencilStateCreateInfo,
    VkPipelineDiscardRectangleStateCreateInfoEXT,
    VkPipelineDynamicStateCreateInfo,
    VkPipelineExecutableInfoKHR,
    VkPipelineExecutableInternalRepresentationKHR,
    VkPipelineExecutablePropertiesKHR,
    VkPipelineExecutableStatisticKHR,
    VkPipelineExecutableStatisticValueKHR,
    VkPipelineFragmentShadingRateEnumStateCreateInfoNV,
    VkPipelineFragmentShadingRateStateCreateInfoKHR,
    VkPipelineIndirectDeviceAddressInfoNV,
    VkPipelineInfoKHR,
    VkPipelineInputAssemblyStateCreateInfo,
    VkPipelineLayoutCreateInfo,
    VkPipelineLibraryCreateInfoKHR,
    VkPipelineMultisampleStateCreateInfo,
    VkPipelineOfflineCreateInfo,
    VkPipelinePoolSize,
    VkPipelinePropertiesIdentifierEXT,
    VkPipelineRasterizationConservativeStateCreateInfoEXT,
    VkPipelineRasterizationDepthClipStateCreateInfoEXT,
    VkPipelineRasterizationLineStateCreateInfoKHR,
    VkPipelineRasterizationProvokingVertexStateCreateInfoEXT,
    VkPipelineRasterizationStateCreateInfo,
    VkPipelineRasterizationStateRasterizationOrderAMD,
    VkPipelineRasterizationStateStreamCreateInfoEXT,
    VkPipelineRenderingCreateInfo,
    VkPipelineRepresentativeFragmentTestStateCreateInfoNV,
    VkPipelineRobustnessCreateInfoEXT,
    VkPipelineSampleLocationsStateCreateInfoEXT,
    VkPipelineShaderStageCreateInfo,
    VkPipelineShaderStageModuleIdentifierCreateInfoEXT,
    VkPipelineShaderStageNodeCreateInfoAMDX,
    VkPipelineShaderStageRequiredSubgroupSizeCreateInfo,
    VkPipelineTessellationDomainOriginStateCreateInfo,
    VkPipelineTessellationStateCreateInfo,
    VkPipelineVertexInputDivisorStateCreateInfoKHR,
    VkPipelineVertexInputStateCreateInfo,
    VkPipelineViewportCoarseSampleOrderStateCreateInfoNV,
    VkPipelineViewportDepthClipControlCreateInfoEXT,
    VkPipelineViewportExclusiveScissorStateCreateInfoNV,
    VkPipelineViewportShadingRateImageStateCreateInfoNV,
    VkPipelineViewportStateCreateInfo,
    VkPipelineViewportSwizzleStateCreateInfoNV,
    VkPipelineViewportWScalingStateCreateInfoNV,
    VkPresentFrameTokenGGP,
    VkPresentIdKHR,
    VkPresentInfoKHR,
    VkPresentRegionKHR,
    VkPresentRegionsKHR,
    VkPresentTimeGOOGLE,
    VkPresentTimesInfoGOOGLE,
    VkPrivateDataSlotCreateInfo,
    VkProtectedSubmitInfo,
    VkPushConstantRange,
    VkPushConstantsInfoKHR,
    VkPushDescriptorSetInfoKHR,
    VkPushDescriptorSetWithTemplateInfoKHR,
    VkQueryLowLatencySupportNV,
    VkQueryPoolCreateInfo,
    VkQueryPoolPerformanceCreateInfoKHR,
    VkQueryPoolPerformanceQueryCreateInfoINTEL,
    VkQueryPoolVideoEncodeFeedbackCreateInfoKHR,
    VkQueueFamilyCheckpointProperties2NV,
    VkQueueFamilyCheckpointPropertiesNV,
    VkQueueFamilyGlobalPriorityPropertiesKHR,
    VkQueueFamilyProperties,
    VkQueueFamilyProperties2,
    VkQueueFamilyQueryResultStatusPropertiesKHR,
    VkQueueFamilyVideoPropertiesKHR,
    VkRayTracingPipelineCreateInfoKHR,
    VkRayTracingPipelineCreateInfoNV,
    VkRayTracingPipelineInterfaceCreateInfoKHR,
    VkRayTracingShaderGroupCreateInfoKHR,
    VkRayTracingShaderGroupCreateInfoNV,
    VkRect2D,
    VkRectLayerKHR,
    VkRefreshCycleDurationGOOGLE,
    VkRefreshObjectKHR,
    VkRefreshObjectListKHR,
    VkReleaseSwapchainImagesInfoEXT,
    VkRenderPassAttachmentBeginInfo,
    VkRenderPassBeginInfo,
    VkRenderPassCreateInfo,
    VkRenderPassCreateInfo2,
    VkRenderPassCreationControlEXT,
    VkRenderPassCreationFeedbackCreateInfoEXT,
    VkRenderPassCreationFeedbackInfoEXT,
    VkRenderPassFragmentDensityMapCreateInfoEXT,
    VkRenderPassInputAttachmentAspectCreateInfo,
    VkRenderPassMultiviewCreateInfo,
    VkRenderPassSampleLocationsBeginInfoEXT,
    VkRenderPassStripeBeginInfoARM,
    VkRenderPassStripeInfoARM,
    VkRenderPassStripeSubmitInfoARM,
    VkRenderPassSubpassFeedbackCreateInfoEXT,
    VkRenderPassSubpassFeedbackInfoEXT,
    VkRenderPassTransformBeginInfoQCOM,
    VkRenderingAreaInfoKHR,
    VkRenderingAttachmentInfo,
    VkRenderingAttachmentLocationInfoKHR,
    VkRenderingFragmentDensityMapAttachmentInfoEXT,
    VkRenderingFragmentShadingRateAttachmentInfoKHR,
    VkRenderingInfo,
    VkRenderingInputAttachmentIndexInfoKHR,
    VkResolveImageInfo2,
    VkSRTDataNV,
    VkSampleLocationEXT,
    VkSampleLocationsInfoEXT,
    VkSamplerBlockMatchWindowCreateInfoQCOM,
    VkSamplerBorderColorComponentMappingCreateInfoEXT,
    VkSamplerCaptureDescriptorDataInfoEXT,
    VkSamplerCreateInfo,
    VkSamplerCubicWeightsCreateInfoQCOM,
    VkSamplerCustomBorderColorCreateInfoEXT,
    VkSamplerReductionModeCreateInfo,
    VkSamplerYcbcrConversionCreateInfo,
    VkSamplerYcbcrConversionImageFormatProperties,
    VkSamplerYcbcrConversionInfo,
    VkSamplerYcbcrConversionYcbcrDegammaCreateInfoQCOM,
    VkSciSyncAttributesInfoNV,
    VkScreenBufferFormatPropertiesQNX,
    VkScreenBufferPropertiesQNX,
    VkScreenSurfaceCreateInfoQNX,
    VkSemaphoreCreateInfo,
    VkSemaphoreGetFdInfoKHR,
    VkSemaphoreGetSciSyncInfoNV,
    VkSemaphoreGetWin32HandleInfoKHR,
    VkSemaphoreGetZirconHandleInfoFUCHSIA,
    VkSemaphoreSciSyncCreateInfoNV,
    VkSemaphoreSciSyncPoolCreateInfoNV,
    VkSemaphoreSignalInfo,
    VkSemaphoreSubmitInfo,
    VkSemaphoreTypeCreateInfo,
    VkSemaphoreWaitInfo,
    VkSetDescriptorBufferOffsetsInfoEXT,
    VkSetLatencyMarkerInfoNV,
    VkSetStateFlagsIndirectCommandNV,
    VkShaderCreateInfoEXT,
    VkShaderModuleCreateInfo,
    VkShaderModuleIdentifierEXT,
    VkShaderModuleValidationCacheCreateInfoEXT,
    VkShaderResourceUsageAMD,
    VkShaderStatisticsInfoAMD,
    VkShadingRatePaletteNV,
    VkSharedPresentSurfaceCapabilitiesKHR,
    VkSparseBufferMemoryBindInfo,
    VkSparseImageFormatProperties,
    VkSparseImageFormatProperties2,
    VkSparseImageMemoryBind,
    VkSparseImageMemoryBindInfo,
    VkSparseImageMemoryRequirements,
    VkSparseImageMemoryRequirements2,
    VkSparseImageOpaqueMemoryBindInfo,
    VkSparseMemoryBind,
    VkSpecializationInfo,
    VkSpecializationMapEntry,
    VkStencilOpState,
    VkStreamDescriptorSurfaceCreateInfoGGP,
    VkStridedDeviceAddressRegionKHR,
    VkSubmitInfo,
    VkSubmitInfo2,
    VkSubpassBeginInfo,
    VkSubpassDependency,
    VkSubpassDependency2,
    VkSubpassDescription,
    VkSubpassDescription2,
    VkSubpassDescriptionDepthStencilResolve,
    VkSubpassEndInfo,
    VkSubpassFragmentDensityMapOffsetEndInfoQCOM,
    VkSubpassResolvePerformanceQueryEXT,
    VkSubpassSampleLocationsEXT,
    VkSubpassShadingPipelineCreateInfoHUAWEI,
    VkSubresourceHostMemcpySizeEXT,
    VkSubresourceLayout,
    VkSubresourceLayout2KHR,
    VkSurfaceCapabilities2EXT,
    VkSurfaceCapabilities2KHR,
    VkSurfaceCapabilitiesFullScreenExclusiveEXT,
    VkSurfaceCapabilitiesKHR,
    VkSurfaceCapabilitiesPresentBarrierNV,
    VkSurfaceFormat2KHR,
    VkSurfaceFormatKHR,
    VkSurfaceFullScreenExclusiveInfoEXT,
    VkSurfaceFullScreenExclusiveWin32InfoEXT,
    VkSurfacePresentModeCompatibilityEXT,
    VkSurfacePresentModeEXT,
    VkSurfacePresentScalingCapabilitiesEXT,
    VkSurfaceProtectedCapabilitiesKHR,
    VkSwapchainCounterCreateInfoEXT,
    VkSwapchainCreateInfoKHR,
    VkSwapchainDisplayNativeHdrCreateInfoAMD,
    VkSwapchainImageCreateInfoANDROID,
    VkSwapchainLatencyCreateInfoNV,
    VkSwapchainPresentBarrierCreateInfoNV,
    VkSwapchainPresentFenceInfoEXT,
    VkSwapchainPresentModeInfoEXT,
    VkSwapchainPresentModesCreateInfoEXT,
    VkSwapchainPresentScalingCreateInfoEXT,
    VkSysmemColorSpaceFUCHSIA,
    VkTextureLODGatherFormatPropertiesAMD,
    VkTilePropertiesQCOM,
    VkTimelineSemaphoreSubmitInfo,
    VkTraceRaysIndirectCommand2KHR,
    VkTraceRaysIndirectCommandKHR,
    VkTransformMatrixKHR,
    VkValidationCacheCreateInfoEXT,
    VkValidationFeaturesEXT,
    VkValidationFlagsEXT,
    VkVertexInputAttributeDescription,
    VkVertexInputAttributeDescription2EXT,
    VkVertexInputBindingDescription,
    VkVertexInputBindingDescription2EXT,
    VkVertexInputBindingDivisorDescriptionKHR,
    VkViSurfaceCreateInfoNN,
    VkVideoBeginCodingInfoKHR,
    VkVideoCapabilitiesKHR,
    VkVideoCodingControlInfoKHR,
    VkVideoDecodeAV1CapabilitiesKHR,
    VkVideoDecodeAV1DpbSlotInfoKHR,
    VkVideoDecodeAV1PictureInfoKHR,
    VkVideoDecodeAV1ProfileInfoKHR,
    VkVideoDecodeAV1SessionParametersCreateInfoKHR,
    VkVideoDecodeCapabilitiesKHR,
    VkVideoDecodeH264CapabilitiesKHR,
    VkVideoDecodeH264DpbSlotInfoKHR,
    VkVideoDecodeH264PictureInfoKHR,
    VkVideoDecodeH264ProfileInfoKHR,
    VkVideoDecodeH264SessionParametersAddInfoKHR,
    VkVideoDecodeH264SessionParametersCreateInfoKHR,
    VkVideoDecodeH265CapabilitiesKHR,
    VkVideoDecodeH265DpbSlotInfoKHR,
    VkVideoDecodeH265PictureInfoKHR,
    VkVideoDecodeH265ProfileInfoKHR,
    VkVideoDecodeH265SessionParametersAddInfoKHR,
    VkVideoDecodeH265SessionParametersCreateInfoKHR,
    VkVideoDecodeInfoKHR,
    VkVideoDecodeUsageInfoKHR,
    VkVideoEncodeCapabilitiesKHR,
    VkVideoEncodeH264CapabilitiesKHR,
    VkVideoEncodeH264DpbSlotInfoKHR,
    VkVideoEncodeH264FrameSizeKHR,
    VkVideoEncodeH264GopRemainingFrameInfoKHR,
    VkVideoEncodeH264NaluSliceInfoKHR,
    VkVideoEncodeH264PictureInfoKHR,
    VkVideoEncodeH264ProfileInfoKHR,
    VkVideoEncodeH264QpKHR,
    VkVideoEncodeH264QualityLevelPropertiesKHR,
    VkVideoEncodeH264RateControlInfoKHR,
    VkVideoEncodeH264RateControlLayerInfoKHR,
    VkVideoEncodeH264SessionCreateInfoKHR,
    VkVideoEncodeH264SessionParametersAddInfoKHR,
    VkVideoEncodeH264SessionParametersCreateInfoKHR,
    VkVideoEncodeH264SessionParametersFeedbackInfoKHR,
    VkVideoEncodeH264SessionParametersGetInfoKHR,
    VkVideoEncodeH265CapabilitiesKHR,
    VkVideoEncodeH265DpbSlotInfoKHR,
    VkVideoEncodeH265FrameSizeKHR,
    VkVideoEncodeH265GopRemainingFrameInfoKHR,
    VkVideoEncodeH265NaluSliceSegmentInfoKHR,
    VkVideoEncodeH265PictureInfoKHR,
    VkVideoEncodeH265ProfileInfoKHR,
    VkVideoEncodeH265QpKHR,
    VkVideoEncodeH265QualityLevelPropertiesKHR,
    VkVideoEncodeH265RateControlInfoKHR,
    VkVideoEncodeH265RateControlLayerInfoKHR,
    VkVideoEncodeH265SessionCreateInfoKHR,
    VkVideoEncodeH265SessionParametersAddInfoKHR,
    VkVideoEncodeH265SessionParametersCreateInfoKHR,
    VkVideoEncodeH265SessionParametersFeedbackInfoKHR,
    VkVideoEncodeH265SessionParametersGetInfoKHR,
    VkVideoEncodeInfoKHR,
    VkVideoEncodeQualityLevelInfoKHR,
    VkVideoEncodeQualityLevelPropertiesKHR,
    VkVideoEncodeRateControlInfoKHR,
    VkVideoEncodeRateControlLayerInfoKHR,
    VkVideoEncodeSessionParametersFeedbackInfoKHR,
    VkVideoEncodeSessionParametersGetInfoKHR,
    VkVideoEncodeUsageInfoKHR,
    VkVideoEndCodingInfoKHR,
    VkVideoFormatPropertiesKHR,
    VkVideoInlineQueryInfoKHR,
    VkVideoPictureResourceInfoKHR,
    VkVideoProfileInfoKHR,
    VkVideoProfileListInfoKHR,
    VkVideoReferenceSlotInfoKHR,
    VkVideoSessionCreateInfoKHR,
    VkVideoSessionMemoryRequirementsKHR,
    VkVideoSessionParametersCreateInfoKHR,
    VkVideoSessionParametersUpdateInfoKHR,
    VkViewport,
    VkViewportSwizzleNV,
    VkViewportWScalingNV,
    VkWaylandSurfaceCreateInfoKHR,
    VkWin32KeyedMutexAcquireReleaseInfoKHR,
    VkWin32KeyedMutexAcquireReleaseInfoNV,
    VkWin32SurfaceCreateInfoKHR,
    VkWriteDescriptorSet,
    VkWriteDescriptorSetAccelerationStructureKHR,
    VkWriteDescriptorSetAccelerationStructureNV,
    VkWriteDescriptorSetInlineUniformBlock,
    VkXYColorEXT,
    VkXcbSurfaceCreateInfoKHR,
    VkXlibSurfaceCreateInfoKHR,
)

VkAabbPositionsNV = VkAabbPositionsKHR
VkAccelerationStructureInstanceNV = VkAccelerationStructureInstanceKHR
VkAttachmentDescription2KHR = VkAttachmentDescription2
VkAttachmentDescriptionStencilLayoutKHR = VkAttachmentDescriptionStencilLayout
VkAttachmentReference2KHR = VkAttachmentReference2
VkAttachmentReferenceStencilLayoutKHR = VkAttachmentReferenceStencilLayout
VkAttachmentSampleCountInfoNV = VkAttachmentSampleCountInfoAMD
VkBindBufferMemoryDeviceGroupInfoKHR = VkBindBufferMemoryDeviceGroupInfo
VkBindBufferMemoryInfoKHR = VkBindBufferMemoryInfo
VkBindImageMemoryDeviceGroupInfoKHR = VkBindImageMemoryDeviceGroupInfo
VkBindImageMemoryInfoKHR = VkBindImageMemoryInfo
VkBindImagePlaneMemoryInfoKHR = VkBindImagePlaneMemoryInfo
VkBlitImageInfo2KHR = VkBlitImageInfo2
VkBufferCopy2KHR = VkBufferCopy2
VkBufferDeviceAddressInfoEXT = VkBufferDeviceAddressInfo
VkBufferDeviceAddressInfoKHR = VkBufferDeviceAddressInfo
VkBufferImageCopy2KHR = VkBufferImageCopy2
VkBufferMemoryBarrier2KHR = VkBufferMemoryBarrier2
VkBufferMemoryRequirementsInfo2KHR = VkBufferMemoryRequirementsInfo2
VkBufferOpaqueCaptureAddressCreateInfoKHR = VkBufferOpaqueCaptureAddressCreateInfo
VkCalibratedTimestampInfoEXT = VkCalibratedTimestampInfoKHR
VkCommandBufferInheritanceRenderingInfoKHR = VkCommandBufferInheritanceRenderingInfo
VkCommandBufferSubmitInfoKHR = VkCommandBufferSubmitInfo
VkConformanceVersionKHR = VkConformanceVersion
VkCopyBufferInfo2KHR = VkCopyBufferInfo2
VkCopyBufferToImageInfo2KHR = VkCopyBufferToImageInfo2
VkCopyImageInfo2KHR = VkCopyImageInfo2
VkCopyImageToBufferInfo2KHR = VkCopyImageToBufferInfo2
VkDependencyInfoKHR = VkDependencyInfo
VkDescriptorPoolInlineUniformBlockCreateInfoEXT = VkDescriptorPoolInlineUniformBlockCreateInfo
VkDescriptorSetLayoutBindingFlagsCreateInfoEXT = VkDescriptorSetLayoutBindingFlagsCreateInfo
VkDescriptorSetLayoutSupportKHR = VkDescriptorSetLayoutSupport
VkDescriptorSetVariableDescriptorCountAllocateInfoEXT = VkDescriptorSetVariableDescriptorCountAllocateInfo
VkDescriptorSetVariableDescriptorCountLayoutSupportEXT = VkDescriptorSetVariableDescriptorCountLayoutSupport
VkDescriptorUpdateTemplateCreateInfoKHR = VkDescriptorUpdateTemplateCreateInfo
VkDescriptorUpdateTemplateEntryKHR = VkDescriptorUpdateTemplateEntry
VkDeviceBufferMemoryRequirementsKHR = VkDeviceBufferMemoryRequirements
VkDeviceGroupBindSparseInfoKHR = VkDeviceGroupBindSparseInfo
VkDeviceGroupCommandBufferBeginInfoKHR = VkDeviceGroupCommandBufferBeginInfo
VkDeviceGroupDeviceCreateInfoKHR = VkDeviceGroupDeviceCreateInfo
VkDeviceGroupRenderPassBeginInfoKHR = VkDeviceGroupRenderPassBeginInfo
VkDeviceGroupSubmitInfoKHR = VkDeviceGroupSubmitInfo
VkDeviceImageMemoryRequirementsKHR = VkDeviceImageMemoryRequirements
VkDeviceMemoryOpaqueCaptureAddressInfoKHR = VkDeviceMemoryOpaqueCaptureAddressInfo
VkDevicePrivateDataCreateInfoEXT = VkDevicePrivateDataCreateInfo
VkDeviceQueueGlobalPriorityCreateInfoEXT = VkDeviceQueueGlobalPriorityCreateInfoKHR
VkExportFenceCreateInfoKHR = VkExportFenceCreateInfo
VkExportMemoryAllocateInfoKHR = VkExportMemoryAllocateInfo
VkExportSemaphoreCreateInfoKHR = VkExportSemaphoreCreateInfo
VkExternalBufferPropertiesKHR = VkExternalBufferProperties
VkExternalFencePropertiesKHR = VkExternalFenceProperties
VkExternalImageFormatPropertiesKHR = VkExternalImageFormatProperties
VkExternalMemoryBufferCreateInfoKHR = VkExternalMemoryBufferCreateInfo
VkExternalMemoryImageCreateInfoKHR = VkExternalMemoryImageCreateInfo
VkExternalMemoryPropertiesKHR = VkExternalMemoryProperties
VkExternalSemaphorePropertiesKHR = VkExternalSemaphoreProperties
VkFormatProperties2KHR = VkFormatProperties2
VkFormatProperties3KHR = VkFormatProperties3
VkFramebufferAttachmentImageInfoKHR = VkFramebufferAttachmentImageInfo
VkFramebufferAttachmentsCreateInfoKHR = VkFramebufferAttachmentsCreateInfo
VkImageBlit2KHR = VkImageBlit2
VkImageCopy2KHR = VkImageCopy2
VkImageFormatListCreateInfoKHR = VkImageFormatListCreateInfo
VkImageFormatProperties2KHR = VkImageFormatProperties2
VkImageMemoryBarrier2KHR = VkImageMemoryBarrier2
VkImageMemoryRequirementsInfo2KHR = VkImageMemoryRequirementsInfo2
VkImagePlaneMemoryRequirementsInfoKHR = VkImagePlaneMemoryRequirementsInfo
VkImageResolve2KHR = VkImageResolve2
VkImageSparseMemoryRequirementsInfo2KHR = VkImageSparseMemoryRequirementsInfo2
VkImageStencilUsageCreateInfoEXT = VkImageStencilUsageCreateInfo
VkImageSubresource2EXT = VkImageSubresource2KHR
VkImageViewUsageCreateInfoKHR = VkImageViewUsageCreateInfo
VkInputAttachmentAspectReferenceKHR = VkInputAttachmentAspectReference
VkMemoryAllocateFlagsInfoKHR = VkMemoryAllocateFlagsInfo
VkMemoryBarrier2KHR = VkMemoryBarrier2
VkMemoryDedicatedAllocateInfoKHR = VkMemoryDedicatedAllocateInfo
VkMemoryDedicatedRequirementsKHR = VkMemoryDedicatedRequirements
VkMemoryOpaqueCaptureAddressAllocateInfoKHR = VkMemoryOpaqueCaptureAddressAllocateInfo
VkMemoryRequirements2KHR = VkMemoryRequirements2
VkMutableDescriptorTypeCreateInfoVALVE = VkMutableDescriptorTypeCreateInfoEXT
VkMutableDescriptorTypeListVALVE = VkMutableDescriptorTypeListEXT
VkPhysicalDevice16BitStorageFeaturesKHR = VkPhysicalDevice16BitStorageFeatures
VkPhysicalDevice8BitStorageFeaturesKHR = VkPhysicalDevice8BitStorageFeatures
VkPhysicalDeviceBufferAddressFeaturesEXT = VkPhysicalDeviceBufferDeviceAddressFeaturesEXT
VkPhysicalDeviceBufferDeviceAddressFeaturesKHR = VkPhysicalDeviceBufferDeviceAddressFeatures
VkPhysicalDeviceDepthStencilResolvePropertiesKHR = VkPhysicalDeviceDepthStencilResolveProperties
VkPhysicalDeviceDescriptorIndexingFeaturesEXT = VkPhysicalDeviceDescriptorIndexingFeatures
VkPhysicalDeviceDescriptorIndexingPropertiesEXT = VkPhysicalDeviceDescriptorIndexingProperties
VkPhysicalDeviceDriverPropertiesKHR = VkPhysicalDeviceDriverProperties
VkPhysicalDeviceDynamicRenderingFeaturesKHR = VkPhysicalDeviceDynamicRenderingFeatures
VkPhysicalDeviceExternalBufferInfoKHR = VkPhysicalDeviceExternalBufferInfo
VkPhysicalDeviceExternalFenceInfoKHR = VkPhysicalDeviceExternalFenceInfo
VkPhysicalDeviceExternalImageFormatInfoKHR = VkPhysicalDeviceExternalImageFormatInfo
VkPhysicalDeviceExternalSciBufFeaturesNV = VkPhysicalDeviceExternalMemorySciBufFeaturesNV
VkPhysicalDeviceExternalSemaphoreInfoKHR = VkPhysicalDeviceExternalSemaphoreInfo
VkPhysicalDeviceFeatures2KHR = VkPhysicalDeviceFeatures2
VkPhysicalDeviceFloat16Int8FeaturesKHR = VkPhysicalDeviceShaderFloat16Int8Features
VkPhysicalDeviceFloatControlsPropertiesKHR = VkPhysicalDeviceFloatControlsProperties
VkPhysicalDeviceFragmentShaderBarycentricFeaturesNV = VkPhysicalDeviceFragmentShaderBarycentricFeaturesKHR
VkPhysicalDeviceGlobalPriorityQueryFeaturesEXT = VkPhysicalDeviceGlobalPriorityQueryFeaturesKHR
VkPhysicalDeviceGroupPropertiesKHR = VkPhysicalDeviceGroupProperties
VkPhysicalDeviceHostQueryResetFeaturesEXT = VkPhysicalDeviceHostQueryResetFeatures
VkPhysicalDeviceIDPropertiesKHR = VkPhysicalDeviceIDProperties
VkPhysicalDeviceImageFormatInfo2KHR = VkPhysicalDeviceImageFormatInfo2
VkPhysicalDeviceImageRobustnessFeaturesEXT = VkPhysicalDeviceImageRobustnessFeatures
VkPhysicalDeviceImagelessFramebufferFeaturesKHR = VkPhysicalDeviceImagelessFramebufferFeatures
VkPhysicalDeviceIndexTypeUint8FeaturesEXT = VkPhysicalDeviceIndexTypeUint8FeaturesKHR
VkPhysicalDeviceInlineUniformBlockFeaturesEXT = VkPhysicalDeviceInlineUniformBlockFeatures
VkPhysicalDeviceInlineUniformBlockPropertiesEXT = VkPhysicalDeviceInlineUniformBlockProperties
VkPhysicalDeviceLineRasterizationFeaturesEXT = VkPhysicalDeviceLineRasterizationFeaturesKHR
VkPhysicalDeviceLineRasterizationPropertiesEXT = VkPhysicalDeviceLineRasterizationPropertiesKHR
VkPhysicalDeviceMaintenance3PropertiesKHR = VkPhysicalDeviceMaintenance3Properties
VkPhysicalDeviceMaintenance4FeaturesKHR = VkPhysicalDeviceMaintenance4Features
VkPhysicalDeviceMaintenance4PropertiesKHR = VkPhysicalDeviceMaintenance4Properties
VkPhysicalDeviceMemoryProperties2KHR = VkPhysicalDeviceMemoryProperties2
VkPhysicalDeviceMultiviewFeaturesKHR = VkPhysicalDeviceMultiviewFeatures
VkPhysicalDeviceMultiviewPropertiesKHR = VkPhysicalDeviceMultiviewProperties
VkPhysicalDeviceMutableDescriptorTypeFeaturesVALVE = VkPhysicalDeviceMutableDescriptorTypeFeaturesEXT
VkPhysicalDevicePipelineCreationCacheControlFeaturesEXT = VkPhysicalDevicePipelineCreationCacheControlFeatures
VkPhysicalDevicePointClippingPropertiesKHR = VkPhysicalDevicePointClippingProperties
VkPhysicalDevicePrivateDataFeaturesEXT = VkPhysicalDevicePrivateDataFeatures
VkPhysicalDeviceProperties2KHR = VkPhysicalDeviceProperties2
VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesARM = VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT
VkPhysicalDeviceSamplerFilterMinmaxPropertiesEXT = VkPhysicalDeviceSamplerFilterMinmaxProperties
VkPhysicalDeviceSamplerYcbcrConversionFeaturesKHR = VkPhysicalDeviceSamplerYcbcrConversionFeatures
VkPhysicalDeviceScalarBlockLayoutFeaturesEXT = VkPhysicalDeviceScalarBlockLayoutFeatures
VkPhysicalDeviceSeparateDepthStencilLayoutsFeaturesKHR = VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures
VkPhysicalDeviceShaderAtomicInt64FeaturesKHR = VkPhysicalDeviceShaderAtomicInt64Features
VkPhysicalDeviceShaderDemoteToHelperInvocationFeaturesEXT = VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures
VkPhysicalDeviceShaderDrawParameterFeatures = VkPhysicalDeviceShaderDrawParametersFeatures
VkPhysicalDeviceShaderFloat16Int8FeaturesKHR = VkPhysicalDeviceShaderFloat16Int8Features
VkPhysicalDeviceShaderIntegerDotProductFeaturesKHR = VkPhysicalDeviceShaderIntegerDotProductFeatures
VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR = VkPhysicalDeviceShaderIntegerDotProductProperties
VkPhysicalDeviceShaderSubgroupExtendedTypesFeaturesKHR = VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures
VkPhysicalDeviceShaderTerminateInvocationFeaturesKHR = VkPhysicalDeviceShaderTerminateInvocationFeatures
VkPhysicalDeviceSparseImageFormatInfo2KHR = VkPhysicalDeviceSparseImageFormatInfo2
VkPhysicalDeviceSubgroupSizeControlFeaturesEXT = VkPhysicalDeviceSubgroupSizeControlFeatures
VkPhysicalDeviceSubgroupSizeControlPropertiesEXT = VkPhysicalDeviceSubgroupSizeControlProperties
VkPhysicalDeviceSynchronization2FeaturesKHR = VkPhysicalDeviceSynchronization2Features
VkPhysicalDeviceTexelBufferAlignmentPropertiesEXT = VkPhysicalDeviceTexelBufferAlignmentProperties
VkPhysicalDeviceTextureCompressionASTCHDRFeaturesEXT = VkPhysicalDeviceTextureCompressionASTCHDRFeatures
VkPhysicalDeviceTimelineSemaphoreFeaturesKHR = VkPhysicalDeviceTimelineSemaphoreFeatures
VkPhysicalDeviceTimelineSemaphorePropertiesKHR = VkPhysicalDeviceTimelineSemaphoreProperties
VkPhysicalDeviceToolPropertiesEXT = VkPhysicalDeviceToolProperties
VkPhysicalDeviceUniformBufferStandardLayoutFeaturesKHR = VkPhysicalDeviceUniformBufferStandardLayoutFeatures
VkPhysicalDeviceVariablePointerFeatures = VkPhysicalDeviceVariablePointersFeatures
VkPhysicalDeviceVariablePointerFeaturesKHR = VkPhysicalDeviceVariablePointersFeatures
VkPhysicalDeviceVariablePointersFeaturesKHR = VkPhysicalDeviceVariablePointersFeatures
VkPhysicalDeviceVertexAttributeDivisorFeaturesEXT = VkPhysicalDeviceVertexAttributeDivisorFeaturesKHR
VkPhysicalDeviceVulkanMemoryModelFeaturesKHR = VkPhysicalDeviceVulkanMemoryModelFeatures
VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeaturesKHR = VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures
VkPipelineCreationFeedbackCreateInfoEXT = VkPipelineCreationFeedbackCreateInfo
VkPipelineCreationFeedbackEXT = VkPipelineCreationFeedback
VkPipelineInfoEXT = VkPipelineInfoKHR
VkPipelineRasterizationLineStateCreateInfoEXT = VkPipelineRasterizationLineStateCreateInfoKHR
VkPipelineRenderingCreateInfoKHR = VkPipelineRenderingCreateInfo
VkPipelineShaderStageRequiredSubgroupSizeCreateInfoEXT = VkPipelineShaderStageRequiredSubgroupSizeCreateInfo
VkPipelineTessellationDomainOriginStateCreateInfoKHR = VkPipelineTessellationDomainOriginStateCreateInfo
VkPipelineVertexInputDivisorStateCreateInfoEXT = VkPipelineVertexInputDivisorStateCreateInfoKHR
VkPrivateDataSlotCreateInfoEXT = VkPrivateDataSlotCreateInfo
VkQueryPoolCreateInfoINTEL = VkQueryPoolPerformanceQueryCreateInfoINTEL
VkQueueFamilyGlobalPriorityPropertiesEXT = VkQueueFamilyGlobalPriorityPropertiesKHR
VkQueueFamilyProperties2KHR = VkQueueFamilyProperties2
VkRenderPassAttachmentBeginInfoKHR = VkRenderPassAttachmentBeginInfo
VkRenderPassCreateInfo2KHR = VkRenderPassCreateInfo2
VkRenderPassInputAttachmentAspectCreateInfoKHR = VkRenderPassInputAttachmentAspectCreateInfo
VkRenderPassMultiviewCreateInfoKHR = VkRenderPassMultiviewCreateInfo
VkRenderingAttachmentInfoKHR = VkRenderingAttachmentInfo
VkRenderingInfoKHR = VkRenderingInfo
VkResolveImageInfo2KHR = VkResolveImageInfo2
VkSamplerReductionModeCreateInfoEXT = VkSamplerReductionModeCreateInfo
VkSamplerYcbcrConversionCreateInfoKHR = VkSamplerYcbcrConversionCreateInfo
VkSamplerYcbcrConversionImageFormatPropertiesKHR = VkSamplerYcbcrConversionImageFormatProperties
VkSamplerYcbcrConversionInfoKHR = VkSamplerYcbcrConversionInfo
VkSemaphoreSignalInfoKHR = VkSemaphoreSignalInfo
VkSemaphoreSubmitInfoKHR = VkSemaphoreSubmitInfo
VkSemaphoreTypeCreateInfoKHR = VkSemaphoreTypeCreateInfo
VkSemaphoreWaitInfoKHR = VkSemaphoreWaitInfo
VkShaderRequiredSubgroupSizeCreateInfoEXT = VkPipelineShaderStageRequiredSubgroupSizeCreateInfo
VkSparseImageFormatProperties2KHR = VkSparseImageFormatProperties2
VkSparseImageMemoryRequirements2KHR = VkSparseImageMemoryRequirements2
VkSubmitInfo2KHR = VkSubmitInfo2
VkSubpassBeginInfoKHR = VkSubpassBeginInfo
VkSubpassDependency2KHR = VkSubpassDependency2
VkSubpassDescription2KHR = VkSubpassDescription2
VkSubpassDescriptionDepthStencilResolveKHR = VkSubpassDescriptionDepthStencilResolve
VkSubpassEndInfoKHR = VkSubpassEndInfo
VkSubresourceLayout2EXT = VkSubresourceLayout2KHR
VkTimelineSemaphoreSubmitInfoKHR = VkTimelineSemaphoreSubmitInfo
VkTransformMatrixNV = VkTransformMatrixKHR
VkVertexInputBindingDivisorDescriptionEXT = VkVertexInputBindingDivisorDescriptionKHR
VkWriteDescriptorSetInlineUniformBlockEXT = VkWriteDescriptorSetInlineUniformBlock
