import ctypes, sys
from ..vulkan_base import VulkanIntEnum

class StdVideoH264NonVclNaluType(VulkanIntEnum):
    STD_VIDEO_H264_NON_VCL_NALU_TYPE_AUD = 2
    STD_VIDEO_H264_NON_VCL_NALU_TYPE_END_OF_SEQUENCE = 4
    STD_VIDEO_H264_NON_VCL_NALU_TYPE_END_OF_STREAM = 5
    STD_VIDEO_H264_NON_VCL_NALU_TYPE_INVALID = 2147483647
    STD_VIDEO_H264_NON_VCL_NALU_TYPE_PPS = 1
    STD_VIDEO_H264_NON_VCL_NALU_TYPE_PRECODED = 6
    STD_VIDEO_H264_NON_VCL_NALU_TYPE_PREFIX = 3
    STD_VIDEO_H264_NON_VCL_NALU_TYPE_SPS = 0

sys.modules[__name__] = StdVideoH264NonVclNaluType

