from enum import IntEnum

class StdVideoDecodeH264FieldOrderCount(IntEnum):
    STD_VIDEO_DECODE_H264_FIELD_ORDER_COUNT_BOTTOM = 1
    STD_VIDEO_DECODE_H264_FIELD_ORDER_COUNT_INVALID = 2147483647
    STD_VIDEO_DECODE_H264_FIELD_ORDER_COUNT_TOP = 0
