import ctypes, sys
from ..vulkan_base import VulkanIntEnum

class StdVideoAV1InterpolationFilter(VulkanIntEnum):
    STD_VIDEO_AV1_INTERPOLATION_FILTER_BILINEAR = 3
    STD_VIDEO_AV1_INTERPOLATION_FILTER_EIGHTTAP = 0
    STD_VIDEO_AV1_INTERPOLATION_FILTER_EIGHTTAP_SHARP = 2
    STD_VIDEO_AV1_INTERPOLATION_FILTER_EIGHTTAP_SMOOTH = 1
    STD_VIDEO_AV1_INTERPOLATION_FILTER_INVALID = 2147483647
    STD_VIDEO_AV1_INTERPOLATION_FILTER_SWITCHABLE = 4

sys.modules[__name__] = StdVideoAV1InterpolationFilter

