from enum import IntEnum

class StdVideoAV1TxMode(IntEnum):
    STD_VIDEO_AV1_TX_MODE_INVALID = 2147483647
    STD_VIDEO_AV1_TX_MODE_LARGEST = 1
    STD_VIDEO_AV1_TX_MODE_ONLY_4X4 = 0
    STD_VIDEO_AV1_TX_MODE_SELECT = 2
