from enum import IntEnum

class StdVideoH264WeightedBipredIdc(IntEnum):
    STD_VIDEO_H264_WEIGHTED_BIPRED_IDC_DEFAULT = 0
    STD_VIDEO_H264_WEIGHTED_BIPRED_IDC_EXPLICIT = 1
    STD_VIDEO_H264_WEIGHTED_BIPRED_IDC_IMPLICIT = 2
    STD_VIDEO_H264_WEIGHTED_BIPRED_IDC_INVALID = 2147483647
