from enum import IntEnum

class StdVideoAV1FrameType(IntEnum):
    STD_VIDEO_AV1_FRAME_TYPE_INTER = 1
    STD_VIDEO_AV1_FRAME_TYPE_INTRA_ONLY = 2
    STD_VIDEO_AV1_FRAME_TYPE_INVALID = 2147483647
    STD_VIDEO_AV1_FRAME_TYPE_KEY = 0
    STD_VIDEO_AV1_FRAME_TYPE_SWITCH = 3
