from enum import IntEnum

class StdVideoAV1FrameRestorationType(IntEnum):
    STD_VIDEO_AV1_FRAME_RESTORATION_TYPE_INVALID = 2147483647
    STD_VIDEO_AV1_FRAME_RESTORATION_TYPE_NONE = 0
    STD_VIDEO_AV1_FRAME_RESTORATION_TYPE_SGRPROJ = 2
    STD_VIDEO_AV1_FRAME_RESTORATION_TYPE_SWITCHABLE = 3
    STD_VIDEO_AV1_FRAME_RESTORATION_TYPE_WIENER = 1
