import ctypes, sys
from ..vulkan_base import VulkanIntEnum

class StdVideoAV1MatrixCoefficients(VulkanIntEnum):
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_BT_2020_CL = 10
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_BT_2020_NCL = 9
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_BT_470_B_G = 5
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_BT_601 = 6
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_BT_709 = 1
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_CHROMAT_CL = 13
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_CHROMAT_NCL = 12
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_FCC = 4
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_ICTCP = 14
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_IDENTITY = 0
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_INVALID = 2147483647
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_RESERVED_3 = 3
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_SMPTE_2085 = 11
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_SMPTE_240 = 7
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_SMPTE_YCGCO = 8
    STD_VIDEO_AV1_MATRIX_COEFFICIENTS_UNSPECIFIED = 2

sys.modules[__name__] = StdVideoAV1MatrixCoefficients

