import ctypes, sys
from ..vulkan_base import VulkanIntEnum

class StdVideoH264ModificationOfPicNumsIdc(VulkanIntEnum):
    STD_VIDEO_H264_MODIFICATION_OF_PIC_NUMS_IDC_END = 3
    STD_VIDEO_H264_MODIFICATION_OF_PIC_NUMS_IDC_INVALID = 2147483647
    STD_VIDEO_H264_MODIFICATION_OF_PIC_NUMS_IDC_LONG_TERM = 2
    STD_VIDEO_H264_MODIFICATION_OF_PIC_NUMS_IDC_SHORT_TERM_ADD = 1
    STD_VIDEO_H264_MODIFICATION_OF_PIC_NUMS_IDC_SHORT_TERM_SUBTRACT = 0

sys.modules[__name__] = StdVideoH264ModificationOfPicNumsIdc

