from enum import IntFlag

class VkCommandPoolCreateFlags(IntFlag):
    VK_COMMAND_POOL_CREATE_PROTECTED_BIT = 4
    VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT = 2
    VK_COMMAND_POOL_CREATE_TRANSIENT_BIT = 1
