from enum import IntEnum

class VkCubicFilterWeightsQCOM(IntEnum):
    VK_CUBIC_FILTER_WEIGHTS_B_SPLINE_QCOM = 2
    VK_CUBIC_FILTER_WEIGHTS_CATMULL_ROM_QCOM = 0
    VK_CUBIC_FILTER_WEIGHTS_MITCHELL_NETRAVALI_QCOM = 3
    VK_CUBIC_FILTER_WEIGHTS_ZERO_TANGENT_CARDINAL_QCOM = 1
