import ctypes, sys
from ..vulkan_base import VulkanIntEnum

class VkPipelineRobustnessBufferBehaviorEXT(VulkanIntEnum):
    VK_PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_DEVICE_DEFAULT_EXT = 0
    VK_PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_DISABLED_EXT = 1
    VK_PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_ROBUST_BUFFER_ACCESS_2_EXT = 3
    VK_PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_ROBUST_BUFFER_ACCESS_EXT = 2

sys.modules[__name__] = VkPipelineRobustnessBufferBehaviorEXT

