import ctypes, sys
from ..vulkan_base import VulkanIntEnum

class VkPipelineBindPoint(VulkanIntEnum):
    VK_PIPELINE_BIND_POINT_COMPUTE = 1
    VK_PIPELINE_BIND_POINT_EXECUTION_GRAPH_AMDX = 1000134000
    VK_PIPELINE_BIND_POINT_GRAPHICS = 0
    VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR = 1000165000
    VK_PIPELINE_BIND_POINT_SUBPASS_SHADING_HUAWEI = 1000369003

sys.modules[__name__] = VkPipelineBindPoint

VkPipelineBindPoint.VK_PIPELINE_BIND_POINT_RAY_TRACING_NV = VkPipelineBindPoint.VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR
