import ctypes, sys
from ..vulkan_base import VulkanIntEnum

class VkPresentModeKHR(VulkanIntEnum):
    VK_PRESENT_MODE_FIFO_KHR = 2
    VK_PRESENT_MODE_FIFO_RELAXED_KHR = 3
    VK_PRESENT_MODE_IMMEDIATE_KHR = 0
    VK_PRESENT_MODE_MAILBOX_KHR = 1
    VK_PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR = 1000111001
    VK_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR = 1000111000

sys.modules[__name__] = VkPresentModeKHR

