import ctypes, sys
from ..vulkan_base import VulkanUIntFlag

class VkResolveModeFlags(VulkanUIntFlag):
    VK_RESOLVE_MODE_AVERAGE_BIT = 2
    VK_RESOLVE_MODE_EXTERNAL_FORMAT_DOWNSAMPLE_ANDROID = 16
    VK_RESOLVE_MODE_MAX_BIT = 8
    VK_RESOLVE_MODE_MIN_BIT = 4
    VK_RESOLVE_MODE_NONE = 0
    VK_RESOLVE_MODE_SAMPLE_ZERO_BIT = 1

sys.modules[__name__] = VkResolveModeFlags

VkResolveModeFlags.VK_RESOLVE_MODE_AVERAGE_BIT_KHR = VkResolveModeFlags.VK_RESOLVE_MODE_AVERAGE_BIT
VkResolveModeFlags.VK_RESOLVE_MODE_MAX_BIT_KHR = VkResolveModeFlags.VK_RESOLVE_MODE_MAX_BIT
VkResolveModeFlags.VK_RESOLVE_MODE_MIN_BIT_KHR = VkResolveModeFlags.VK_RESOLVE_MODE_MIN_BIT
VkResolveModeFlags.VK_RESOLVE_MODE_NONE_KHR = VkResolveModeFlags.VK_RESOLVE_MODE_NONE
VkResolveModeFlags.VK_RESOLVE_MODE_SAMPLE_ZERO_BIT_KHR = VkResolveModeFlags.VK_RESOLVE_MODE_SAMPLE_ZERO_BIT
