from enum import IntFlag

class VkSampleCountFlags(IntFlag):
    VK_SAMPLE_COUNT_16_BIT = 16
    VK_SAMPLE_COUNT_1_BIT = 1
    VK_SAMPLE_COUNT_2_BIT = 2
    VK_SAMPLE_COUNT_32_BIT = 32
    VK_SAMPLE_COUNT_4_BIT = 4
    VK_SAMPLE_COUNT_64_BIT = 64
    VK_SAMPLE_COUNT_8_BIT = 8
