import ctypes, sys
from ..vulkan_base import VulkanUIntFlag

class VkShaderStageFlags(VulkanUIntFlag):
    VK_SHADER_STAGE_ALL = 2147483647
    VK_SHADER_STAGE_ALL_GRAPHICS = 31
    VK_SHADER_STAGE_ANY_HIT_BIT_KHR = 512
    VK_SHADER_STAGE_CALLABLE_BIT_KHR = 8192
    VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR = 1024
    VK_SHADER_STAGE_CLUSTER_CULLING_BIT_HUAWEI = 524288
    VK_SHADER_STAGE_COMPUTE_BIT = 32
    VK_SHADER_STAGE_FRAGMENT_BIT = 16
    VK_SHADER_STAGE_GEOMETRY_BIT = 8
    VK_SHADER_STAGE_INTERSECTION_BIT_KHR = 4096
    VK_SHADER_STAGE_MESH_BIT_EXT = 128
    VK_SHADER_STAGE_MISS_BIT_KHR = 2048
    VK_SHADER_STAGE_RAYGEN_BIT_KHR = 256
    VK_SHADER_STAGE_SUBPASS_SHADING_BIT_HUAWEI = 16384
    VK_SHADER_STAGE_TASK_BIT_EXT = 64
    VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT = 2
    VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT = 4
    VK_SHADER_STAGE_VERTEX_BIT = 1

sys.modules[__name__] = VkShaderStageFlags

VkShaderStageFlags.VK_SHADER_STAGE_ANY_HIT_BIT_NV = VkShaderStageFlags.VK_SHADER_STAGE_ANY_HIT_BIT_KHR
VkShaderStageFlags.VK_SHADER_STAGE_CALLABLE_BIT_NV = VkShaderStageFlags.VK_SHADER_STAGE_CALLABLE_BIT_KHR
VkShaderStageFlags.VK_SHADER_STAGE_CLOSEST_HIT_BIT_NV = VkShaderStageFlags.VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR
VkShaderStageFlags.VK_SHADER_STAGE_INTERSECTION_BIT_NV = VkShaderStageFlags.VK_SHADER_STAGE_INTERSECTION_BIT_KHR
VkShaderStageFlags.VK_SHADER_STAGE_MESH_BIT_NV = VkShaderStageFlags.VK_SHADER_STAGE_MESH_BIT_EXT
VkShaderStageFlags.VK_SHADER_STAGE_MISS_BIT_NV = VkShaderStageFlags.VK_SHADER_STAGE_MISS_BIT_KHR
VkShaderStageFlags.VK_SHADER_STAGE_RAYGEN_BIT_NV = VkShaderStageFlags.VK_SHADER_STAGE_RAYGEN_BIT_KHR
VkShaderStageFlags.VK_SHADER_STAGE_TASK_BIT_NV = VkShaderStageFlags.VK_SHADER_STAGE_TASK_BIT_EXT
