from enum import IntFlag

class VkShaderCreateFlagsEXT(IntFlag):
    VK_SHADER_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT = 2
    VK_SHADER_CREATE_DISPATCH_BASE_BIT_EXT = 16
    VK_SHADER_CREATE_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXT = 64
    VK_SHADER_CREATE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_EXT = 32
    VK_SHADER_CREATE_LINK_STAGE_BIT_EXT = 1
    VK_SHADER_CREATE_NO_TASK_SHADER_BIT_EXT = 8
    VK_SHADER_CREATE_REQUIRE_FULL_SUBGROUPS_BIT_EXT = 4
