import ctypes, sys
from ..vulkan_base import VulkanUIntFlag

class VkSubgroupFeatureFlags(VulkanUIntFlag):
    VK_SUBGROUP_FEATURE_ARITHMETIC_BIT = 4
    VK_SUBGROUP_FEATURE_BALLOT_BIT = 8
    VK_SUBGROUP_FEATURE_BASIC_BIT = 1
    VK_SUBGROUP_FEATURE_CLUSTERED_BIT = 64
    VK_SUBGROUP_FEATURE_PARTITIONED_BIT_NV = 256
    VK_SUBGROUP_FEATURE_QUAD_BIT = 128
    VK_SUBGROUP_FEATURE_ROTATE_BIT_KHR = 512
    VK_SUBGROUP_FEATURE_ROTATE_CLUSTERED_BIT_KHR = 1024
    VK_SUBGROUP_FEATURE_SHUFFLE_BIT = 16
    VK_SUBGROUP_FEATURE_SHUFFLE_RELATIVE_BIT = 32
    VK_SUBGROUP_FEATURE_VOTE_BIT = 2

sys.modules[__name__] = VkSubgroupFeatureFlags

