import ctypes, sys
from .._vulkan_base import VulkanIntEnum

class StdVideoH264MemMgmtControlOp(VulkanIntEnum):
    STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_END = 0
    STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_INVALID = 2147483647
    STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_MARK_CURRENT_AS_LONG_TERM = 6
    STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_MARK_LONG_TERM = 3
    STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_SET_MAX_LONG_TERM_INDEX = 4
    STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_UNMARK_ALL = 5
    STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_UNMARK_LONG_TERM = 2
    STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_UNMARK_SHORT_TERM = 1

sys.modules[__name__] = StdVideoH264MemMgmtControlOp

