import ctypes, sys
from .._vulkan_base import VulkanIntEnum

class VkComponentTypeKHR(VulkanIntEnum):
    VK_COMPONENT_TYPE_FLOAT16_KHR = 0
    VK_COMPONENT_TYPE_FLOAT32_KHR = 1
    VK_COMPONENT_TYPE_FLOAT64_KHR = 2
    VK_COMPONENT_TYPE_SINT16_KHR = 4
    VK_COMPONENT_TYPE_SINT32_KHR = 5
    VK_COMPONENT_TYPE_SINT64_KHR = 6
    VK_COMPONENT_TYPE_SINT8_KHR = 3
    VK_COMPONENT_TYPE_UINT16_KHR = 8
    VK_COMPONENT_TYPE_UINT32_KHR = 9
    VK_COMPONENT_TYPE_UINT64_KHR = 10
    VK_COMPONENT_TYPE_UINT8_KHR = 7

sys.modules[__name__] = VkComponentTypeKHR

VkComponentTypeKHR.VK_COMPONENT_TYPE_FLOAT16_NV = VkComponentTypeKHR.VK_COMPONENT_TYPE_FLOAT16_KHR
VkComponentTypeKHR.VK_COMPONENT_TYPE_FLOAT32_NV = VkComponentTypeKHR.VK_COMPONENT_TYPE_FLOAT32_KHR
VkComponentTypeKHR.VK_COMPONENT_TYPE_FLOAT64_NV = VkComponentTypeKHR.VK_COMPONENT_TYPE_FLOAT64_KHR
VkComponentTypeKHR.VK_COMPONENT_TYPE_SINT16_NV = VkComponentTypeKHR.VK_COMPONENT_TYPE_SINT16_KHR
VkComponentTypeKHR.VK_COMPONENT_TYPE_SINT32_NV = VkComponentTypeKHR.VK_COMPONENT_TYPE_SINT32_KHR
VkComponentTypeKHR.VK_COMPONENT_TYPE_SINT64_NV = VkComponentTypeKHR.VK_COMPONENT_TYPE_SINT64_KHR
VkComponentTypeKHR.VK_COMPONENT_TYPE_SINT8_NV = VkComponentTypeKHR.VK_COMPONENT_TYPE_SINT8_KHR
VkComponentTypeKHR.VK_COMPONENT_TYPE_UINT16_NV = VkComponentTypeKHR.VK_COMPONENT_TYPE_UINT16_KHR
VkComponentTypeKHR.VK_COMPONENT_TYPE_UINT32_NV = VkComponentTypeKHR.VK_COMPONENT_TYPE_UINT32_KHR
VkComponentTypeKHR.VK_COMPONENT_TYPE_UINT64_NV = VkComponentTypeKHR.VK_COMPONENT_TYPE_UINT64_KHR
VkComponentTypeKHR.VK_COMPONENT_TYPE_UINT8_NV = VkComponentTypeKHR.VK_COMPONENT_TYPE_UINT8_KHR
