import ctypes, sys
from .._vulkan_base import VulkanUIntFlag

class VkMemoryPropertyFlags(VulkanUIntFlag):
    VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD = 64
    VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT = 1
    VK_MEMORY_PROPERTY_DEVICE_UNCACHED_BIT_AMD = 128
    VK_MEMORY_PROPERTY_HOST_CACHED_BIT = 8
    VK_MEMORY_PROPERTY_HOST_COHERENT_BIT = 4
    VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT = 2
    VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT = 16
    VK_MEMORY_PROPERTY_PROTECTED_BIT = 32
    VK_MEMORY_PROPERTY_RDMA_CAPABLE_BIT_NV = 256

sys.modules[__name__] = VkMemoryPropertyFlags

