import ctypes, sys
from .._vulkan_base import VulkanUIntFlag

class VkVideoCodecOperationFlagsKHR(VulkanUIntFlag):
    VK_VIDEO_CODEC_OPERATION_DECODE_H264_BIT_KHR = 1
    VK_VIDEO_CODEC_OPERATION_ENCODE_H265_BIT_KHR = 131072
    VK_VIDEO_CODEC_OPERATION_DECODE_AV1_BIT_KHR = 4
    VK_VIDEO_CODEC_OPERATION_DECODE_H265_BIT_KHR = 2
    VK_VIDEO_CODEC_OPERATION_ENCODE_H264_BIT_KHR = 65536
    VK_VIDEO_CODEC_OPERATION_NONE_KHR = 0

sys.modules[__name__] = VkVideoCodecOperationFlagsKHR
