from ..._ctypes import *

_category_ = 'structure'
_name_ = 'VkAllocationCallbacks'
_member_list_ = ['pUserData', 'pfnAllocation', 'pfnReallocation', 'pfnFree', 'pfnInternalAllocation', 'pfnInternalFree']
_member_info_ = {
    'pUserData': {
        'type': CIntType('c_void_p'),
        'is_string': False,
    },
    'pfnAllocation': {
        'type': CFunctionType('vkAllocationFunction'),
        'callback': 'vkAllocationFunction',
        'is_string': False,
    },
    'pfnReallocation': {
        'type': CFunctionType('vkReallocationFunction'),
        'callback': 'vkReallocationFunction',
        'is_string': False,
    },
    'pfnFree': {
        'type': CFunctionType('vkFreeFunction'),
        'callback': 'vkFreeFunction',
        'is_string': False,
    },
    'pfnInternalAllocation': {
        'type': CFunctionType('vkInternalAllocationNotification'),
        'callback': 'vkInternalAllocationNotification',
        'is_string': False,
    },
    'pfnInternalFree': {
        'type': CFunctionType('vkInternalFreeNotification'),
        'callback': 'vkInternalFreeNotification',
        'is_string': False,
    },
}
_extends_ = set()
_extended_by_ = set()
_includes_ = set()
_included_in_ = set()
_input_of_ = {
    'vkAllocateMemory',
    'vkCreateAccelerationStructureKHR',
    'vkCreateAccelerationStructureNV',
    'vkCreateAndroidSurfaceKHR',
    'vkCreateBuffer',
    'vkCreateBufferCollectionFUCHSIA',
    'vkCreateBufferView',
    'vkCreateCommandPool',
    'vkCreateComputePipelines',
    'vkCreateCuFunctionNVX',
    'vkCreateCuModuleNVX',
    'vkCreateCudaFunctionNV',
    'vkCreateCudaModuleNV',
    'vkCreateDebugReportCallbackEXT',
    'vkCreateDebugUtilsMessengerEXT',
    'vkCreateDeferredOperationKHR',
    'vkCreateDescriptorPool',
    'vkCreateDescriptorSetLayout',
    'vkCreateDescriptorUpdateTemplate',
    'vkCreateDevice',
    'vkCreateDirectFBSurfaceEXT',
    'vkCreateDisplayModeKHR',
    'vkCreateDisplayPlaneSurfaceKHR',
    'vkCreateEvent',
    'vkCreateExecutionGraphPipelinesAMDX',
    'vkCreateFence',
    'vkCreateFramebuffer',
    'vkCreateGraphicsPipelines',
    'vkCreateHeadlessSurfaceEXT',
    'vkCreateIOSSurfaceMVK',
    'vkCreateImage',
    'vkCreateImagePipeSurfaceFUCHSIA',
    'vkCreateImageView',
    'vkCreateIndirectCommandsLayoutNV',
    'vkCreateInstance',
    'vkCreateMacOSSurfaceMVK',
    'vkCreateMetalSurfaceEXT',
    'vkCreateMicromapEXT',
    'vkCreateOpticalFlowSessionNV',
    'vkCreatePipelineCache',
    'vkCreatePipelineLayout',
    'vkCreatePrivateDataSlot',
    'vkCreateQueryPool',
    'vkCreateRayTracingPipelinesKHR',
    'vkCreateRayTracingPipelinesNV',
    'vkCreateRenderPass',
    'vkCreateRenderPass2',
    'vkCreateSampler',
    'vkCreateSamplerYcbcrConversion',
    'vkCreateScreenSurfaceQNX',
    'vkCreateSemaphore',
    'vkCreateShaderModule',
    'vkCreateShadersEXT',
    'vkCreateSharedSwapchainsKHR',
    'vkCreateStreamDescriptorSurfaceGGP',
    'vkCreateSwapchainKHR',
    'vkCreateValidationCacheEXT',
    'vkCreateViSurfaceNN',
    'vkCreateVideoSessionKHR',
    'vkCreateVideoSessionParametersKHR',
    'vkCreateWaylandSurfaceKHR',
    'vkCreateWin32SurfaceKHR',
    'vkCreateXcbSurfaceKHR',
    'vkCreateXlibSurfaceKHR',
    'vkDestroyAccelerationStructureKHR',
    'vkDestroyAccelerationStructureNV',
    'vkDestroyBuffer',
    'vkDestroyBufferCollectionFUCHSIA',
    'vkDestroyBufferView',
    'vkDestroyCommandPool',
    'vkDestroyCuFunctionNVX',
    'vkDestroyCuModuleNVX',
    'vkDestroyCudaFunctionNV',
    'vkDestroyCudaModuleNV',
    'vkDestroyDebugReportCallbackEXT',
    'vkDestroyDebugUtilsMessengerEXT',
    'vkDestroyDeferredOperationKHR',
    'vkDestroyDescriptorPool',
    'vkDestroyDescriptorSetLayout',
    'vkDestroyDescriptorUpdateTemplate',
    'vkDestroyDevice',
    'vkDestroyEvent',
    'vkDestroyFence',
    'vkDestroyFramebuffer',
    'vkDestroyImage',
    'vkDestroyImageView',
    'vkDestroyIndirectCommandsLayoutNV',
    'vkDestroyInstance',
    'vkDestroyMicromapEXT',
    'vkDestroyOpticalFlowSessionNV',
    'vkDestroyPipeline',
    'vkDestroyPipelineCache',
    'vkDestroyPipelineLayout',
    'vkDestroyPrivateDataSlot',
    'vkDestroyQueryPool',
    'vkDestroyRenderPass',
    'vkDestroySampler',
    'vkDestroySamplerYcbcrConversion',
    'vkDestroySemaphore',
    'vkDestroySemaphoreSciSyncPoolNV',
    'vkDestroyShaderEXT',
    'vkDestroyShaderModule',
    'vkDestroySurfaceKHR',
    'vkDestroySwapchainKHR',
    'vkDestroyValidationCacheEXT',
    'vkDestroyVideoSessionKHR',
    'vkDestroyVideoSessionParametersKHR',
    'vkFreeMemory',
    'vkRegisterDeviceEventEXT',
    'vkRegisterDisplayEventEXT',
}
_output_of_ = set()
