from ..._ctypes import *

_category_ = 'structure'
_name_ = 'VkDeviceCreateInfo'
_member_list_ = ['sType', 'pNext', 'flags', 'queueCreateInfoCount', 'pQueueCreateInfos', 'enabledLayerCount', 'ppEnabledLayerNames', 'enabledExtensionCount', 'ppEnabledExtensionNames', 'pEnabledFeatures']
_member_info_ = {
    'sType': {
        'type': CIntType('c_int'),
        'type_name': 'VkStructureType',
        'enum': 'VkStructureType',
        'value': 'VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO',
        'is_string': False,
    },
    'pNext': {
        'type': CIntType('c_void_p'),
        'is_string': False,
    },
    'flags': {
        'type': CIntType('c_uint32'),
        'type_name': 'VkDeviceCreateFlags',
        'enum': 'VkDeviceCreateFlags',
        'is_string': False,
    },
    'queueCreateInfoCount': {
        'type': CIntType('c_uint32'),
        'is_string': False,
    },
    'pQueueCreateInfos': {
        'type': CPointerType(CComplexType('VkDeviceQueueCreateInfo')),
        'type_name': 'VkDeviceQueueCreateInfo',
        'structure': 'VkDeviceQueueCreateInfo',
        'length': [['queueCreateInfoCount']],
        'is_string': False,
    },
    'enabledLayerCount': {
        'type': CIntType('c_uint32'),
        'is_string': False,
    },
    'ppEnabledLayerNames': {
        'type': CPointerType(CStringType('c_char_p')),
        'length': [['enabledLayerCount']],
        'is_string': True,
    },
    'enabledExtensionCount': {
        'type': CIntType('c_uint32'),
        'is_string': False,
    },
    'ppEnabledExtensionNames': {
        'type': CPointerType(CStringType('c_char_p')),
        'length': [['enabledExtensionCount']],
        'is_string': True,
    },
    'pEnabledFeatures': {
        'type': CPointerType(CComplexType('VkPhysicalDeviceFeatures')),
        'type_name': 'VkPhysicalDeviceFeatures',
        'structure': 'VkPhysicalDeviceFeatures',
        'is_string': False,
    },
}
_extends_ = set()
_extended_by_ = {
    'VkDeviceDeviceMemoryReportCreateInfoEXT',
    'VkDeviceDiagnosticsConfigCreateInfoNV',
    'VkDeviceGroupDeviceCreateInfo',
    'VkDeviceMemoryOverallocationCreateInfoAMD',
    'VkDevicePrivateDataCreateInfo',
    'VkDeviceQueueShaderCoreControlCreateInfoARM',
    'VkPhysicalDevice16BitStorageFeatures',
    'VkPhysicalDevice4444FormatsFeaturesEXT',
    'VkPhysicalDevice8BitStorageFeatures',
    'VkPhysicalDeviceASTCDecodeFeaturesEXT',
    'VkPhysicalDeviceAccelerationStructureFeaturesKHR',
    'VkPhysicalDeviceAddressBindingReportFeaturesEXT',
    'VkPhysicalDeviceAmigoProfilingFeaturesSEC',
    'VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXT',
    'VkPhysicalDeviceAttachmentFeedbackLoopLayoutFeaturesEXT',
    'VkPhysicalDeviceBlendOperationAdvancedFeaturesEXT',
    'VkPhysicalDeviceBorderColorSwizzleFeaturesEXT',
    'VkPhysicalDeviceBufferDeviceAddressFeatures',
    'VkPhysicalDeviceBufferDeviceAddressFeaturesEXT',
    'VkPhysicalDeviceClusterCullingShaderFeaturesHUAWEI',
    'VkPhysicalDeviceCoherentMemoryFeaturesAMD',
    'VkPhysicalDeviceColorWriteEnableFeaturesEXT',
    'VkPhysicalDeviceComputeShaderDerivativesFeaturesNV',
    'VkPhysicalDeviceConditionalRenderingFeaturesEXT',
    'VkPhysicalDeviceCooperativeMatrixFeaturesKHR',
    'VkPhysicalDeviceCooperativeMatrixFeaturesNV',
    'VkPhysicalDeviceCopyMemoryIndirectFeaturesNV',
    'VkPhysicalDeviceCornerSampledImageFeaturesNV',
    'VkPhysicalDeviceCoverageReductionModeFeaturesNV',
    'VkPhysicalDeviceCubicClampFeaturesQCOM',
    'VkPhysicalDeviceCubicWeightsFeaturesQCOM',
    'VkPhysicalDeviceCudaKernelLaunchFeaturesNV',
    'VkPhysicalDeviceCustomBorderColorFeaturesEXT',
    'VkPhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV',
    'VkPhysicalDeviceDepthBiasControlFeaturesEXT',
    'VkPhysicalDeviceDepthClampZeroOneFeaturesEXT',
    'VkPhysicalDeviceDepthClipControlFeaturesEXT',
    'VkPhysicalDeviceDepthClipEnableFeaturesEXT',
    'VkPhysicalDeviceDescriptorBufferFeaturesEXT',
    'VkPhysicalDeviceDescriptorIndexingFeatures',
    'VkPhysicalDeviceDescriptorPoolOverallocationFeaturesNV',
    'VkPhysicalDeviceDescriptorSetHostMappingFeaturesVALVE',
    'VkPhysicalDeviceDeviceGeneratedCommandsComputeFeaturesNV',
    'VkPhysicalDeviceDeviceGeneratedCommandsFeaturesNV',
    'VkPhysicalDeviceDeviceMemoryReportFeaturesEXT',
    'VkPhysicalDeviceDiagnosticsConfigFeaturesNV',
    'VkPhysicalDeviceDisplacementMicromapFeaturesNV',
    'VkPhysicalDeviceDynamicRenderingFeatures',
    'VkPhysicalDeviceDynamicRenderingLocalReadFeaturesKHR',
    'VkPhysicalDeviceDynamicRenderingUnusedAttachmentsFeaturesEXT',
    'VkPhysicalDeviceExclusiveScissorFeaturesNV',
    'VkPhysicalDeviceExtendedDynamicState2FeaturesEXT',
    'VkPhysicalDeviceExtendedDynamicState3FeaturesEXT',
    'VkPhysicalDeviceExtendedDynamicStateFeaturesEXT',
    'VkPhysicalDeviceExtendedSparseAddressSpaceFeaturesNV',
    'VkPhysicalDeviceExternalFormatResolveFeaturesANDROID',
    'VkPhysicalDeviceExternalMemoryRDMAFeaturesNV',
    'VkPhysicalDeviceExternalMemoryScreenBufferFeaturesQNX',
    'VkPhysicalDeviceFaultFeaturesEXT',
    'VkPhysicalDeviceFeatures2',
    'VkPhysicalDeviceFragmentDensityMap2FeaturesEXT',
    'VkPhysicalDeviceFragmentDensityMapFeaturesEXT',
    'VkPhysicalDeviceFragmentDensityMapOffsetFeaturesQCOM',
    'VkPhysicalDeviceFragmentShaderBarycentricFeaturesKHR',
    'VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT',
    'VkPhysicalDeviceFragmentShadingRateEnumsFeaturesNV',
    'VkPhysicalDeviceFragmentShadingRateFeaturesKHR',
    'VkPhysicalDeviceFrameBoundaryFeaturesEXT',
    'VkPhysicalDeviceGlobalPriorityQueryFeaturesKHR',
    'VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT',
    'VkPhysicalDeviceHostImageCopyFeaturesEXT',
    'VkPhysicalDeviceHostQueryResetFeatures',
    'VkPhysicalDeviceImage2DViewOf3DFeaturesEXT',
    'VkPhysicalDeviceImageAlignmentControlFeaturesMESA',
    'VkPhysicalDeviceImageCompressionControlFeaturesEXT',
    'VkPhysicalDeviceImageCompressionControlSwapchainFeaturesEXT',
    'VkPhysicalDeviceImageProcessing2FeaturesQCOM',
    'VkPhysicalDeviceImageProcessingFeaturesQCOM',
    'VkPhysicalDeviceImageRobustnessFeatures',
    'VkPhysicalDeviceImageSlicedViewOf3DFeaturesEXT',
    'VkPhysicalDeviceImageViewMinLodFeaturesEXT',
    'VkPhysicalDeviceImagelessFramebufferFeatures',
    'VkPhysicalDeviceIndexTypeUint8FeaturesKHR',
    'VkPhysicalDeviceInheritedViewportScissorFeaturesNV',
    'VkPhysicalDeviceInlineUniformBlockFeatures',
    'VkPhysicalDeviceInvocationMaskFeaturesHUAWEI',
    'VkPhysicalDeviceLegacyDitheringFeaturesEXT',
    'VkPhysicalDeviceLegacyVertexAttributesFeaturesEXT',
    'VkPhysicalDeviceLineRasterizationFeaturesKHR',
    'VkPhysicalDeviceLinearColorAttachmentFeaturesNV',
    'VkPhysicalDeviceMaintenance4Features',
    'VkPhysicalDeviceMaintenance5FeaturesKHR',
    'VkPhysicalDeviceMaintenance6FeaturesKHR',
    'VkPhysicalDeviceMaintenance7FeaturesKHR',
    'VkPhysicalDeviceMapMemoryPlacedFeaturesEXT',
    'VkPhysicalDeviceMemoryDecompressionFeaturesNV',
    'VkPhysicalDeviceMemoryPriorityFeaturesEXT',
    'VkPhysicalDeviceMeshShaderFeaturesEXT',
    'VkPhysicalDeviceMeshShaderFeaturesNV',
    'VkPhysicalDeviceMultiDrawFeaturesEXT',
    'VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT',
    'VkPhysicalDeviceMultiviewFeatures',
    'VkPhysicalDeviceMultiviewPerViewRenderAreasFeaturesQCOM',
    'VkPhysicalDeviceMultiviewPerViewViewportsFeaturesQCOM',
    'VkPhysicalDeviceMutableDescriptorTypeFeaturesEXT',
    'VkPhysicalDeviceNestedCommandBufferFeaturesEXT',
    'VkPhysicalDeviceNonSeamlessCubeMapFeaturesEXT',
    'VkPhysicalDeviceOpacityMicromapFeaturesEXT',
    'VkPhysicalDeviceOpticalFlowFeaturesNV',
    'VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT',
    'VkPhysicalDevicePerStageDescriptorSetFeaturesNV',
    'VkPhysicalDevicePerformanceQueryFeaturesKHR',
    'VkPhysicalDevicePipelineCreationCacheControlFeatures',
    'VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR',
    'VkPhysicalDevicePipelineLibraryGroupHandlesFeaturesEXT',
    'VkPhysicalDevicePipelinePropertiesFeaturesEXT',
    'VkPhysicalDevicePipelineProtectedAccessFeaturesEXT',
    'VkPhysicalDevicePipelineRobustnessFeaturesEXT',
    'VkPhysicalDevicePortabilitySubsetFeaturesKHR',
    'VkPhysicalDevicePresentBarrierFeaturesNV',
    'VkPhysicalDevicePresentIdFeaturesKHR',
    'VkPhysicalDevicePresentWaitFeaturesKHR',
    'VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT',
    'VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT',
    'VkPhysicalDevicePrivateDataFeatures',
    'VkPhysicalDeviceProtectedMemoryFeatures',
    'VkPhysicalDeviceProvokingVertexFeaturesEXT',
    'VkPhysicalDeviceRGBA10X6FormatsFeaturesEXT',
    'VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT',
    'VkPhysicalDeviceRawAccessChainsFeaturesNV',
    'VkPhysicalDeviceRayQueryFeaturesKHR',
    'VkPhysicalDeviceRayTracingInvocationReorderFeaturesNV',
    'VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR',
    'VkPhysicalDeviceRayTracingMotionBlurFeaturesNV',
    'VkPhysicalDeviceRayTracingPipelineFeaturesKHR',
    'VkPhysicalDeviceRayTracingPositionFetchFeaturesKHR',
    'VkPhysicalDeviceRayTracingValidationFeaturesNV',
    'VkPhysicalDeviceRelaxedLineRasterizationFeaturesIMG',
    'VkPhysicalDeviceRenderPassStripedFeaturesARM',
    'VkPhysicalDeviceRepresentativeFragmentTestFeaturesNV',
    'VkPhysicalDeviceRobustness2FeaturesEXT',
    'VkPhysicalDeviceSamplerYcbcrConversionFeatures',
    'VkPhysicalDeviceScalarBlockLayoutFeatures',
    'VkPhysicalDeviceSchedulingControlsFeaturesARM',
    'VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures',
    'VkPhysicalDeviceShaderAtomicFloat16VectorFeaturesNV',
    'VkPhysicalDeviceShaderAtomicFloat2FeaturesEXT',
    'VkPhysicalDeviceShaderAtomicFloatFeaturesEXT',
    'VkPhysicalDeviceShaderAtomicInt64Features',
    'VkPhysicalDeviceShaderClockFeaturesKHR',
    'VkPhysicalDeviceShaderCoreBuiltinsFeaturesARM',
    'VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures',
    'VkPhysicalDeviceShaderDrawParametersFeatures',
    'VkPhysicalDeviceShaderEarlyAndLateFragmentTestsFeaturesAMD',
    'VkPhysicalDeviceShaderEnqueueFeaturesAMDX',
    'VkPhysicalDeviceShaderExpectAssumeFeaturesKHR',
    'VkPhysicalDeviceShaderFloat16Int8Features',
    'VkPhysicalDeviceShaderFloatControls2FeaturesKHR',
    'VkPhysicalDeviceShaderImageAtomicInt64FeaturesEXT',
    'VkPhysicalDeviceShaderImageFootprintFeaturesNV',
    'VkPhysicalDeviceShaderIntegerDotProductFeatures',
    'VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL',
    'VkPhysicalDeviceShaderMaximalReconvergenceFeaturesKHR',
    'VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT',
    'VkPhysicalDeviceShaderObjectFeaturesEXT',
    'VkPhysicalDeviceShaderQuadControlFeaturesKHR',
    'VkPhysicalDeviceShaderRelaxedExtendedInstructionFeaturesKHR',
    'VkPhysicalDeviceShaderReplicatedCompositesFeaturesEXT',
    'VkPhysicalDeviceShaderSMBuiltinsFeaturesNV',
    'VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures',
    'VkPhysicalDeviceShaderSubgroupRotateFeaturesKHR',
    'VkPhysicalDeviceShaderSubgroupUniformControlFlowFeaturesKHR',
    'VkPhysicalDeviceShaderTerminateInvocationFeatures',
    'VkPhysicalDeviceShaderTileImageFeaturesEXT',
    'VkPhysicalDeviceShadingRateImageFeaturesNV',
    'VkPhysicalDeviceSubgroupSizeControlFeatures',
    'VkPhysicalDeviceSubpassMergeFeedbackFeaturesEXT',
    'VkPhysicalDeviceSubpassShadingFeaturesHUAWEI',
    'VkPhysicalDeviceSwapchainMaintenance1FeaturesEXT',
    'VkPhysicalDeviceSynchronization2Features',
    'VkPhysicalDeviceTexelBufferAlignmentFeaturesEXT',
    'VkPhysicalDeviceTextureCompressionASTCHDRFeatures',
    'VkPhysicalDeviceTilePropertiesFeaturesQCOM',
    'VkPhysicalDeviceTimelineSemaphoreFeatures',
    'VkPhysicalDeviceTransformFeedbackFeaturesEXT',
    'VkPhysicalDeviceUniformBufferStandardLayoutFeatures',
    'VkPhysicalDeviceVariablePointersFeatures',
    'VkPhysicalDeviceVertexAttributeDivisorFeaturesKHR',
    'VkPhysicalDeviceVertexInputDynamicStateFeaturesEXT',
    'VkPhysicalDeviceVideoMaintenance1FeaturesKHR',
    'VkPhysicalDeviceVulkan11Features',
    'VkPhysicalDeviceVulkan12Features',
    'VkPhysicalDeviceVulkan13Features',
    'VkPhysicalDeviceVulkanMemoryModelFeatures',
    'VkPhysicalDeviceWorkgroupMemoryExplicitLayoutFeaturesKHR',
    'VkPhysicalDeviceYcbcr2Plane444FormatsFeaturesEXT',
    'VkPhysicalDeviceYcbcrDegammaFeaturesQCOM',
    'VkPhysicalDeviceYcbcrImageArraysFeaturesEXT',
    'VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures',
}
_includes_ = {
    'VkDeviceQueueCreateInfo',
    'VkPhysicalDeviceFeatures',
}
_included_in_ = set()
_input_of_ = {
    'vkCreateDevice',
}
_output_of_ = set()
