from ..._ctypes import *

_category_ = 'structure'
_name_ = 'VkPhysicalDeviceProperties2'
_member_list_ = ['sType', 'pNext', 'properties']
_member_info_ = {
    'sType': {
        'type': CIntType('c_int'),
        'type_name': 'VkStructureType',
        'enum': 'VkStructureType',
        'value': 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2',
        'is_string': False,
    },
    'pNext': {
        'type': CIntType('c_void_p'),
        'is_string': False,
    },
    'properties': {
        'type': CComplexType('VkPhysicalDeviceProperties'),
        'type_name': 'VkPhysicalDeviceProperties',
        'structure': 'VkPhysicalDeviceProperties',
        'is_string': False,
    },
}
_extends_ = set()
_extended_by_ = {
    'VkPhysicalDeviceAccelerationStructurePropertiesKHR',
    'VkPhysicalDeviceBlendOperationAdvancedPropertiesEXT',
    'VkPhysicalDeviceClusterCullingShaderPropertiesHUAWEI',
    'VkPhysicalDeviceConservativeRasterizationPropertiesEXT',
    'VkPhysicalDeviceCooperativeMatrixPropertiesKHR',
    'VkPhysicalDeviceCooperativeMatrixPropertiesNV',
    'VkPhysicalDeviceCopyMemoryIndirectPropertiesNV',
    'VkPhysicalDeviceCudaKernelLaunchPropertiesNV',
    'VkPhysicalDeviceCustomBorderColorPropertiesEXT',
    'VkPhysicalDeviceDepthStencilResolveProperties',
    'VkPhysicalDeviceDescriptorBufferDensityMapPropertiesEXT',
    'VkPhysicalDeviceDescriptorBufferPropertiesEXT',
    'VkPhysicalDeviceDescriptorIndexingProperties',
    'VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV',
    'VkPhysicalDeviceDiscardRectanglePropertiesEXT',
    'VkPhysicalDeviceDisplacementMicromapPropertiesNV',
    'VkPhysicalDeviceDriverProperties',
    'VkPhysicalDeviceDrmPropertiesEXT',
    'VkPhysicalDeviceExtendedDynamicState3PropertiesEXT',
    'VkPhysicalDeviceExtendedSparseAddressSpacePropertiesNV',
    'VkPhysicalDeviceExternalFormatResolvePropertiesANDROID',
    'VkPhysicalDeviceExternalMemoryHostPropertiesEXT',
    'VkPhysicalDeviceFloatControlsProperties',
    'VkPhysicalDeviceFragmentDensityMap2PropertiesEXT',
    'VkPhysicalDeviceFragmentDensityMapOffsetPropertiesQCOM',
    'VkPhysicalDeviceFragmentDensityMapPropertiesEXT',
    'VkPhysicalDeviceFragmentShaderBarycentricPropertiesKHR',
    'VkPhysicalDeviceFragmentShadingRateEnumsPropertiesNV',
    'VkPhysicalDeviceFragmentShadingRatePropertiesKHR',
    'VkPhysicalDeviceGraphicsPipelineLibraryPropertiesEXT',
    'VkPhysicalDeviceHostImageCopyPropertiesEXT',
    'VkPhysicalDeviceIDProperties',
    'VkPhysicalDeviceImageAlignmentControlPropertiesMESA',
    'VkPhysicalDeviceImageProcessing2PropertiesQCOM',
    'VkPhysicalDeviceImageProcessingPropertiesQCOM',
    'VkPhysicalDeviceInlineUniformBlockProperties',
    'VkPhysicalDeviceLayeredApiPropertiesListKHR',
    'VkPhysicalDeviceLayeredDriverPropertiesMSFT',
    'VkPhysicalDeviceLegacyVertexAttributesPropertiesEXT',
    'VkPhysicalDeviceLineRasterizationPropertiesKHR',
    'VkPhysicalDeviceMaintenance3Properties',
    'VkPhysicalDeviceMaintenance4Properties',
    'VkPhysicalDeviceMaintenance5PropertiesKHR',
    'VkPhysicalDeviceMaintenance6PropertiesKHR',
    'VkPhysicalDeviceMaintenance7PropertiesKHR',
    'VkPhysicalDeviceMapMemoryPlacedPropertiesEXT',
    'VkPhysicalDeviceMemoryDecompressionPropertiesNV',
    'VkPhysicalDeviceMeshShaderPropertiesEXT',
    'VkPhysicalDeviceMeshShaderPropertiesNV',
    'VkPhysicalDeviceMultiDrawPropertiesEXT',
    'VkPhysicalDeviceMultiviewPerViewAttributesPropertiesNVX',
    'VkPhysicalDeviceMultiviewProperties',
    'VkPhysicalDeviceNestedCommandBufferPropertiesEXT',
    'VkPhysicalDeviceOpacityMicromapPropertiesEXT',
    'VkPhysicalDeviceOpticalFlowPropertiesNV',
    'VkPhysicalDevicePCIBusInfoPropertiesEXT',
    'VkPhysicalDevicePerformanceQueryPropertiesKHR',
    'VkPhysicalDevicePipelineRobustnessPropertiesEXT',
    'VkPhysicalDevicePointClippingProperties',
    'VkPhysicalDevicePortabilitySubsetPropertiesKHR',
    'VkPhysicalDeviceProtectedMemoryProperties',
    'VkPhysicalDeviceProvokingVertexPropertiesEXT',
    'VkPhysicalDevicePushDescriptorPropertiesKHR',
    'VkPhysicalDeviceRayTracingInvocationReorderPropertiesNV',
    'VkPhysicalDeviceRayTracingPipelinePropertiesKHR',
    'VkPhysicalDeviceRayTracingPropertiesNV',
    'VkPhysicalDeviceRenderPassStripedPropertiesARM',
    'VkPhysicalDeviceRobustness2PropertiesEXT',
    'VkPhysicalDeviceSampleLocationsPropertiesEXT',
    'VkPhysicalDeviceSamplerFilterMinmaxProperties',
    'VkPhysicalDeviceSchedulingControlsPropertiesARM',
    'VkPhysicalDeviceShaderCoreBuiltinsPropertiesARM',
    'VkPhysicalDeviceShaderCoreProperties2AMD',
    'VkPhysicalDeviceShaderCorePropertiesAMD',
    'VkPhysicalDeviceShaderCorePropertiesARM',
    'VkPhysicalDeviceShaderEnqueuePropertiesAMDX',
    'VkPhysicalDeviceShaderIntegerDotProductProperties',
    'VkPhysicalDeviceShaderModuleIdentifierPropertiesEXT',
    'VkPhysicalDeviceShaderObjectPropertiesEXT',
    'VkPhysicalDeviceShaderSMBuiltinsPropertiesNV',
    'VkPhysicalDeviceShaderTileImagePropertiesEXT',
    'VkPhysicalDeviceShadingRateImagePropertiesNV',
    'VkPhysicalDeviceSubgroupProperties',
    'VkPhysicalDeviceSubgroupSizeControlProperties',
    'VkPhysicalDeviceSubpassShadingPropertiesHUAWEI',
    'VkPhysicalDeviceTexelBufferAlignmentProperties',
    'VkPhysicalDeviceTimelineSemaphoreProperties',
    'VkPhysicalDeviceTransformFeedbackPropertiesEXT',
    'VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT',
    'VkPhysicalDeviceVertexAttributeDivisorPropertiesKHR',
    'VkPhysicalDeviceVulkan11Properties',
    'VkPhysicalDeviceVulkan12Properties',
    'VkPhysicalDeviceVulkan13Properties',
}
_includes_ = {
    'VkPhysicalDeviceProperties',
}
_included_in_ = {
    'VkPhysicalDeviceLayeredApiVulkanPropertiesKHR',
}
_input_of_ = set()
_output_of_ = {
    'vkGetPhysicalDeviceProperties2',
}
