import ctypes

class CType(ctypes.Structure):
    _fields_ = [
        ('sps_temporal_id_nesting_flag', ctypes.c_uint32, 1),
        ('separate_colour_plane_flag', ctypes.c_uint32, 1),
        ('conformance_window_flag', ctypes.c_uint32, 1),
        ('sps_sub_layer_ordering_info_present_flag', ctypes.c_uint32, 1),
        ('scaling_list_enabled_flag', ctypes.c_uint32, 1),
        ('sps_scaling_list_data_present_flag', ctypes.c_uint32, 1),
        ('amp_enabled_flag', ctypes.c_uint32, 1),
        ('sample_adaptive_offset_enabled_flag', ctypes.c_uint32, 1),
        ('pcm_enabled_flag', ctypes.c_uint32, 1),
        ('pcm_loop_filter_disabled_flag', ctypes.c_uint32, 1),
        ('long_term_ref_pics_present_flag', ctypes.c_uint32, 1),
        ('sps_temporal_mvp_enabled_flag', ctypes.c_uint32, 1),
        ('strong_intra_smoothing_enabled_flag', ctypes.c_uint32, 1),
        ('vui_parameters_present_flag', ctypes.c_uint32, 1),
        ('sps_extension_present_flag', ctypes.c_uint32, 1),
        ('sps_range_extension_flag', ctypes.c_uint32, 1),
        ('transform_skip_rotation_enabled_flag', ctypes.c_uint32, 1),
        ('transform_skip_context_enabled_flag', ctypes.c_uint32, 1),
        ('implicit_rdpcm_enabled_flag', ctypes.c_uint32, 1),
        ('explicit_rdpcm_enabled_flag', ctypes.c_uint32, 1),
        ('extended_precision_processing_flag', ctypes.c_uint32, 1),
        ('intra_smoothing_disabled_flag', ctypes.c_uint32, 1),
        ('high_precision_offsets_enabled_flag', ctypes.c_uint32, 1),
        ('persistent_rice_adaptation_enabled_flag', ctypes.c_uint32, 1),
        ('cabac_bypass_alignment_enabled_flag', ctypes.c_uint32, 1),
        ('sps_scc_extension_flag', ctypes.c_uint32, 1),
        ('sps_curr_pic_ref_enabled_flag', ctypes.c_uint32, 1),
        ('palette_mode_enabled_flag', ctypes.c_uint32, 1),
        ('sps_palette_predictor_initializers_present_flag', ctypes.c_uint32, 1),
        ('intra_boundary_filtering_disabled_flag', ctypes.c_uint32, 1),
    ]

descriptor = {
    'extends': set(),
    'extended_by': set(),
    'includes': set(),
    'included_in': {
        'StdVideoH265SequenceParameterSet',
    },
    'input_of': set(),
    'output_of': set(),
    'member_map': {
        'sps_temporal_id_nesting_flag': {'python_name': ['sps', 'temporal', 'id', 'nesting', 'flag']},
        'separate_colour_plane_flag': {'python_name': ['separate', 'colour', 'plane', 'flag']},
        'conformance_window_flag': {'python_name': ['conformance', 'window', 'flag']},
        'sps_sub_layer_ordering_info_present_flag': {'python_name': ['sps', 'sub', 'layer', 'ordering', 'info', 'present', 'flag']},
        'scaling_list_enabled_flag': {'python_name': ['scaling', 'list', 'enabled', 'flag']},
        'sps_scaling_list_data_present_flag': {'python_name': ['sps', 'scaling', 'list', 'data', 'present', 'flag']},
        'amp_enabled_flag': {'python_name': ['amp', 'enabled', 'flag']},
        'sample_adaptive_offset_enabled_flag': {'python_name': ['sample', 'adaptive', 'offset', 'enabled', 'flag']},
        'pcm_enabled_flag': {'python_name': ['pcm', 'enabled', 'flag']},
        'pcm_loop_filter_disabled_flag': {'python_name': ['pcm', 'loop', 'filter', 'disabled', 'flag']},
        'long_term_ref_pics_present_flag': {'python_name': ['long', 'term', 'ref', 'pics', 'present', 'flag']},
        'sps_temporal_mvp_enabled_flag': {'python_name': ['sps', 'temporal', 'mvp', 'enabled', 'flag']},
        'strong_intra_smoothing_enabled_flag': {'python_name': ['strong', 'intra', 'smoothing', 'enabled', 'flag']},
        'vui_parameters_present_flag': {'python_name': ['vui', 'parameters', 'present', 'flag']},
        'sps_extension_present_flag': {'python_name': ['sps', 'extension', 'present', 'flag']},
        'sps_range_extension_flag': {'python_name': ['sps', 'range', 'extension', 'flag']},
        'transform_skip_rotation_enabled_flag': {'python_name': ['transform', 'skip', 'rotation', 'enabled', 'flag']},
        'transform_skip_context_enabled_flag': {'python_name': ['transform', 'skip', 'context', 'enabled', 'flag']},
        'implicit_rdpcm_enabled_flag': {'python_name': ['implicit', 'rdpcm', 'enabled', 'flag']},
        'explicit_rdpcm_enabled_flag': {'python_name': ['explicit', 'rdpcm', 'enabled', 'flag']},
        'extended_precision_processing_flag': {'python_name': ['extended', 'precision', 'processing', 'flag']},
        'intra_smoothing_disabled_flag': {'python_name': ['intra', 'smoothing', 'disabled', 'flag']},
        'high_precision_offsets_enabled_flag': {'python_name': ['high', 'precision', 'offsets', 'enabled', 'flag']},
        'persistent_rice_adaptation_enabled_flag': {'python_name': ['persistent', 'rice', 'adaptation', 'enabled', 'flag']},
        'cabac_bypass_alignment_enabled_flag': {'python_name': ['cabac', 'bypass', 'alignment', 'enabled', 'flag']},
        'sps_scc_extension_flag': {'python_name': ['sps', 'scc', 'extension', 'flag']},
        'sps_curr_pic_ref_enabled_flag': {'python_name': ['sps', 'curr', 'pic', 'ref', 'enabled', 'flag']},
        'palette_mode_enabled_flag': {'python_name': ['palette', 'mode', 'enabled', 'flag']},
        'sps_palette_predictor_initializers_present_flag': {'python_name': ['sps', 'palette', 'predictor', 'initializers', 'present', 'flag']},
        'intra_boundary_filtering_disabled_flag': {'python_name': ['intra', 'boundary', 'filtering', 'disabled', 'flag']},
    }
}
