import ctypes

class VkDeviceCreateInfo(ctypes.Structure):
    _init_ = []
    _extends_ = set()
    _extended_by_ = {
        'VkDeviceDeviceMemoryReportCreateInfoEXT',
        'VkDeviceDiagnosticsConfigCreateInfoNV',
        'VkDeviceGroupDeviceCreateInfo',
        'VkDeviceMemoryOverallocationCreateInfoAMD',
        'VkDevicePrivateDataCreateInfo',
        'VkDeviceQueueShaderCoreControlCreateInfoARM',
        'VkPhysicalDevice16BitStorageFeatures',
        'VkPhysicalDevice4444FormatsFeaturesEXT',
        'VkPhysicalDevice8BitStorageFeatures',
        'VkPhysicalDeviceASTCDecodeFeaturesEXT',
        'VkPhysicalDeviceAccelerationStructureFeaturesKHR',
        'VkPhysicalDeviceAddressBindingReportFeaturesEXT',
        'VkPhysicalDeviceAmigoProfilingFeaturesSEC',
        'VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXT',
        'VkPhysicalDeviceAttachmentFeedbackLoopLayoutFeaturesEXT',
        'VkPhysicalDeviceBlendOperationAdvancedFeaturesEXT',
        'VkPhysicalDeviceBorderColorSwizzleFeaturesEXT',
        'VkPhysicalDeviceBufferDeviceAddressFeatures',
        'VkPhysicalDeviceBufferDeviceAddressFeaturesEXT',
        'VkPhysicalDeviceClusterCullingShaderFeaturesHUAWEI',
        'VkPhysicalDeviceCoherentMemoryFeaturesAMD',
        'VkPhysicalDeviceColorWriteEnableFeaturesEXT',
        'VkPhysicalDeviceComputeShaderDerivativesFeaturesNV',
        'VkPhysicalDeviceConditionalRenderingFeaturesEXT',
        'VkPhysicalDeviceCooperativeMatrixFeaturesKHR',
        'VkPhysicalDeviceCooperativeMatrixFeaturesNV',
        'VkPhysicalDeviceCopyMemoryIndirectFeaturesNV',
        'VkPhysicalDeviceCornerSampledImageFeaturesNV',
        'VkPhysicalDeviceCoverageReductionModeFeaturesNV',
        'VkPhysicalDeviceCubicClampFeaturesQCOM',
        'VkPhysicalDeviceCubicWeightsFeaturesQCOM',
        'VkPhysicalDeviceCudaKernelLaunchFeaturesNV',
        'VkPhysicalDeviceCustomBorderColorFeaturesEXT',
        'VkPhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV',
        'VkPhysicalDeviceDepthBiasControlFeaturesEXT',
        'VkPhysicalDeviceDepthClampZeroOneFeaturesEXT',
        'VkPhysicalDeviceDepthClipControlFeaturesEXT',
        'VkPhysicalDeviceDepthClipEnableFeaturesEXT',
        'VkPhysicalDeviceDescriptorBufferFeaturesEXT',
        'VkPhysicalDeviceDescriptorIndexingFeatures',
        'VkPhysicalDeviceDescriptorPoolOverallocationFeaturesNV',
        'VkPhysicalDeviceDescriptorSetHostMappingFeaturesVALVE',
        'VkPhysicalDeviceDeviceGeneratedCommandsComputeFeaturesNV',
        'VkPhysicalDeviceDeviceGeneratedCommandsFeaturesNV',
        'VkPhysicalDeviceDeviceMemoryReportFeaturesEXT',
        'VkPhysicalDeviceDiagnosticsConfigFeaturesNV',
        'VkPhysicalDeviceDisplacementMicromapFeaturesNV',
        'VkPhysicalDeviceDynamicRenderingFeatures',
        'VkPhysicalDeviceDynamicRenderingLocalReadFeaturesKHR',
        'VkPhysicalDeviceDynamicRenderingUnusedAttachmentsFeaturesEXT',
        'VkPhysicalDeviceExclusiveScissorFeaturesNV',
        'VkPhysicalDeviceExtendedDynamicState2FeaturesEXT',
        'VkPhysicalDeviceExtendedDynamicState3FeaturesEXT',
        'VkPhysicalDeviceExtendedDynamicStateFeaturesEXT',
        'VkPhysicalDeviceExtendedSparseAddressSpaceFeaturesNV',
        'VkPhysicalDeviceExternalFormatResolveFeaturesANDROID',
        'VkPhysicalDeviceExternalMemoryRDMAFeaturesNV',
        'VkPhysicalDeviceExternalMemoryScreenBufferFeaturesQNX',
        'VkPhysicalDeviceFaultFeaturesEXT',
        'VkPhysicalDeviceFeatures2',
        'VkPhysicalDeviceFragmentDensityMap2FeaturesEXT',
        'VkPhysicalDeviceFragmentDensityMapFeaturesEXT',
        'VkPhysicalDeviceFragmentDensityMapOffsetFeaturesQCOM',
        'VkPhysicalDeviceFragmentShaderBarycentricFeaturesKHR',
        'VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT',
        'VkPhysicalDeviceFragmentShadingRateEnumsFeaturesNV',
        'VkPhysicalDeviceFragmentShadingRateFeaturesKHR',
        'VkPhysicalDeviceFrameBoundaryFeaturesEXT',
        'VkPhysicalDeviceGlobalPriorityQueryFeaturesKHR',
        'VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT',
        'VkPhysicalDeviceHostImageCopyFeaturesEXT',
        'VkPhysicalDeviceHostQueryResetFeatures',
        'VkPhysicalDeviceImage2DViewOf3DFeaturesEXT',
        'VkPhysicalDeviceImageAlignmentControlFeaturesMESA',
        'VkPhysicalDeviceImageCompressionControlFeaturesEXT',
        'VkPhysicalDeviceImageCompressionControlSwapchainFeaturesEXT',
        'VkPhysicalDeviceImageProcessing2FeaturesQCOM',
        'VkPhysicalDeviceImageProcessingFeaturesQCOM',
        'VkPhysicalDeviceImageRobustnessFeatures',
        'VkPhysicalDeviceImageSlicedViewOf3DFeaturesEXT',
        'VkPhysicalDeviceImageViewMinLodFeaturesEXT',
        'VkPhysicalDeviceImagelessFramebufferFeatures',
        'VkPhysicalDeviceIndexTypeUint8FeaturesKHR',
        'VkPhysicalDeviceInheritedViewportScissorFeaturesNV',
        'VkPhysicalDeviceInlineUniformBlockFeatures',
        'VkPhysicalDeviceInvocationMaskFeaturesHUAWEI',
        'VkPhysicalDeviceLegacyDitheringFeaturesEXT',
        'VkPhysicalDeviceLegacyVertexAttributesFeaturesEXT',
        'VkPhysicalDeviceLineRasterizationFeaturesKHR',
        'VkPhysicalDeviceLinearColorAttachmentFeaturesNV',
        'VkPhysicalDeviceMaintenance4Features',
        'VkPhysicalDeviceMaintenance5FeaturesKHR',
        'VkPhysicalDeviceMaintenance6FeaturesKHR',
        'VkPhysicalDeviceMaintenance7FeaturesKHR',
        'VkPhysicalDeviceMapMemoryPlacedFeaturesEXT',
        'VkPhysicalDeviceMemoryDecompressionFeaturesNV',
        'VkPhysicalDeviceMemoryPriorityFeaturesEXT',
        'VkPhysicalDeviceMeshShaderFeaturesEXT',
        'VkPhysicalDeviceMeshShaderFeaturesNV',
        'VkPhysicalDeviceMultiDrawFeaturesEXT',
        'VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT',
        'VkPhysicalDeviceMultiviewFeatures',
        'VkPhysicalDeviceMultiviewPerViewRenderAreasFeaturesQCOM',
        'VkPhysicalDeviceMultiviewPerViewViewportsFeaturesQCOM',
        'VkPhysicalDeviceMutableDescriptorTypeFeaturesEXT',
        'VkPhysicalDeviceNestedCommandBufferFeaturesEXT',
        'VkPhysicalDeviceNonSeamlessCubeMapFeaturesEXT',
        'VkPhysicalDeviceOpacityMicromapFeaturesEXT',
        'VkPhysicalDeviceOpticalFlowFeaturesNV',
        'VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT',
        'VkPhysicalDevicePerStageDescriptorSetFeaturesNV',
        'VkPhysicalDevicePerformanceQueryFeaturesKHR',
        'VkPhysicalDevicePipelineCreationCacheControlFeatures',
        'VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR',
        'VkPhysicalDevicePipelineLibraryGroupHandlesFeaturesEXT',
        'VkPhysicalDevicePipelinePropertiesFeaturesEXT',
        'VkPhysicalDevicePipelineProtectedAccessFeaturesEXT',
        'VkPhysicalDevicePipelineRobustnessFeaturesEXT',
        'VkPhysicalDevicePortabilitySubsetFeaturesKHR',
        'VkPhysicalDevicePresentBarrierFeaturesNV',
        'VkPhysicalDevicePresentIdFeaturesKHR',
        'VkPhysicalDevicePresentWaitFeaturesKHR',
        'VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT',
        'VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT',
        'VkPhysicalDevicePrivateDataFeatures',
        'VkPhysicalDeviceProtectedMemoryFeatures',
        'VkPhysicalDeviceProvokingVertexFeaturesEXT',
        'VkPhysicalDeviceRGBA10X6FormatsFeaturesEXT',
        'VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT',
        'VkPhysicalDeviceRawAccessChainsFeaturesNV',
        'VkPhysicalDeviceRayQueryFeaturesKHR',
        'VkPhysicalDeviceRayTracingInvocationReorderFeaturesNV',
        'VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR',
        'VkPhysicalDeviceRayTracingMotionBlurFeaturesNV',
        'VkPhysicalDeviceRayTracingPipelineFeaturesKHR',
        'VkPhysicalDeviceRayTracingPositionFetchFeaturesKHR',
        'VkPhysicalDeviceRayTracingValidationFeaturesNV',
        'VkPhysicalDeviceRelaxedLineRasterizationFeaturesIMG',
        'VkPhysicalDeviceRenderPassStripedFeaturesARM',
        'VkPhysicalDeviceRepresentativeFragmentTestFeaturesNV',
        'VkPhysicalDeviceRobustness2FeaturesEXT',
        'VkPhysicalDeviceSamplerYcbcrConversionFeatures',
        'VkPhysicalDeviceScalarBlockLayoutFeatures',
        'VkPhysicalDeviceSchedulingControlsFeaturesARM',
        'VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures',
        'VkPhysicalDeviceShaderAtomicFloat16VectorFeaturesNV',
        'VkPhysicalDeviceShaderAtomicFloat2FeaturesEXT',
        'VkPhysicalDeviceShaderAtomicFloatFeaturesEXT',
        'VkPhysicalDeviceShaderAtomicInt64Features',
        'VkPhysicalDeviceShaderClockFeaturesKHR',
        'VkPhysicalDeviceShaderCoreBuiltinsFeaturesARM',
        'VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures',
        'VkPhysicalDeviceShaderDrawParametersFeatures',
        'VkPhysicalDeviceShaderEarlyAndLateFragmentTestsFeaturesAMD',
        'VkPhysicalDeviceShaderEnqueueFeaturesAMDX',
        'VkPhysicalDeviceShaderExpectAssumeFeaturesKHR',
        'VkPhysicalDeviceShaderFloat16Int8Features',
        'VkPhysicalDeviceShaderFloatControls2FeaturesKHR',
        'VkPhysicalDeviceShaderImageAtomicInt64FeaturesEXT',
        'VkPhysicalDeviceShaderImageFootprintFeaturesNV',
        'VkPhysicalDeviceShaderIntegerDotProductFeatures',
        'VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL',
        'VkPhysicalDeviceShaderMaximalReconvergenceFeaturesKHR',
        'VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT',
        'VkPhysicalDeviceShaderObjectFeaturesEXT',
        'VkPhysicalDeviceShaderQuadControlFeaturesKHR',
        'VkPhysicalDeviceShaderRelaxedExtendedInstructionFeaturesKHR',
        'VkPhysicalDeviceShaderReplicatedCompositesFeaturesEXT',
        'VkPhysicalDeviceShaderSMBuiltinsFeaturesNV',
        'VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures',
        'VkPhysicalDeviceShaderSubgroupRotateFeaturesKHR',
        'VkPhysicalDeviceShaderSubgroupUniformControlFlowFeaturesKHR',
        'VkPhysicalDeviceShaderTerminateInvocationFeatures',
        'VkPhysicalDeviceShaderTileImageFeaturesEXT',
        'VkPhysicalDeviceShadingRateImageFeaturesNV',
        'VkPhysicalDeviceSubgroupSizeControlFeatures',
        'VkPhysicalDeviceSubpassMergeFeedbackFeaturesEXT',
        'VkPhysicalDeviceSubpassShadingFeaturesHUAWEI',
        'VkPhysicalDeviceSwapchainMaintenance1FeaturesEXT',
        'VkPhysicalDeviceSynchronization2Features',
        'VkPhysicalDeviceTexelBufferAlignmentFeaturesEXT',
        'VkPhysicalDeviceTextureCompressionASTCHDRFeatures',
        'VkPhysicalDeviceTilePropertiesFeaturesQCOM',
        'VkPhysicalDeviceTimelineSemaphoreFeatures',
        'VkPhysicalDeviceTransformFeedbackFeaturesEXT',
        'VkPhysicalDeviceUniformBufferStandardLayoutFeatures',
        'VkPhysicalDeviceVariablePointersFeatures',
        'VkPhysicalDeviceVertexAttributeDivisorFeaturesKHR',
        'VkPhysicalDeviceVertexInputDynamicStateFeaturesEXT',
        'VkPhysicalDeviceVideoMaintenance1FeaturesKHR',
        'VkPhysicalDeviceVulkan11Features',
        'VkPhysicalDeviceVulkan12Features',
        'VkPhysicalDeviceVulkan13Features',
        'VkPhysicalDeviceVulkanMemoryModelFeatures',
        'VkPhysicalDeviceWorkgroupMemoryExplicitLayoutFeaturesKHR',
        'VkPhysicalDeviceYcbcr2Plane444FormatsFeaturesEXT',
        'VkPhysicalDeviceYcbcrDegammaFeaturesQCOM',
        'VkPhysicalDeviceYcbcrImageArraysFeaturesEXT',
        'VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures',
    }
    _includes_ = {
        'VkDeviceQueueCreateInfo',
        'VkPhysicalDeviceFeatures',
    }
    _included_in_ = set()
    _input_of_ = {
        'vkCreateDevice',
    }
    _output_of_ = set()
    _python_name_ = {
        'sType': 'type',
        'pNext': 'next',
        'flags': 'flags',
        'queueCreateInfoCount': 'queue_create_info_count',
        'pQueueCreateInfos': 'queue_create_infos',
        'enabledLayerCount': 'enabled_layer_count',
        'ppEnabledLayerNames': 'enabled_layer_names',
        'enabledExtensionCount': 'enabled_extension_count',
        'ppEnabledExtensionNames': 'enabled_extension_names',
        'pEnabledFeatures': 'enabled_features',
    }
    _vk_versions_ = {
        (1, 0),
    }
    _vk_extensions_ = set()
    _vk_enum_ = {
        'sType': 'VkStructureType',
        'flags': 'VkDeviceCreateFlags',
    }
    _vk_structure_type_ = 'VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO'

    def __init__(self, *args, **kwargs):
        super().__init__()
        from .._vulkan_enum.VkStructureType import VkStructureType
        self.sType = VkStructureType.VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO
        for function in self._init_:
            function(self, *args, **kwargs)


from .VkDeviceQueueCreateInfo import VkDeviceQueueCreateInfo
from .VkPhysicalDeviceFeatures import VkPhysicalDeviceFeatures

VkDeviceCreateInfo._fields_ = [
    ('sType', ctypes.c_int),
    ('pNext', ctypes.c_void_p),
    ('flags', ctypes.c_uint32),
    ('queueCreateInfoCount', ctypes.c_uint32),
    ('pQueueCreateInfos', ctypes.POINTER(VkDeviceQueueCreateInfo)),
    ('enabledLayerCount', ctypes.c_uint32),
    ('ppEnabledLayerNames', ctypes.POINTER(ctypes.c_char_p)),
    ('enabledExtensionCount', ctypes.c_uint32),
    ('ppEnabledExtensionNames', ctypes.POINTER(ctypes.c_char_p)),
    ('pEnabledFeatures', ctypes.POINTER(VkPhysicalDeviceFeatures)),
]

VkDeviceCreateInfo._type_ = {
    'sType': ctypes.c_int,
    'pNext': ctypes.c_void_p,
    'flags': ctypes.c_uint32,
    'queueCreateInfoCount': ctypes.c_uint32,
    'pQueueCreateInfos': ctypes.POINTER(VkDeviceQueueCreateInfo),
    'enabledLayerCount': ctypes.c_uint32,
    'ppEnabledLayerNames': ctypes.POINTER(ctypes.c_char_p),
    'enabledExtensionCount': ctypes.c_uint32,
    'ppEnabledExtensionNames': ctypes.POINTER(ctypes.c_char_p),
    'pEnabledFeatures': ctypes.POINTER(VkPhysicalDeviceFeatures),
}
