import ctypes

class VkPhysicalDeviceVulkan13Properties(ctypes.Structure):
    _fields_ = [
        ('sType', ctypes.c_int),
        ('pNext', ctypes.c_void_p),
        ('minSubgroupSize', ctypes.c_uint32),
        ('maxSubgroupSize', ctypes.c_uint32),
        ('maxComputeWorkgroupSubgroups', ctypes.c_uint32),
        ('requiredSubgroupSizeStages', ctypes.c_uint32),
        ('maxInlineUniformBlockSize', ctypes.c_uint32),
        ('maxPerStageDescriptorInlineUniformBlocks', ctypes.c_uint32),
        ('maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks', ctypes.c_uint32),
        ('maxDescriptorSetInlineUniformBlocks', ctypes.c_uint32),
        ('maxDescriptorSetUpdateAfterBindInlineUniformBlocks', ctypes.c_uint32),
        ('maxInlineUniformTotalSize', ctypes.c_uint32),
        ('integerDotProduct8BitUnsignedAccelerated', ctypes.c_uint32),
        ('integerDotProduct8BitSignedAccelerated', ctypes.c_uint32),
        ('integerDotProduct8BitMixedSignednessAccelerated', ctypes.c_uint32),
        ('integerDotProduct4x8BitPackedUnsignedAccelerated', ctypes.c_uint32),
        ('integerDotProduct4x8BitPackedSignedAccelerated', ctypes.c_uint32),
        ('integerDotProduct4x8BitPackedMixedSignednessAccelerated', ctypes.c_uint32),
        ('integerDotProduct16BitUnsignedAccelerated', ctypes.c_uint32),
        ('integerDotProduct16BitSignedAccelerated', ctypes.c_uint32),
        ('integerDotProduct16BitMixedSignednessAccelerated', ctypes.c_uint32),
        ('integerDotProduct32BitUnsignedAccelerated', ctypes.c_uint32),
        ('integerDotProduct32BitSignedAccelerated', ctypes.c_uint32),
        ('integerDotProduct32BitMixedSignednessAccelerated', ctypes.c_uint32),
        ('integerDotProduct64BitUnsignedAccelerated', ctypes.c_uint32),
        ('integerDotProduct64BitSignedAccelerated', ctypes.c_uint32),
        ('integerDotProduct64BitMixedSignednessAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating8BitUnsignedAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating8BitSignedAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating16BitUnsignedAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating16BitSignedAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating32BitUnsignedAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating32BitSignedAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating64BitUnsignedAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating64BitSignedAccelerated', ctypes.c_uint32),
        ('integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated', ctypes.c_uint32),
        ('storageTexelBufferOffsetAlignmentBytes', ctypes.c_uint64),
        ('storageTexelBufferOffsetSingleTexelAlignment', ctypes.c_uint32),
        ('uniformTexelBufferOffsetAlignmentBytes', ctypes.c_uint64),
        ('uniformTexelBufferOffsetSingleTexelAlignment', ctypes.c_uint32),
        ('maxBufferSize', ctypes.c_uint64),
    ]

    _init_ = []
    _extends_ = {
        'VkPhysicalDeviceProperties2',
    }
    _extended_by_ = set()
    _includes_ = set()
    _included_in_ = set()
    _input_of_ = set()
    _output_of_ = set()
    _python_name_ = {
        'sType': 'type',
        'pNext': 'next',
        'minSubgroupSize': 'min_subgroup_size',
        'maxSubgroupSize': 'max_subgroup_size',
        'maxComputeWorkgroupSubgroups': 'max_compute_workgroup_subgroups',
        'requiredSubgroupSizeStages': 'required_subgroup_size_stages',
        'maxInlineUniformBlockSize': 'max_inline_uniform_block_size',
        'maxPerStageDescriptorInlineUniformBlocks': 'max_per_stage_descriptor_inline_uniform_blocks',
        'maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks': 'max_per_stage_descriptor_update_after_bind_inline_uniform_blocks',
        'maxDescriptorSetInlineUniformBlocks': 'max_descriptor_set_inline_uniform_blocks',
        'maxDescriptorSetUpdateAfterBindInlineUniformBlocks': 'max_descriptor_set_update_after_bind_inline_uniform_blocks',
        'maxInlineUniformTotalSize': 'max_inline_uniform_total_size',
        'integerDotProduct8BitUnsignedAccelerated': 'integer_dot_product8_bit_unsigned_accelerated',
        'integerDotProduct8BitSignedAccelerated': 'integer_dot_product8_bit_signed_accelerated',
        'integerDotProduct8BitMixedSignednessAccelerated': 'integer_dot_product8_bit_mixed_signedness_accelerated',
        'integerDotProduct4x8BitPackedUnsignedAccelerated': 'integer_dot_product4x8_bit_packed_unsigned_accelerated',
        'integerDotProduct4x8BitPackedSignedAccelerated': 'integer_dot_product4x8_bit_packed_signed_accelerated',
        'integerDotProduct4x8BitPackedMixedSignednessAccelerated': 'integer_dot_product4x8_bit_packed_mixed_signedness_accelerated',
        'integerDotProduct16BitUnsignedAccelerated': 'integer_dot_product16_bit_unsigned_accelerated',
        'integerDotProduct16BitSignedAccelerated': 'integer_dot_product16_bit_signed_accelerated',
        'integerDotProduct16BitMixedSignednessAccelerated': 'integer_dot_product16_bit_mixed_signedness_accelerated',
        'integerDotProduct32BitUnsignedAccelerated': 'integer_dot_product32_bit_unsigned_accelerated',
        'integerDotProduct32BitSignedAccelerated': 'integer_dot_product32_bit_signed_accelerated',
        'integerDotProduct32BitMixedSignednessAccelerated': 'integer_dot_product32_bit_mixed_signedness_accelerated',
        'integerDotProduct64BitUnsignedAccelerated': 'integer_dot_product64_bit_unsigned_accelerated',
        'integerDotProduct64BitSignedAccelerated': 'integer_dot_product64_bit_signed_accelerated',
        'integerDotProduct64BitMixedSignednessAccelerated': 'integer_dot_product64_bit_mixed_signedness_accelerated',
        'integerDotProductAccumulatingSaturating8BitUnsignedAccelerated': 'integer_dot_product_accumulating_saturating8_bit_unsigned_accelerated',
        'integerDotProductAccumulatingSaturating8BitSignedAccelerated': 'integer_dot_product_accumulating_saturating8_bit_signed_accelerated',
        'integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated': 'integer_dot_product_accumulating_saturating8_bit_mixed_signedness_accelerated',
        'integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated': 'integer_dot_product_accumulating_saturating4x8_bit_packed_unsigned_accelerated',
        'integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated': 'integer_dot_product_accumulating_saturating4x8_bit_packed_signed_accelerated',
        'integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated': 'integer_dot_product_accumulating_saturating4x8_bit_packed_mixed_signedness_accelerated',
        'integerDotProductAccumulatingSaturating16BitUnsignedAccelerated': 'integer_dot_product_accumulating_saturating16_bit_unsigned_accelerated',
        'integerDotProductAccumulatingSaturating16BitSignedAccelerated': 'integer_dot_product_accumulating_saturating16_bit_signed_accelerated',
        'integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated': 'integer_dot_product_accumulating_saturating16_bit_mixed_signedness_accelerated',
        'integerDotProductAccumulatingSaturating32BitUnsignedAccelerated': 'integer_dot_product_accumulating_saturating32_bit_unsigned_accelerated',
        'integerDotProductAccumulatingSaturating32BitSignedAccelerated': 'integer_dot_product_accumulating_saturating32_bit_signed_accelerated',
        'integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated': 'integer_dot_product_accumulating_saturating32_bit_mixed_signedness_accelerated',
        'integerDotProductAccumulatingSaturating64BitUnsignedAccelerated': 'integer_dot_product_accumulating_saturating64_bit_unsigned_accelerated',
        'integerDotProductAccumulatingSaturating64BitSignedAccelerated': 'integer_dot_product_accumulating_saturating64_bit_signed_accelerated',
        'integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated': 'integer_dot_product_accumulating_saturating64_bit_mixed_signedness_accelerated',
        'storageTexelBufferOffsetAlignmentBytes': 'storage_texel_buffer_offset_alignment_bytes',
        'storageTexelBufferOffsetSingleTexelAlignment': 'storage_texel_buffer_offset_single_texel_alignment',
        'uniformTexelBufferOffsetAlignmentBytes': 'uniform_texel_buffer_offset_alignment_bytes',
        'uniformTexelBufferOffsetSingleTexelAlignment': 'uniform_texel_buffer_offset_single_texel_alignment',
        'maxBufferSize': 'max_buffer_size',
    }
    _vk_versions_ = {
        (1, 3),
    }
    _vk_extensions_ = set()
    _vk_enum_ = {
        'sType': 'VkStructureType',
        'requiredSubgroupSizeStages': 'VkShaderStageFlags',
    }
    _vk_structure_type_ = 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES'

    def __init__(self, *args, **kwargs):
        super().__init__()
        from .._vulkan_enum.VkStructureType import VkStructureType
        self.sType = VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES
        for function in self._init_:
            function(self, *args, **kwargs)

VkPhysicalDeviceVulkan13Properties._type_ = {
    'sType': ctypes.c_int,
    'pNext': ctypes.c_void_p,
    'minSubgroupSize': ctypes.c_uint32,
    'maxSubgroupSize': ctypes.c_uint32,
    'maxComputeWorkgroupSubgroups': ctypes.c_uint32,
    'requiredSubgroupSizeStages': ctypes.c_uint32,
    'maxInlineUniformBlockSize': ctypes.c_uint32,
    'maxPerStageDescriptorInlineUniformBlocks': ctypes.c_uint32,
    'maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks': ctypes.c_uint32,
    'maxDescriptorSetInlineUniformBlocks': ctypes.c_uint32,
    'maxDescriptorSetUpdateAfterBindInlineUniformBlocks': ctypes.c_uint32,
    'maxInlineUniformTotalSize': ctypes.c_uint32,
    'integerDotProduct8BitUnsignedAccelerated': ctypes.c_uint32,
    'integerDotProduct8BitSignedAccelerated': ctypes.c_uint32,
    'integerDotProduct8BitMixedSignednessAccelerated': ctypes.c_uint32,
    'integerDotProduct4x8BitPackedUnsignedAccelerated': ctypes.c_uint32,
    'integerDotProduct4x8BitPackedSignedAccelerated': ctypes.c_uint32,
    'integerDotProduct4x8BitPackedMixedSignednessAccelerated': ctypes.c_uint32,
    'integerDotProduct16BitUnsignedAccelerated': ctypes.c_uint32,
    'integerDotProduct16BitSignedAccelerated': ctypes.c_uint32,
    'integerDotProduct16BitMixedSignednessAccelerated': ctypes.c_uint32,
    'integerDotProduct32BitUnsignedAccelerated': ctypes.c_uint32,
    'integerDotProduct32BitSignedAccelerated': ctypes.c_uint32,
    'integerDotProduct32BitMixedSignednessAccelerated': ctypes.c_uint32,
    'integerDotProduct64BitUnsignedAccelerated': ctypes.c_uint32,
    'integerDotProduct64BitSignedAccelerated': ctypes.c_uint32,
    'integerDotProduct64BitMixedSignednessAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating8BitUnsignedAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating8BitSignedAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating16BitUnsignedAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating16BitSignedAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating32BitUnsignedAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating32BitSignedAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating64BitUnsignedAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating64BitSignedAccelerated': ctypes.c_uint32,
    'integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated': ctypes.c_uint32,
    'storageTexelBufferOffsetAlignmentBytes': ctypes.c_uint64,
    'storageTexelBufferOffsetSingleTexelAlignment': ctypes.c_uint32,
    'uniformTexelBufferOffsetAlignmentBytes': ctypes.c_uint64,
    'uniformTexelBufferOffsetSingleTexelAlignment': ctypes.c_uint32,
    'maxBufferSize': ctypes.c_uint64,
}
