import ctypes

class VkPhysicalDeviceLimits(ctypes.Structure):
    _fields_ = [
        ('maxImageDimension1D', ctypes.c_uint32),
        ('maxImageDimension2D', ctypes.c_uint32),
        ('maxImageDimension3D', ctypes.c_uint32),
        ('maxImageDimensionCube', ctypes.c_uint32),
        ('maxImageArrayLayers', ctypes.c_uint32),
        ('maxTexelBufferElements', ctypes.c_uint32),
        ('maxUniformBufferRange', ctypes.c_uint32),
        ('maxStorageBufferRange', ctypes.c_uint32),
        ('maxPushConstantsSize', ctypes.c_uint32),
        ('maxMemoryAllocationCount', ctypes.c_uint32),
        ('maxSamplerAllocationCount', ctypes.c_uint32),
        ('bufferImageGranularity', ctypes.c_uint64),
        ('sparseAddressSpaceSize', ctypes.c_uint64),
        ('maxBoundDescriptorSets', ctypes.c_uint32),
        ('maxPerStageDescriptorSamplers', ctypes.c_uint32),
        ('maxPerStageDescriptorUniformBuffers', ctypes.c_uint32),
        ('maxPerStageDescriptorStorageBuffers', ctypes.c_uint32),
        ('maxPerStageDescriptorSampledImages', ctypes.c_uint32),
        ('maxPerStageDescriptorStorageImages', ctypes.c_uint32),
        ('maxPerStageDescriptorInputAttachments', ctypes.c_uint32),
        ('maxPerStageResources', ctypes.c_uint32),
        ('maxDescriptorSetSamplers', ctypes.c_uint32),
        ('maxDescriptorSetUniformBuffers', ctypes.c_uint32),
        ('maxDescriptorSetUniformBuffersDynamic', ctypes.c_uint32),
        ('maxDescriptorSetStorageBuffers', ctypes.c_uint32),
        ('maxDescriptorSetStorageBuffersDynamic', ctypes.c_uint32),
        ('maxDescriptorSetSampledImages', ctypes.c_uint32),
        ('maxDescriptorSetStorageImages', ctypes.c_uint32),
        ('maxDescriptorSetInputAttachments', ctypes.c_uint32),
        ('maxVertexInputAttributes', ctypes.c_uint32),
        ('maxVertexInputBindings', ctypes.c_uint32),
        ('maxVertexInputAttributeOffset', ctypes.c_uint32),
        ('maxVertexInputBindingStride', ctypes.c_uint32),
        ('maxVertexOutputComponents', ctypes.c_uint32),
        ('maxTessellationGenerationLevel', ctypes.c_uint32),
        ('maxTessellationPatchSize', ctypes.c_uint32),
        ('maxTessellationControlPerVertexInputComponents', ctypes.c_uint32),
        ('maxTessellationControlPerVertexOutputComponents', ctypes.c_uint32),
        ('maxTessellationControlPerPatchOutputComponents', ctypes.c_uint32),
        ('maxTessellationControlTotalOutputComponents', ctypes.c_uint32),
        ('maxTessellationEvaluationInputComponents', ctypes.c_uint32),
        ('maxTessellationEvaluationOutputComponents', ctypes.c_uint32),
        ('maxGeometryShaderInvocations', ctypes.c_uint32),
        ('maxGeometryInputComponents', ctypes.c_uint32),
        ('maxGeometryOutputComponents', ctypes.c_uint32),
        ('maxGeometryOutputVertices', ctypes.c_uint32),
        ('maxGeometryTotalOutputComponents', ctypes.c_uint32),
        ('maxFragmentInputComponents', ctypes.c_uint32),
        ('maxFragmentOutputAttachments', ctypes.c_uint32),
        ('maxFragmentDualSrcAttachments', ctypes.c_uint32),
        ('maxFragmentCombinedOutputResources', ctypes.c_uint32),
        ('maxComputeSharedMemorySize', ctypes.c_uint32),
        ('maxComputeWorkGroupCount', ctypes.ARRAY(ctypes.c_uint32, 3)),
        ('maxComputeWorkGroupInvocations', ctypes.c_uint32),
        ('maxComputeWorkGroupSize', ctypes.ARRAY(ctypes.c_uint32, 3)),
        ('subPixelPrecisionBits', ctypes.c_uint32),
        ('subTexelPrecisionBits', ctypes.c_uint32),
        ('mipmapPrecisionBits', ctypes.c_uint32),
        ('maxDrawIndexedIndexValue', ctypes.c_uint32),
        ('maxDrawIndirectCount', ctypes.c_uint32),
        ('maxSamplerLodBias', ctypes.c_float),
        ('maxSamplerAnisotropy', ctypes.c_float),
        ('maxViewports', ctypes.c_uint32),
        ('maxViewportDimensions', ctypes.ARRAY(ctypes.c_uint32, 2)),
        ('viewportBoundsRange', ctypes.ARRAY(ctypes.c_float, 2)),
        ('viewportSubPixelBits', ctypes.c_uint32),
        ('minMemoryMapAlignment', ctypes.c_size_t),
        ('minTexelBufferOffsetAlignment', ctypes.c_uint64),
        ('minUniformBufferOffsetAlignment', ctypes.c_uint64),
        ('minStorageBufferOffsetAlignment', ctypes.c_uint64),
        ('minTexelOffset', ctypes.c_int32),
        ('maxTexelOffset', ctypes.c_uint32),
        ('minTexelGatherOffset', ctypes.c_int32),
        ('maxTexelGatherOffset', ctypes.c_uint32),
        ('minInterpolationOffset', ctypes.c_float),
        ('maxInterpolationOffset', ctypes.c_float),
        ('subPixelInterpolationOffsetBits', ctypes.c_uint32),
        ('maxFramebufferWidth', ctypes.c_uint32),
        ('maxFramebufferHeight', ctypes.c_uint32),
        ('maxFramebufferLayers', ctypes.c_uint32),
        ('framebufferColorSampleCounts', ctypes.c_uint32),
        ('framebufferDepthSampleCounts', ctypes.c_uint32),
        ('framebufferStencilSampleCounts', ctypes.c_uint32),
        ('framebufferNoAttachmentsSampleCounts', ctypes.c_uint32),
        ('maxColorAttachments', ctypes.c_uint32),
        ('sampledImageColorSampleCounts', ctypes.c_uint32),
        ('sampledImageIntegerSampleCounts', ctypes.c_uint32),
        ('sampledImageDepthSampleCounts', ctypes.c_uint32),
        ('sampledImageStencilSampleCounts', ctypes.c_uint32),
        ('storageImageSampleCounts', ctypes.c_uint32),
        ('maxSampleMaskWords', ctypes.c_uint32),
        ('timestampComputeAndGraphics', ctypes.c_uint32),
        ('timestampPeriod', ctypes.c_float),
        ('maxClipDistances', ctypes.c_uint32),
        ('maxCullDistances', ctypes.c_uint32),
        ('maxCombinedClipAndCullDistances', ctypes.c_uint32),
        ('discreteQueuePriorities', ctypes.c_uint32),
        ('pointSizeRange', ctypes.ARRAY(ctypes.c_float, 2)),
        ('lineWidthRange', ctypes.ARRAY(ctypes.c_float, 2)),
        ('pointSizeGranularity', ctypes.c_float),
        ('lineWidthGranularity', ctypes.c_float),
        ('strictLines', ctypes.c_uint32),
        ('standardSampleLocations', ctypes.c_uint32),
        ('optimalBufferCopyOffsetAlignment', ctypes.c_uint64),
        ('optimalBufferCopyRowPitchAlignment', ctypes.c_uint64),
        ('nonCoherentAtomSize', ctypes.c_uint64),
    ]

    _init_ = []
    _extends_ = set()
    _extended_by_ = set()
    _includes_ = set()
    _included_in_ = {
        'VkPhysicalDeviceProperties',
    }
    _input_of_ = set()
    _output_of_ = set()
    _python_name_ = {
        'maxImageDimension1D': 'max_image_dimension1_d',
        'maxImageDimension2D': 'max_image_dimension2_d',
        'maxImageDimension3D': 'max_image_dimension3_d',
        'maxImageDimensionCube': 'max_image_dimension_cube',
        'maxImageArrayLayers': 'max_image_array_layers',
        'maxTexelBufferElements': 'max_texel_buffer_elements',
        'maxUniformBufferRange': 'max_uniform_buffer_range',
        'maxStorageBufferRange': 'max_storage_buffer_range',
        'maxPushConstantsSize': 'max_push_constants_size',
        'maxMemoryAllocationCount': 'max_memory_allocation_count',
        'maxSamplerAllocationCount': 'max_sampler_allocation_count',
        'bufferImageGranularity': 'buffer_image_granularity',
        'sparseAddressSpaceSize': 'sparse_address_space_size',
        'maxBoundDescriptorSets': 'max_bound_descriptor_sets',
        'maxPerStageDescriptorSamplers': 'max_per_stage_descriptor_samplers',
        'maxPerStageDescriptorUniformBuffers': 'max_per_stage_descriptor_uniform_buffers',
        'maxPerStageDescriptorStorageBuffers': 'max_per_stage_descriptor_storage_buffers',
        'maxPerStageDescriptorSampledImages': 'max_per_stage_descriptor_sampled_images',
        'maxPerStageDescriptorStorageImages': 'max_per_stage_descriptor_storage_images',
        'maxPerStageDescriptorInputAttachments': 'max_per_stage_descriptor_input_attachments',
        'maxPerStageResources': 'max_per_stage_resources',
        'maxDescriptorSetSamplers': 'max_descriptor_set_samplers',
        'maxDescriptorSetUniformBuffers': 'max_descriptor_set_uniform_buffers',
        'maxDescriptorSetUniformBuffersDynamic': 'max_descriptor_set_uniform_buffers_dynamic',
        'maxDescriptorSetStorageBuffers': 'max_descriptor_set_storage_buffers',
        'maxDescriptorSetStorageBuffersDynamic': 'max_descriptor_set_storage_buffers_dynamic',
        'maxDescriptorSetSampledImages': 'max_descriptor_set_sampled_images',
        'maxDescriptorSetStorageImages': 'max_descriptor_set_storage_images',
        'maxDescriptorSetInputAttachments': 'max_descriptor_set_input_attachments',
        'maxVertexInputAttributes': 'max_vertex_input_attributes',
        'maxVertexInputBindings': 'max_vertex_input_bindings',
        'maxVertexInputAttributeOffset': 'max_vertex_input_attribute_offset',
        'maxVertexInputBindingStride': 'max_vertex_input_binding_stride',
        'maxVertexOutputComponents': 'max_vertex_output_components',
        'maxTessellationGenerationLevel': 'max_tessellation_generation_level',
        'maxTessellationPatchSize': 'max_tessellation_patch_size',
        'maxTessellationControlPerVertexInputComponents': 'max_tessellation_control_per_vertex_input_components',
        'maxTessellationControlPerVertexOutputComponents': 'max_tessellation_control_per_vertex_output_components',
        'maxTessellationControlPerPatchOutputComponents': 'max_tessellation_control_per_patch_output_components',
        'maxTessellationControlTotalOutputComponents': 'max_tessellation_control_total_output_components',
        'maxTessellationEvaluationInputComponents': 'max_tessellation_evaluation_input_components',
        'maxTessellationEvaluationOutputComponents': 'max_tessellation_evaluation_output_components',
        'maxGeometryShaderInvocations': 'max_geometry_shader_invocations',
        'maxGeometryInputComponents': 'max_geometry_input_components',
        'maxGeometryOutputComponents': 'max_geometry_output_components',
        'maxGeometryOutputVertices': 'max_geometry_output_vertices',
        'maxGeometryTotalOutputComponents': 'max_geometry_total_output_components',
        'maxFragmentInputComponents': 'max_fragment_input_components',
        'maxFragmentOutputAttachments': 'max_fragment_output_attachments',
        'maxFragmentDualSrcAttachments': 'max_fragment_dual_src_attachments',
        'maxFragmentCombinedOutputResources': 'max_fragment_combined_output_resources',
        'maxComputeSharedMemorySize': 'max_compute_shared_memory_size',
        'maxComputeWorkGroupCount': 'max_compute_work_group_count',
        'maxComputeWorkGroupInvocations': 'max_compute_work_group_invocations',
        'maxComputeWorkGroupSize': 'max_compute_work_group_size',
        'subPixelPrecisionBits': 'sub_pixel_precision_bits',
        'subTexelPrecisionBits': 'sub_texel_precision_bits',
        'mipmapPrecisionBits': 'mipmap_precision_bits',
        'maxDrawIndexedIndexValue': 'max_draw_indexed_index_value',
        'maxDrawIndirectCount': 'max_draw_indirect_count',
        'maxSamplerLodBias': 'max_sampler_lod_bias',
        'maxSamplerAnisotropy': 'max_sampler_anisotropy',
        'maxViewports': 'max_viewports',
        'maxViewportDimensions': 'max_viewport_dimensions',
        'viewportBoundsRange': 'viewport_bounds_range',
        'viewportSubPixelBits': 'viewport_sub_pixel_bits',
        'minMemoryMapAlignment': 'min_memory_map_alignment',
        'minTexelBufferOffsetAlignment': 'min_texel_buffer_offset_alignment',
        'minUniformBufferOffsetAlignment': 'min_uniform_buffer_offset_alignment',
        'minStorageBufferOffsetAlignment': 'min_storage_buffer_offset_alignment',
        'minTexelOffset': 'min_texel_offset',
        'maxTexelOffset': 'max_texel_offset',
        'minTexelGatherOffset': 'min_texel_gather_offset',
        'maxTexelGatherOffset': 'max_texel_gather_offset',
        'minInterpolationOffset': 'min_interpolation_offset',
        'maxInterpolationOffset': 'max_interpolation_offset',
        'subPixelInterpolationOffsetBits': 'sub_pixel_interpolation_offset_bits',
        'maxFramebufferWidth': 'max_framebuffer_width',
        'maxFramebufferHeight': 'max_framebuffer_height',
        'maxFramebufferLayers': 'max_framebuffer_layers',
        'framebufferColorSampleCounts': 'framebuffer_color_sample_counts',
        'framebufferDepthSampleCounts': 'framebuffer_depth_sample_counts',
        'framebufferStencilSampleCounts': 'framebuffer_stencil_sample_counts',
        'framebufferNoAttachmentsSampleCounts': 'framebuffer_no_attachments_sample_counts',
        'maxColorAttachments': 'max_color_attachments',
        'sampledImageColorSampleCounts': 'sampled_image_color_sample_counts',
        'sampledImageIntegerSampleCounts': 'sampled_image_integer_sample_counts',
        'sampledImageDepthSampleCounts': 'sampled_image_depth_sample_counts',
        'sampledImageStencilSampleCounts': 'sampled_image_stencil_sample_counts',
        'storageImageSampleCounts': 'storage_image_sample_counts',
        'maxSampleMaskWords': 'max_sample_mask_words',
        'timestampComputeAndGraphics': 'timestamp_compute_and_graphics',
        'timestampPeriod': 'timestamp_period',
        'maxClipDistances': 'max_clip_distances',
        'maxCullDistances': 'max_cull_distances',
        'maxCombinedClipAndCullDistances': 'max_combined_clip_and_cull_distances',
        'discreteQueuePriorities': 'discrete_queue_priorities',
        'pointSizeRange': 'point_size_range',
        'lineWidthRange': 'line_width_range',
        'pointSizeGranularity': 'point_size_granularity',
        'lineWidthGranularity': 'line_width_granularity',
        'strictLines': 'strict_lines',
        'standardSampleLocations': 'standard_sample_locations',
        'optimalBufferCopyOffsetAlignment': 'optimal_buffer_copy_offset_alignment',
        'optimalBufferCopyRowPitchAlignment': 'optimal_buffer_copy_row_pitch_alignment',
        'nonCoherentAtomSize': 'non_coherent_atom_size',
    }
    _vk_versions_ = {
        (1, 0),
    }
    _vk_extensions_ = set()
    _vk_enum_ = {
        'framebufferColorSampleCounts': 'VkSampleCountFlags',
        'framebufferDepthSampleCounts': 'VkSampleCountFlags',
        'framebufferStencilSampleCounts': 'VkSampleCountFlags',
        'framebufferNoAttachmentsSampleCounts': 'VkSampleCountFlags',
        'sampledImageColorSampleCounts': 'VkSampleCountFlags',
        'sampledImageIntegerSampleCounts': 'VkSampleCountFlags',
        'sampledImageDepthSampleCounts': 'VkSampleCountFlags',
        'sampledImageStencilSampleCounts': 'VkSampleCountFlags',
        'storageImageSampleCounts': 'VkSampleCountFlags',
    }

    def __init__(self, *args, **kwargs):
        super().__init__()
        for function in self._init_:
            function(self, *args, **kwargs)

VkPhysicalDeviceLimits._type_ = {
    'maxImageDimension1D': ctypes.c_uint32,
    'maxImageDimension2D': ctypes.c_uint32,
    'maxImageDimension3D': ctypes.c_uint32,
    'maxImageDimensionCube': ctypes.c_uint32,
    'maxImageArrayLayers': ctypes.c_uint32,
    'maxTexelBufferElements': ctypes.c_uint32,
    'maxUniformBufferRange': ctypes.c_uint32,
    'maxStorageBufferRange': ctypes.c_uint32,
    'maxPushConstantsSize': ctypes.c_uint32,
    'maxMemoryAllocationCount': ctypes.c_uint32,
    'maxSamplerAllocationCount': ctypes.c_uint32,
    'bufferImageGranularity': ctypes.c_uint64,
    'sparseAddressSpaceSize': ctypes.c_uint64,
    'maxBoundDescriptorSets': ctypes.c_uint32,
    'maxPerStageDescriptorSamplers': ctypes.c_uint32,
    'maxPerStageDescriptorUniformBuffers': ctypes.c_uint32,
    'maxPerStageDescriptorStorageBuffers': ctypes.c_uint32,
    'maxPerStageDescriptorSampledImages': ctypes.c_uint32,
    'maxPerStageDescriptorStorageImages': ctypes.c_uint32,
    'maxPerStageDescriptorInputAttachments': ctypes.c_uint32,
    'maxPerStageResources': ctypes.c_uint32,
    'maxDescriptorSetSamplers': ctypes.c_uint32,
    'maxDescriptorSetUniformBuffers': ctypes.c_uint32,
    'maxDescriptorSetUniformBuffersDynamic': ctypes.c_uint32,
    'maxDescriptorSetStorageBuffers': ctypes.c_uint32,
    'maxDescriptorSetStorageBuffersDynamic': ctypes.c_uint32,
    'maxDescriptorSetSampledImages': ctypes.c_uint32,
    'maxDescriptorSetStorageImages': ctypes.c_uint32,
    'maxDescriptorSetInputAttachments': ctypes.c_uint32,
    'maxVertexInputAttributes': ctypes.c_uint32,
    'maxVertexInputBindings': ctypes.c_uint32,
    'maxVertexInputAttributeOffset': ctypes.c_uint32,
    'maxVertexInputBindingStride': ctypes.c_uint32,
    'maxVertexOutputComponents': ctypes.c_uint32,
    'maxTessellationGenerationLevel': ctypes.c_uint32,
    'maxTessellationPatchSize': ctypes.c_uint32,
    'maxTessellationControlPerVertexInputComponents': ctypes.c_uint32,
    'maxTessellationControlPerVertexOutputComponents': ctypes.c_uint32,
    'maxTessellationControlPerPatchOutputComponents': ctypes.c_uint32,
    'maxTessellationControlTotalOutputComponents': ctypes.c_uint32,
    'maxTessellationEvaluationInputComponents': ctypes.c_uint32,
    'maxTessellationEvaluationOutputComponents': ctypes.c_uint32,
    'maxGeometryShaderInvocations': ctypes.c_uint32,
    'maxGeometryInputComponents': ctypes.c_uint32,
    'maxGeometryOutputComponents': ctypes.c_uint32,
    'maxGeometryOutputVertices': ctypes.c_uint32,
    'maxGeometryTotalOutputComponents': ctypes.c_uint32,
    'maxFragmentInputComponents': ctypes.c_uint32,
    'maxFragmentOutputAttachments': ctypes.c_uint32,
    'maxFragmentDualSrcAttachments': ctypes.c_uint32,
    'maxFragmentCombinedOutputResources': ctypes.c_uint32,
    'maxComputeSharedMemorySize': ctypes.c_uint32,
    'maxComputeWorkGroupCount': ctypes.ARRAY(ctypes.c_uint32, 3),
    'maxComputeWorkGroupInvocations': ctypes.c_uint32,
    'maxComputeWorkGroupSize': ctypes.ARRAY(ctypes.c_uint32, 3),
    'subPixelPrecisionBits': ctypes.c_uint32,
    'subTexelPrecisionBits': ctypes.c_uint32,
    'mipmapPrecisionBits': ctypes.c_uint32,
    'maxDrawIndexedIndexValue': ctypes.c_uint32,
    'maxDrawIndirectCount': ctypes.c_uint32,
    'maxSamplerLodBias': ctypes.c_float,
    'maxSamplerAnisotropy': ctypes.c_float,
    'maxViewports': ctypes.c_uint32,
    'maxViewportDimensions': ctypes.ARRAY(ctypes.c_uint32, 2),
    'viewportBoundsRange': ctypes.ARRAY(ctypes.c_float, 2),
    'viewportSubPixelBits': ctypes.c_uint32,
    'minMemoryMapAlignment': ctypes.c_size_t,
    'minTexelBufferOffsetAlignment': ctypes.c_uint64,
    'minUniformBufferOffsetAlignment': ctypes.c_uint64,
    'minStorageBufferOffsetAlignment': ctypes.c_uint64,
    'minTexelOffset': ctypes.c_int32,
    'maxTexelOffset': ctypes.c_uint32,
    'minTexelGatherOffset': ctypes.c_int32,
    'maxTexelGatherOffset': ctypes.c_uint32,
    'minInterpolationOffset': ctypes.c_float,
    'maxInterpolationOffset': ctypes.c_float,
    'subPixelInterpolationOffsetBits': ctypes.c_uint32,
    'maxFramebufferWidth': ctypes.c_uint32,
    'maxFramebufferHeight': ctypes.c_uint32,
    'maxFramebufferLayers': ctypes.c_uint32,
    'framebufferColorSampleCounts': ctypes.c_uint32,
    'framebufferDepthSampleCounts': ctypes.c_uint32,
    'framebufferStencilSampleCounts': ctypes.c_uint32,
    'framebufferNoAttachmentsSampleCounts': ctypes.c_uint32,
    'maxColorAttachments': ctypes.c_uint32,
    'sampledImageColorSampleCounts': ctypes.c_uint32,
    'sampledImageIntegerSampleCounts': ctypes.c_uint32,
    'sampledImageDepthSampleCounts': ctypes.c_uint32,
    'sampledImageStencilSampleCounts': ctypes.c_uint32,
    'storageImageSampleCounts': ctypes.c_uint32,
    'maxSampleMaskWords': ctypes.c_uint32,
    'timestampComputeAndGraphics': ctypes.c_uint32,
    'timestampPeriod': ctypes.c_float,
    'maxClipDistances': ctypes.c_uint32,
    'maxCullDistances': ctypes.c_uint32,
    'maxCombinedClipAndCullDistances': ctypes.c_uint32,
    'discreteQueuePriorities': ctypes.c_uint32,
    'pointSizeRange': ctypes.ARRAY(ctypes.c_float, 2),
    'lineWidthRange': ctypes.ARRAY(ctypes.c_float, 2),
    'pointSizeGranularity': ctypes.c_float,
    'lineWidthGranularity': ctypes.c_float,
    'strictLines': ctypes.c_uint32,
    'standardSampleLocations': ctypes.c_uint32,
    'optimalBufferCopyOffsetAlignment': ctypes.c_uint64,
    'optimalBufferCopyRowPitchAlignment': ctypes.c_uint64,
    'nonCoherentAtomSize': ctypes.c_uint64,
}
