import ctypes

class CType(ctypes.Structure):
    _fields_ = [
        ('maxImageDimension1D', ctypes.c_uint32),
        ('maxImageDimension2D', ctypes.c_uint32),
        ('maxImageDimension3D', ctypes.c_uint32),
        ('maxImageDimensionCube', ctypes.c_uint32),
        ('maxImageArrayLayers', ctypes.c_uint32),
        ('maxTexelBufferElements', ctypes.c_uint32),
        ('maxUniformBufferRange', ctypes.c_uint32),
        ('maxStorageBufferRange', ctypes.c_uint32),
        ('maxPushConstantsSize', ctypes.c_uint32),
        ('maxMemoryAllocationCount', ctypes.c_uint32),
        ('maxSamplerAllocationCount', ctypes.c_uint32),
        ('bufferImageGranularity', ctypes.c_uint64),
        ('sparseAddressSpaceSize', ctypes.c_uint64),
        ('maxBoundDescriptorSets', ctypes.c_uint32),
        ('maxPerStageDescriptorSamplers', ctypes.c_uint32),
        ('maxPerStageDescriptorUniformBuffers', ctypes.c_uint32),
        ('maxPerStageDescriptorStorageBuffers', ctypes.c_uint32),
        ('maxPerStageDescriptorSampledImages', ctypes.c_uint32),
        ('maxPerStageDescriptorStorageImages', ctypes.c_uint32),
        ('maxPerStageDescriptorInputAttachments', ctypes.c_uint32),
        ('maxPerStageResources', ctypes.c_uint32),
        ('maxDescriptorSetSamplers', ctypes.c_uint32),
        ('maxDescriptorSetUniformBuffers', ctypes.c_uint32),
        ('maxDescriptorSetUniformBuffersDynamic', ctypes.c_uint32),
        ('maxDescriptorSetStorageBuffers', ctypes.c_uint32),
        ('maxDescriptorSetStorageBuffersDynamic', ctypes.c_uint32),
        ('maxDescriptorSetSampledImages', ctypes.c_uint32),
        ('maxDescriptorSetStorageImages', ctypes.c_uint32),
        ('maxDescriptorSetInputAttachments', ctypes.c_uint32),
        ('maxVertexInputAttributes', ctypes.c_uint32),
        ('maxVertexInputBindings', ctypes.c_uint32),
        ('maxVertexInputAttributeOffset', ctypes.c_uint32),
        ('maxVertexInputBindingStride', ctypes.c_uint32),
        ('maxVertexOutputComponents', ctypes.c_uint32),
        ('maxTessellationGenerationLevel', ctypes.c_uint32),
        ('maxTessellationPatchSize', ctypes.c_uint32),
        ('maxTessellationControlPerVertexInputComponents', ctypes.c_uint32),
        ('maxTessellationControlPerVertexOutputComponents', ctypes.c_uint32),
        ('maxTessellationControlPerPatchOutputComponents', ctypes.c_uint32),
        ('maxTessellationControlTotalOutputComponents', ctypes.c_uint32),
        ('maxTessellationEvaluationInputComponents', ctypes.c_uint32),
        ('maxTessellationEvaluationOutputComponents', ctypes.c_uint32),
        ('maxGeometryShaderInvocations', ctypes.c_uint32),
        ('maxGeometryInputComponents', ctypes.c_uint32),
        ('maxGeometryOutputComponents', ctypes.c_uint32),
        ('maxGeometryOutputVertices', ctypes.c_uint32),
        ('maxGeometryTotalOutputComponents', ctypes.c_uint32),
        ('maxFragmentInputComponents', ctypes.c_uint32),
        ('maxFragmentOutputAttachments', ctypes.c_uint32),
        ('maxFragmentDualSrcAttachments', ctypes.c_uint32),
        ('maxFragmentCombinedOutputResources', ctypes.c_uint32),
        ('maxComputeSharedMemorySize', ctypes.c_uint32),
        ('maxComputeWorkGroupCount', ctypes.ARRAY(ctypes.c_uint32, 3)),
        ('maxComputeWorkGroupInvocations', ctypes.c_uint32),
        ('maxComputeWorkGroupSize', ctypes.ARRAY(ctypes.c_uint32, 3)),
        ('subPixelPrecisionBits', ctypes.c_uint32),
        ('subTexelPrecisionBits', ctypes.c_uint32),
        ('mipmapPrecisionBits', ctypes.c_uint32),
        ('maxDrawIndexedIndexValue', ctypes.c_uint32),
        ('maxDrawIndirectCount', ctypes.c_uint32),
        ('maxSamplerLodBias', ctypes.c_float),
        ('maxSamplerAnisotropy', ctypes.c_float),
        ('maxViewports', ctypes.c_uint32),
        ('maxViewportDimensions', ctypes.ARRAY(ctypes.c_uint32, 2)),
        ('viewportBoundsRange', ctypes.ARRAY(ctypes.c_float, 2)),
        ('viewportSubPixelBits', ctypes.c_uint32),
        ('minMemoryMapAlignment', ctypes.c_size_t),
        ('minTexelBufferOffsetAlignment', ctypes.c_uint64),
        ('minUniformBufferOffsetAlignment', ctypes.c_uint64),
        ('minStorageBufferOffsetAlignment', ctypes.c_uint64),
        ('minTexelOffset', ctypes.c_int32),
        ('maxTexelOffset', ctypes.c_uint32),
        ('minTexelGatherOffset', ctypes.c_int32),
        ('maxTexelGatherOffset', ctypes.c_uint32),
        ('minInterpolationOffset', ctypes.c_float),
        ('maxInterpolationOffset', ctypes.c_float),
        ('subPixelInterpolationOffsetBits', ctypes.c_uint32),
        ('maxFramebufferWidth', ctypes.c_uint32),
        ('maxFramebufferHeight', ctypes.c_uint32),
        ('maxFramebufferLayers', ctypes.c_uint32),
        ('framebufferColorSampleCounts', ctypes.c_uint32),
        ('framebufferDepthSampleCounts', ctypes.c_uint32),
        ('framebufferStencilSampleCounts', ctypes.c_uint32),
        ('framebufferNoAttachmentsSampleCounts', ctypes.c_uint32),
        ('maxColorAttachments', ctypes.c_uint32),
        ('sampledImageColorSampleCounts', ctypes.c_uint32),
        ('sampledImageIntegerSampleCounts', ctypes.c_uint32),
        ('sampledImageDepthSampleCounts', ctypes.c_uint32),
        ('sampledImageStencilSampleCounts', ctypes.c_uint32),
        ('storageImageSampleCounts', ctypes.c_uint32),
        ('maxSampleMaskWords', ctypes.c_uint32),
        ('timestampComputeAndGraphics', ctypes.c_uint32),
        ('timestampPeriod', ctypes.c_float),
        ('maxClipDistances', ctypes.c_uint32),
        ('maxCullDistances', ctypes.c_uint32),
        ('maxCombinedClipAndCullDistances', ctypes.c_uint32),
        ('discreteQueuePriorities', ctypes.c_uint32),
        ('pointSizeRange', ctypes.ARRAY(ctypes.c_float, 2)),
        ('lineWidthRange', ctypes.ARRAY(ctypes.c_float, 2)),
        ('pointSizeGranularity', ctypes.c_float),
        ('lineWidthGranularity', ctypes.c_float),
        ('strictLines', ctypes.c_uint32),
        ('standardSampleLocations', ctypes.c_uint32),
        ('optimalBufferCopyOffsetAlignment', ctypes.c_uint64),
        ('optimalBufferCopyRowPitchAlignment', ctypes.c_uint64),
        ('nonCoherentAtomSize', ctypes.c_uint64),
    ]

descriptor = {
    'extends': set(),
    'extended_by': set(),
    'includes': set(),
    'included_in': {
        'VkPhysicalDeviceProperties',
    },
    'input_of': set(),
    'output_of': set(),
    'member_map': {
        'maxImageDimension1D': {'python_name': ['max', 'image', 'dimension1', 'd']},
        'maxImageDimension2D': {'python_name': ['max', 'image', 'dimension2', 'd']},
        'maxImageDimension3D': {'python_name': ['max', 'image', 'dimension3', 'd']},
        'maxImageDimensionCube': {'python_name': ['max', 'image', 'dimension', 'cube']},
        'maxImageArrayLayers': {'python_name': ['max', 'image', 'array', 'layers']},
        'maxTexelBufferElements': {'python_name': ['max', 'texel', 'buffer', 'elements']},
        'maxUniformBufferRange': {'python_name': ['max', 'uniform', 'buffer', 'range']},
        'maxStorageBufferRange': {'python_name': ['max', 'storage', 'buffer', 'range']},
        'maxPushConstantsSize': {'python_name': ['max', 'push', 'constants', 'size']},
        'maxMemoryAllocationCount': {'python_name': ['max', 'memory', 'allocation', 'count']},
        'maxSamplerAllocationCount': {'python_name': ['max', 'sampler', 'allocation', 'count']},
        'bufferImageGranularity': {'python_name': ['buffer', 'image', 'granularity']},
        'sparseAddressSpaceSize': {'python_name': ['sparse', 'address', 'space', 'size']},
        'maxBoundDescriptorSets': {'python_name': ['max', 'bound', 'descriptor', 'sets']},
        'maxPerStageDescriptorSamplers': {'python_name': ['max', 'per', 'stage', 'descriptor', 'samplers']},
        'maxPerStageDescriptorUniformBuffers': {'python_name': ['max', 'per', 'stage', 'descriptor', 'uniform', 'buffers']},
        'maxPerStageDescriptorStorageBuffers': {'python_name': ['max', 'per', 'stage', 'descriptor', 'storage', 'buffers']},
        'maxPerStageDescriptorSampledImages': {'python_name': ['max', 'per', 'stage', 'descriptor', 'sampled', 'images']},
        'maxPerStageDescriptorStorageImages': {'python_name': ['max', 'per', 'stage', 'descriptor', 'storage', 'images']},
        'maxPerStageDescriptorInputAttachments': {'python_name': ['max', 'per', 'stage', 'descriptor', 'input', 'attachments']},
        'maxPerStageResources': {'python_name': ['max', 'per', 'stage', 'resources']},
        'maxDescriptorSetSamplers': {'python_name': ['max', 'descriptor', 'set', 'samplers']},
        'maxDescriptorSetUniformBuffers': {'python_name': ['max', 'descriptor', 'set', 'uniform', 'buffers']},
        'maxDescriptorSetUniformBuffersDynamic': {'python_name': ['max', 'descriptor', 'set', 'uniform', 'buffers', 'dynamic']},
        'maxDescriptorSetStorageBuffers': {'python_name': ['max', 'descriptor', 'set', 'storage', 'buffers']},
        'maxDescriptorSetStorageBuffersDynamic': {'python_name': ['max', 'descriptor', 'set', 'storage', 'buffers', 'dynamic']},
        'maxDescriptorSetSampledImages': {'python_name': ['max', 'descriptor', 'set', 'sampled', 'images']},
        'maxDescriptorSetStorageImages': {'python_name': ['max', 'descriptor', 'set', 'storage', 'images']},
        'maxDescriptorSetInputAttachments': {'python_name': ['max', 'descriptor', 'set', 'input', 'attachments']},
        'maxVertexInputAttributes': {'python_name': ['max', 'vertex', 'input', 'attributes']},
        'maxVertexInputBindings': {'python_name': ['max', 'vertex', 'input', 'bindings']},
        'maxVertexInputAttributeOffset': {'python_name': ['max', 'vertex', 'input', 'attribute', 'offset']},
        'maxVertexInputBindingStride': {'python_name': ['max', 'vertex', 'input', 'binding', 'stride']},
        'maxVertexOutputComponents': {'python_name': ['max', 'vertex', 'output', 'components']},
        'maxTessellationGenerationLevel': {'python_name': ['max', 'tessellation', 'generation', 'level']},
        'maxTessellationPatchSize': {'python_name': ['max', 'tessellation', 'patch', 'size']},
        'maxTessellationControlPerVertexInputComponents': {'python_name': ['max', 'tessellation', 'control', 'per', 'vertex', 'input', 'components']},
        'maxTessellationControlPerVertexOutputComponents': {'python_name': ['max', 'tessellation', 'control', 'per', 'vertex', 'output', 'components']},
        'maxTessellationControlPerPatchOutputComponents': {'python_name': ['max', 'tessellation', 'control', 'per', 'patch', 'output', 'components']},
        'maxTessellationControlTotalOutputComponents': {'python_name': ['max', 'tessellation', 'control', 'total', 'output', 'components']},
        'maxTessellationEvaluationInputComponents': {'python_name': ['max', 'tessellation', 'evaluation', 'input', 'components']},
        'maxTessellationEvaluationOutputComponents': {'python_name': ['max', 'tessellation', 'evaluation', 'output', 'components']},
        'maxGeometryShaderInvocations': {'python_name': ['max', 'geometry', 'shader', 'invocations']},
        'maxGeometryInputComponents': {'python_name': ['max', 'geometry', 'input', 'components']},
        'maxGeometryOutputComponents': {'python_name': ['max', 'geometry', 'output', 'components']},
        'maxGeometryOutputVertices': {'python_name': ['max', 'geometry', 'output', 'vertices']},
        'maxGeometryTotalOutputComponents': {'python_name': ['max', 'geometry', 'total', 'output', 'components']},
        'maxFragmentInputComponents': {'python_name': ['max', 'fragment', 'input', 'components']},
        'maxFragmentOutputAttachments': {'python_name': ['max', 'fragment', 'output', 'attachments']},
        'maxFragmentDualSrcAttachments': {'python_name': ['max', 'fragment', 'dual', 'src', 'attachments']},
        'maxFragmentCombinedOutputResources': {'python_name': ['max', 'fragment', 'combined', 'output', 'resources']},
        'maxComputeSharedMemorySize': {'python_name': ['max', 'compute', 'shared', 'memory', 'size']},
        'maxComputeWorkGroupCount': {'python_name': ['max', 'compute', 'work', 'group', 'count']},
        'maxComputeWorkGroupInvocations': {'python_name': ['max', 'compute', 'work', 'group', 'invocations']},
        'maxComputeWorkGroupSize': {'python_name': ['max', 'compute', 'work', 'group', 'size']},
        'subPixelPrecisionBits': {'python_name': ['sub', 'pixel', 'precision', 'bits']},
        'subTexelPrecisionBits': {'python_name': ['sub', 'texel', 'precision', 'bits']},
        'mipmapPrecisionBits': {'python_name': ['mipmap', 'precision', 'bits']},
        'maxDrawIndexedIndexValue': {'python_name': ['max', 'draw', 'indexed', 'index', 'value']},
        'maxDrawIndirectCount': {'python_name': ['max', 'draw', 'indirect', 'count']},
        'maxSamplerLodBias': {'python_name': ['max', 'sampler', 'lod', 'bias']},
        'maxSamplerAnisotropy': {'python_name': ['max', 'sampler', 'anisotropy']},
        'maxViewports': {'python_name': ['max', 'viewports']},
        'maxViewportDimensions': {'python_name': ['max', 'viewport', 'dimensions']},
        'viewportBoundsRange': {'python_name': ['viewport', 'bounds', 'range']},
        'viewportSubPixelBits': {'python_name': ['viewport', 'sub', 'pixel', 'bits']},
        'minMemoryMapAlignment': {'python_name': ['min', 'memory', 'map', 'alignment']},
        'minTexelBufferOffsetAlignment': {'python_name': ['min', 'texel', 'buffer', 'offset', 'alignment']},
        'minUniformBufferOffsetAlignment': {'python_name': ['min', 'uniform', 'buffer', 'offset', 'alignment']},
        'minStorageBufferOffsetAlignment': {'python_name': ['min', 'storage', 'buffer', 'offset', 'alignment']},
        'minTexelOffset': {'python_name': ['min', 'texel', 'offset']},
        'maxTexelOffset': {'python_name': ['max', 'texel', 'offset']},
        'minTexelGatherOffset': {'python_name': ['min', 'texel', 'gather', 'offset']},
        'maxTexelGatherOffset': {'python_name': ['max', 'texel', 'gather', 'offset']},
        'minInterpolationOffset': {'python_name': ['min', 'interpolation', 'offset']},
        'maxInterpolationOffset': {'python_name': ['max', 'interpolation', 'offset']},
        'subPixelInterpolationOffsetBits': {'python_name': ['sub', 'pixel', 'interpolation', 'offset', 'bits']},
        'maxFramebufferWidth': {'python_name': ['max', 'framebuffer', 'width']},
        'maxFramebufferHeight': {'python_name': ['max', 'framebuffer', 'height']},
        'maxFramebufferLayers': {'python_name': ['max', 'framebuffer', 'layers']},
        'framebufferColorSampleCounts': {'python_name': ['framebuffer', 'color', 'sample', 'counts'], 'type': 'VkSampleCountFlags'},
        'framebufferDepthSampleCounts': {'python_name': ['framebuffer', 'depth', 'sample', 'counts'], 'type': 'VkSampleCountFlags'},
        'framebufferStencilSampleCounts': {'python_name': ['framebuffer', 'stencil', 'sample', 'counts'], 'type': 'VkSampleCountFlags'},
        'framebufferNoAttachmentsSampleCounts': {'python_name': ['framebuffer', 'no', 'attachments', 'sample', 'counts'], 'type': 'VkSampleCountFlags'},
        'maxColorAttachments': {'python_name': ['max', 'color', 'attachments']},
        'sampledImageColorSampleCounts': {'python_name': ['sampled', 'image', 'color', 'sample', 'counts'], 'type': 'VkSampleCountFlags'},
        'sampledImageIntegerSampleCounts': {'python_name': ['sampled', 'image', 'integer', 'sample', 'counts'], 'type': 'VkSampleCountFlags'},
        'sampledImageDepthSampleCounts': {'python_name': ['sampled', 'image', 'depth', 'sample', 'counts'], 'type': 'VkSampleCountFlags'},
        'sampledImageStencilSampleCounts': {'python_name': ['sampled', 'image', 'stencil', 'sample', 'counts'], 'type': 'VkSampleCountFlags'},
        'storageImageSampleCounts': {'python_name': ['storage', 'image', 'sample', 'counts'], 'type': 'VkSampleCountFlags'},
        'maxSampleMaskWords': {'python_name': ['max', 'sample', 'mask', 'words']},
        'timestampComputeAndGraphics': {'python_name': ['timestamp', 'compute', 'and', 'graphics']},
        'timestampPeriod': {'python_name': ['timestamp', 'period']},
        'maxClipDistances': {'python_name': ['max', 'clip', 'distances']},
        'maxCullDistances': {'python_name': ['max', 'cull', 'distances']},
        'maxCombinedClipAndCullDistances': {'python_name': ['max', 'combined', 'clip', 'and', 'cull', 'distances']},
        'discreteQueuePriorities': {'python_name': ['discrete', 'queue', 'priorities']},
        'pointSizeRange': {'python_name': ['point', 'size', 'range']},
        'lineWidthRange': {'python_name': ['line', 'width', 'range']},
        'pointSizeGranularity': {'python_name': ['point', 'size', 'granularity']},
        'lineWidthGranularity': {'python_name': ['line', 'width', 'granularity']},
        'strictLines': {'python_name': ['strict', 'lines']},
        'standardSampleLocations': {'python_name': ['standard', 'sample', 'locations']},
        'optimalBufferCopyOffsetAlignment': {'python_name': ['optimal', 'buffer', 'copy', 'offset', 'alignment']},
        'optimalBufferCopyRowPitchAlignment': {'python_name': ['optimal', 'buffer', 'copy', 'row', 'pitch', 'alignment']},
        'nonCoherentAtomSize': {'python_name': ['non', 'coherent', 'atom', 'size']},
    }
}
