import ctypes

class CType(ctypes.Structure):
    _fields_ = [
        ('sType', ctypes.c_int),
        ('pNext', ctypes.c_void_p),
        ('combinedImageSamplerDescriptorSingleArray', ctypes.c_uint32),
        ('bufferlessPushDescriptors', ctypes.c_uint32),
        ('allowSamplerImageViewPostSubmitCreation', ctypes.c_uint32),
        ('descriptorBufferOffsetAlignment', ctypes.c_uint64),
        ('maxDescriptorBufferBindings', ctypes.c_uint32),
        ('maxResourceDescriptorBufferBindings', ctypes.c_uint32),
        ('maxSamplerDescriptorBufferBindings', ctypes.c_uint32),
        ('maxEmbeddedImmutableSamplerBindings', ctypes.c_uint32),
        ('maxEmbeddedImmutableSamplers', ctypes.c_uint32),
        ('bufferCaptureReplayDescriptorDataSize', ctypes.c_size_t),
        ('imageCaptureReplayDescriptorDataSize', ctypes.c_size_t),
        ('imageViewCaptureReplayDescriptorDataSize', ctypes.c_size_t),
        ('samplerCaptureReplayDescriptorDataSize', ctypes.c_size_t),
        ('accelerationStructureCaptureReplayDescriptorDataSize', ctypes.c_size_t),
        ('samplerDescriptorSize', ctypes.c_size_t),
        ('combinedImageSamplerDescriptorSize', ctypes.c_size_t),
        ('sampledImageDescriptorSize', ctypes.c_size_t),
        ('storageImageDescriptorSize', ctypes.c_size_t),
        ('uniformTexelBufferDescriptorSize', ctypes.c_size_t),
        ('robustUniformTexelBufferDescriptorSize', ctypes.c_size_t),
        ('storageTexelBufferDescriptorSize', ctypes.c_size_t),
        ('robustStorageTexelBufferDescriptorSize', ctypes.c_size_t),
        ('uniformBufferDescriptorSize', ctypes.c_size_t),
        ('robustUniformBufferDescriptorSize', ctypes.c_size_t),
        ('storageBufferDescriptorSize', ctypes.c_size_t),
        ('robustStorageBufferDescriptorSize', ctypes.c_size_t),
        ('inputAttachmentDescriptorSize', ctypes.c_size_t),
        ('accelerationStructureDescriptorSize', ctypes.c_size_t),
        ('maxSamplerDescriptorBufferRange', ctypes.c_uint64),
        ('maxResourceDescriptorBufferRange', ctypes.c_uint64),
        ('samplerDescriptorBufferAddressSpaceSize', ctypes.c_uint64),
        ('resourceDescriptorBufferAddressSpaceSize', ctypes.c_uint64),
        ('descriptorBufferAddressSpaceSize', ctypes.c_uint64),
    ]

descriptor = {
    'extends': {
        'VkPhysicalDeviceProperties2',
    },
    'extended_by': set(),
    'includes': set(),
    'included_in': set(),
    'input_of': set(),
    'output_of': set(),
    'member_map': {
        'sType': {'python_name': ['s', 'type'], 'value': 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_BUFFER_PROPERTIES_EXT', 'type': 'VkStructureType'},
        'pNext': {'python_name': ['p', 'next']},
        'combinedImageSamplerDescriptorSingleArray': {'python_name': ['combined', 'image', 'sampler', 'descriptor', 'single', 'array']},
        'bufferlessPushDescriptors': {'python_name': ['bufferless', 'push', 'descriptors']},
        'allowSamplerImageViewPostSubmitCreation': {'python_name': ['allow', 'sampler', 'image', 'view', 'post', 'submit', 'creation']},
        'descriptorBufferOffsetAlignment': {'python_name': ['descriptor', 'buffer', 'offset', 'alignment']},
        'maxDescriptorBufferBindings': {'python_name': ['max', 'descriptor', 'buffer', 'bindings']},
        'maxResourceDescriptorBufferBindings': {'python_name': ['max', 'resource', 'descriptor', 'buffer', 'bindings']},
        'maxSamplerDescriptorBufferBindings': {'python_name': ['max', 'sampler', 'descriptor', 'buffer', 'bindings']},
        'maxEmbeddedImmutableSamplerBindings': {'python_name': ['max', 'embedded', 'immutable', 'sampler', 'bindings']},
        'maxEmbeddedImmutableSamplers': {'python_name': ['max', 'embedded', 'immutable', 'samplers']},
        'bufferCaptureReplayDescriptorDataSize': {'python_name': ['buffer', 'capture', 'replay', 'descriptor', 'data', 'size']},
        'imageCaptureReplayDescriptorDataSize': {'python_name': ['image', 'capture', 'replay', 'descriptor', 'data', 'size']},
        'imageViewCaptureReplayDescriptorDataSize': {'python_name': ['image', 'view', 'capture', 'replay', 'descriptor', 'data', 'size']},
        'samplerCaptureReplayDescriptorDataSize': {'python_name': ['sampler', 'capture', 'replay', 'descriptor', 'data', 'size']},
        'accelerationStructureCaptureReplayDescriptorDataSize': {'python_name': ['acceleration', 'structure', 'capture', 'replay', 'descriptor', 'data', 'size']},
        'samplerDescriptorSize': {'python_name': ['sampler', 'descriptor', 'size']},
        'combinedImageSamplerDescriptorSize': {'python_name': ['combined', 'image', 'sampler', 'descriptor', 'size']},
        'sampledImageDescriptorSize': {'python_name': ['sampled', 'image', 'descriptor', 'size']},
        'storageImageDescriptorSize': {'python_name': ['storage', 'image', 'descriptor', 'size']},
        'uniformTexelBufferDescriptorSize': {'python_name': ['uniform', 'texel', 'buffer', 'descriptor', 'size']},
        'robustUniformTexelBufferDescriptorSize': {'python_name': ['robust', 'uniform', 'texel', 'buffer', 'descriptor', 'size']},
        'storageTexelBufferDescriptorSize': {'python_name': ['storage', 'texel', 'buffer', 'descriptor', 'size']},
        'robustStorageTexelBufferDescriptorSize': {'python_name': ['robust', 'storage', 'texel', 'buffer', 'descriptor', 'size']},
        'uniformBufferDescriptorSize': {'python_name': ['uniform', 'buffer', 'descriptor', 'size']},
        'robustUniformBufferDescriptorSize': {'python_name': ['robust', 'uniform', 'buffer', 'descriptor', 'size']},
        'storageBufferDescriptorSize': {'python_name': ['storage', 'buffer', 'descriptor', 'size']},
        'robustStorageBufferDescriptorSize': {'python_name': ['robust', 'storage', 'buffer', 'descriptor', 'size']},
        'inputAttachmentDescriptorSize': {'python_name': ['input', 'attachment', 'descriptor', 'size']},
        'accelerationStructureDescriptorSize': {'python_name': ['acceleration', 'structure', 'descriptor', 'size']},
        'maxSamplerDescriptorBufferRange': {'python_name': ['max', 'sampler', 'descriptor', 'buffer', 'range']},
        'maxResourceDescriptorBufferRange': {'python_name': ['max', 'resource', 'descriptor', 'buffer', 'range']},
        'samplerDescriptorBufferAddressSpaceSize': {'python_name': ['sampler', 'descriptor', 'buffer', 'address', 'space', 'size']},
        'resourceDescriptorBufferAddressSpaceSize': {'python_name': ['resource', 'descriptor', 'buffer', 'address', 'space', 'size']},
        'descriptorBufferAddressSpaceSize': {'python_name': ['descriptor', 'buffer', 'address', 'space', 'size']},
    }
}
