import ctypes

class CType(ctypes.Structure):
    pass

from .VkPhysicalDeviceProperties import CType as VkPhysicalDeviceProperties

CType._fields_ = [
    ('sType', ctypes.c_int),
    ('pNext', ctypes.c_void_p),
    ('properties', VkPhysicalDeviceProperties),
]

descriptor = {
    'extends': set(),
    'extended_by': {
        'VkPhysicalDeviceAccelerationStructurePropertiesKHR',
        'VkPhysicalDeviceBlendOperationAdvancedPropertiesEXT',
        'VkPhysicalDeviceClusterCullingShaderPropertiesHUAWEI',
        'VkPhysicalDeviceConservativeRasterizationPropertiesEXT',
        'VkPhysicalDeviceCooperativeMatrixPropertiesKHR',
        'VkPhysicalDeviceCooperativeMatrixPropertiesNV',
        'VkPhysicalDeviceCopyMemoryIndirectPropertiesNV',
        'VkPhysicalDeviceCudaKernelLaunchPropertiesNV',
        'VkPhysicalDeviceCustomBorderColorPropertiesEXT',
        'VkPhysicalDeviceDepthStencilResolveProperties',
        'VkPhysicalDeviceDescriptorBufferDensityMapPropertiesEXT',
        'VkPhysicalDeviceDescriptorBufferPropertiesEXT',
        'VkPhysicalDeviceDescriptorIndexingProperties',
        'VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV',
        'VkPhysicalDeviceDiscardRectanglePropertiesEXT',
        'VkPhysicalDeviceDisplacementMicromapPropertiesNV',
        'VkPhysicalDeviceDriverProperties',
        'VkPhysicalDeviceDrmPropertiesEXT',
        'VkPhysicalDeviceExtendedDynamicState3PropertiesEXT',
        'VkPhysicalDeviceExtendedSparseAddressSpacePropertiesNV',
        'VkPhysicalDeviceExternalFormatResolvePropertiesANDROID',
        'VkPhysicalDeviceExternalMemoryHostPropertiesEXT',
        'VkPhysicalDeviceFloatControlsProperties',
        'VkPhysicalDeviceFragmentDensityMap2PropertiesEXT',
        'VkPhysicalDeviceFragmentDensityMapOffsetPropertiesQCOM',
        'VkPhysicalDeviceFragmentDensityMapPropertiesEXT',
        'VkPhysicalDeviceFragmentShaderBarycentricPropertiesKHR',
        'VkPhysicalDeviceFragmentShadingRateEnumsPropertiesNV',
        'VkPhysicalDeviceFragmentShadingRatePropertiesKHR',
        'VkPhysicalDeviceGraphicsPipelineLibraryPropertiesEXT',
        'VkPhysicalDeviceHostImageCopyPropertiesEXT',
        'VkPhysicalDeviceIDProperties',
        'VkPhysicalDeviceImageAlignmentControlPropertiesMESA',
        'VkPhysicalDeviceImageProcessing2PropertiesQCOM',
        'VkPhysicalDeviceImageProcessingPropertiesQCOM',
        'VkPhysicalDeviceInlineUniformBlockProperties',
        'VkPhysicalDeviceLayeredDriverPropertiesMSFT',
        'VkPhysicalDeviceLegacyVertexAttributesPropertiesEXT',
        'VkPhysicalDeviceLineRasterizationPropertiesKHR',
        'VkPhysicalDeviceMaintenance3Properties',
        'VkPhysicalDeviceMaintenance4Properties',
        'VkPhysicalDeviceMaintenance5PropertiesKHR',
        'VkPhysicalDeviceMaintenance6PropertiesKHR',
        'VkPhysicalDeviceMapMemoryPlacedPropertiesEXT',
        'VkPhysicalDeviceMemoryDecompressionPropertiesNV',
        'VkPhysicalDeviceMeshShaderPropertiesEXT',
        'VkPhysicalDeviceMeshShaderPropertiesNV',
        'VkPhysicalDeviceMultiDrawPropertiesEXT',
        'VkPhysicalDeviceMultiviewPerViewAttributesPropertiesNVX',
        'VkPhysicalDeviceMultiviewProperties',
        'VkPhysicalDeviceNestedCommandBufferPropertiesEXT',
        'VkPhysicalDeviceOpacityMicromapPropertiesEXT',
        'VkPhysicalDeviceOpticalFlowPropertiesNV',
        'VkPhysicalDevicePCIBusInfoPropertiesEXT',
        'VkPhysicalDevicePerformanceQueryPropertiesKHR',
        'VkPhysicalDevicePipelineRobustnessPropertiesEXT',
        'VkPhysicalDevicePointClippingProperties',
        'VkPhysicalDevicePortabilitySubsetPropertiesKHR',
        'VkPhysicalDeviceProtectedMemoryProperties',
        'VkPhysicalDeviceProvokingVertexPropertiesEXT',
        'VkPhysicalDevicePushDescriptorPropertiesKHR',
        'VkPhysicalDeviceRayTracingInvocationReorderPropertiesNV',
        'VkPhysicalDeviceRayTracingPipelinePropertiesKHR',
        'VkPhysicalDeviceRayTracingPropertiesNV',
        'VkPhysicalDeviceRenderPassStripedPropertiesARM',
        'VkPhysicalDeviceRobustness2PropertiesEXT',
        'VkPhysicalDeviceSampleLocationsPropertiesEXT',
        'VkPhysicalDeviceSamplerFilterMinmaxProperties',
        'VkPhysicalDeviceSchedulingControlsPropertiesARM',
        'VkPhysicalDeviceShaderCoreBuiltinsPropertiesARM',
        'VkPhysicalDeviceShaderCoreProperties2AMD',
        'VkPhysicalDeviceShaderCorePropertiesAMD',
        'VkPhysicalDeviceShaderCorePropertiesARM',
        'VkPhysicalDeviceShaderEnqueuePropertiesAMDX',
        'VkPhysicalDeviceShaderIntegerDotProductProperties',
        'VkPhysicalDeviceShaderModuleIdentifierPropertiesEXT',
        'VkPhysicalDeviceShaderObjectPropertiesEXT',
        'VkPhysicalDeviceShaderSMBuiltinsPropertiesNV',
        'VkPhysicalDeviceShaderTileImagePropertiesEXT',
        'VkPhysicalDeviceShadingRateImagePropertiesNV',
        'VkPhysicalDeviceSubgroupProperties',
        'VkPhysicalDeviceSubgroupSizeControlProperties',
        'VkPhysicalDeviceSubpassShadingPropertiesHUAWEI',
        'VkPhysicalDeviceTexelBufferAlignmentProperties',
        'VkPhysicalDeviceTimelineSemaphoreProperties',
        'VkPhysicalDeviceTransformFeedbackPropertiesEXT',
        'VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT',
        'VkPhysicalDeviceVertexAttributeDivisorPropertiesKHR',
        'VkPhysicalDeviceVulkan11Properties',
        'VkPhysicalDeviceVulkan12Properties',
        'VkPhysicalDeviceVulkan13Properties',
        'VkPhysicalDeviceVulkanSC10Properties',
    },
    'includes': {
        'VkPhysicalDeviceProperties',
    },
    'included_in': set(),
    'input_of': set(),
    'output_of': {
        'vkGetPhysicalDeviceProperties2',
    },
    'member_map': {
        'sType': {'python_name': ['s', 'type'], 'value': 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2', 'type': 'VkStructureType'},
        'pNext': {'python_name': ['p', 'next']},
        'properties': {'python_name': ['properties'], 'type': 'VkPhysicalDeviceProperties'},
    }
}
