import ctypes

class CType(ctypes.Structure):
    _fields_ = [
        ('sType', ctypes.c_int),
        ('pNext', ctypes.c_void_p),
        ('samplerMirrorClampToEdge', ctypes.c_uint32),
        ('drawIndirectCount', ctypes.c_uint32),
        ('storageBuffer8BitAccess', ctypes.c_uint32),
        ('uniformAndStorageBuffer8BitAccess', ctypes.c_uint32),
        ('storagePushConstant8', ctypes.c_uint32),
        ('shaderBufferInt64Atomics', ctypes.c_uint32),
        ('shaderSharedInt64Atomics', ctypes.c_uint32),
        ('shaderFloat16', ctypes.c_uint32),
        ('shaderInt8', ctypes.c_uint32),
        ('descriptorIndexing', ctypes.c_uint32),
        ('shaderInputAttachmentArrayDynamicIndexing', ctypes.c_uint32),
        ('shaderUniformTexelBufferArrayDynamicIndexing', ctypes.c_uint32),
        ('shaderStorageTexelBufferArrayDynamicIndexing', ctypes.c_uint32),
        ('shaderUniformBufferArrayNonUniformIndexing', ctypes.c_uint32),
        ('shaderSampledImageArrayNonUniformIndexing', ctypes.c_uint32),
        ('shaderStorageBufferArrayNonUniformIndexing', ctypes.c_uint32),
        ('shaderStorageImageArrayNonUniformIndexing', ctypes.c_uint32),
        ('shaderInputAttachmentArrayNonUniformIndexing', ctypes.c_uint32),
        ('shaderUniformTexelBufferArrayNonUniformIndexing', ctypes.c_uint32),
        ('shaderStorageTexelBufferArrayNonUniformIndexing', ctypes.c_uint32),
        ('descriptorBindingUniformBufferUpdateAfterBind', ctypes.c_uint32),
        ('descriptorBindingSampledImageUpdateAfterBind', ctypes.c_uint32),
        ('descriptorBindingStorageImageUpdateAfterBind', ctypes.c_uint32),
        ('descriptorBindingStorageBufferUpdateAfterBind', ctypes.c_uint32),
        ('descriptorBindingUniformTexelBufferUpdateAfterBind', ctypes.c_uint32),
        ('descriptorBindingStorageTexelBufferUpdateAfterBind', ctypes.c_uint32),
        ('descriptorBindingUpdateUnusedWhilePending', ctypes.c_uint32),
        ('descriptorBindingPartiallyBound', ctypes.c_uint32),
        ('descriptorBindingVariableDescriptorCount', ctypes.c_uint32),
        ('runtimeDescriptorArray', ctypes.c_uint32),
        ('samplerFilterMinmax', ctypes.c_uint32),
        ('scalarBlockLayout', ctypes.c_uint32),
        ('imagelessFramebuffer', ctypes.c_uint32),
        ('uniformBufferStandardLayout', ctypes.c_uint32),
        ('shaderSubgroupExtendedTypes', ctypes.c_uint32),
        ('separateDepthStencilLayouts', ctypes.c_uint32),
        ('hostQueryReset', ctypes.c_uint32),
        ('timelineSemaphore', ctypes.c_uint32),
        ('bufferDeviceAddress', ctypes.c_uint32),
        ('bufferDeviceAddressCaptureReplay', ctypes.c_uint32),
        ('bufferDeviceAddressMultiDevice', ctypes.c_uint32),
        ('vulkanMemoryModel', ctypes.c_uint32),
        ('vulkanMemoryModelDeviceScope', ctypes.c_uint32),
        ('vulkanMemoryModelAvailabilityVisibilityChains', ctypes.c_uint32),
        ('shaderOutputViewportIndex', ctypes.c_uint32),
        ('shaderOutputLayer', ctypes.c_uint32),
        ('subgroupBroadcastDynamicId', ctypes.c_uint32),
    ]

descriptor = {
    'extends': {
        'VkDeviceCreateInfo',
        'VkPhysicalDeviceFeatures2',
    },
    'extended_by': set(),
    'includes': set(),
    'included_in': set(),
    'input_of': set(),
    'output_of': set(),
    'member_map': {
        'sType': {'python_name': ['s', 'type'], 'value': 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES', 'type': 'VkStructureType'},
        'pNext': {'python_name': ['p', 'next']},
        'samplerMirrorClampToEdge': {'python_name': ['sampler', 'mirror', 'clamp', 'to', 'edge']},
        'drawIndirectCount': {'python_name': ['draw', 'indirect', 'count']},
        'storageBuffer8BitAccess': {'python_name': ['storage', 'buffer8', 'bit', 'access']},
        'uniformAndStorageBuffer8BitAccess': {'python_name': ['uniform', 'and', 'storage', 'buffer8', 'bit', 'access']},
        'storagePushConstant8': {'python_name': ['storage', 'push', 'constant8']},
        'shaderBufferInt64Atomics': {'python_name': ['shader', 'buffer', 'int64', 'atomics']},
        'shaderSharedInt64Atomics': {'python_name': ['shader', 'shared', 'int64', 'atomics']},
        'shaderFloat16': {'python_name': ['shader', 'float16']},
        'shaderInt8': {'python_name': ['shader', 'int8']},
        'descriptorIndexing': {'python_name': ['descriptor', 'indexing']},
        'shaderInputAttachmentArrayDynamicIndexing': {'python_name': ['shader', 'input', 'attachment', 'array', 'dynamic', 'indexing']},
        'shaderUniformTexelBufferArrayDynamicIndexing': {'python_name': ['shader', 'uniform', 'texel', 'buffer', 'array', 'dynamic', 'indexing']},
        'shaderStorageTexelBufferArrayDynamicIndexing': {'python_name': ['shader', 'storage', 'texel', 'buffer', 'array', 'dynamic', 'indexing']},
        'shaderUniformBufferArrayNonUniformIndexing': {'python_name': ['shader', 'uniform', 'buffer', 'array', 'non', 'uniform', 'indexing']},
        'shaderSampledImageArrayNonUniformIndexing': {'python_name': ['shader', 'sampled', 'image', 'array', 'non', 'uniform', 'indexing']},
        'shaderStorageBufferArrayNonUniformIndexing': {'python_name': ['shader', 'storage', 'buffer', 'array', 'non', 'uniform', 'indexing']},
        'shaderStorageImageArrayNonUniformIndexing': {'python_name': ['shader', 'storage', 'image', 'array', 'non', 'uniform', 'indexing']},
        'shaderInputAttachmentArrayNonUniformIndexing': {'python_name': ['shader', 'input', 'attachment', 'array', 'non', 'uniform', 'indexing']},
        'shaderUniformTexelBufferArrayNonUniformIndexing': {'python_name': ['shader', 'uniform', 'texel', 'buffer', 'array', 'non', 'uniform', 'indexing']},
        'shaderStorageTexelBufferArrayNonUniformIndexing': {'python_name': ['shader', 'storage', 'texel', 'buffer', 'array', 'non', 'uniform', 'indexing']},
        'descriptorBindingUniformBufferUpdateAfterBind': {'python_name': ['descriptor', 'binding', 'uniform', 'buffer', 'update', 'after', 'bind']},
        'descriptorBindingSampledImageUpdateAfterBind': {'python_name': ['descriptor', 'binding', 'sampled', 'image', 'update', 'after', 'bind']},
        'descriptorBindingStorageImageUpdateAfterBind': {'python_name': ['descriptor', 'binding', 'storage', 'image', 'update', 'after', 'bind']},
        'descriptorBindingStorageBufferUpdateAfterBind': {'python_name': ['descriptor', 'binding', 'storage', 'buffer', 'update', 'after', 'bind']},
        'descriptorBindingUniformTexelBufferUpdateAfterBind': {'python_name': ['descriptor', 'binding', 'uniform', 'texel', 'buffer', 'update', 'after', 'bind']},
        'descriptorBindingStorageTexelBufferUpdateAfterBind': {'python_name': ['descriptor', 'binding', 'storage', 'texel', 'buffer', 'update', 'after', 'bind']},
        'descriptorBindingUpdateUnusedWhilePending': {'python_name': ['descriptor', 'binding', 'update', 'unused', 'while', 'pending']},
        'descriptorBindingPartiallyBound': {'python_name': ['descriptor', 'binding', 'partially', 'bound']},
        'descriptorBindingVariableDescriptorCount': {'python_name': ['descriptor', 'binding', 'variable', 'descriptor', 'count']},
        'runtimeDescriptorArray': {'python_name': ['runtime', 'descriptor', 'array']},
        'samplerFilterMinmax': {'python_name': ['sampler', 'filter', 'minmax']},
        'scalarBlockLayout': {'python_name': ['scalar', 'block', 'layout']},
        'imagelessFramebuffer': {'python_name': ['imageless', 'framebuffer']},
        'uniformBufferStandardLayout': {'python_name': ['uniform', 'buffer', 'standard', 'layout']},
        'shaderSubgroupExtendedTypes': {'python_name': ['shader', 'subgroup', 'extended', 'types']},
        'separateDepthStencilLayouts': {'python_name': ['separate', 'depth', 'stencil', 'layouts']},
        'hostQueryReset': {'python_name': ['host', 'query', 'reset']},
        'timelineSemaphore': {'python_name': ['timeline', 'semaphore']},
        'bufferDeviceAddress': {'python_name': ['buffer', 'device', 'address']},
        'bufferDeviceAddressCaptureReplay': {'python_name': ['buffer', 'device', 'address', 'capture', 'replay']},
        'bufferDeviceAddressMultiDevice': {'python_name': ['buffer', 'device', 'address', 'multi', 'device']},
        'vulkanMemoryModel': {'python_name': ['vulkan', 'memory', 'model']},
        'vulkanMemoryModelDeviceScope': {'python_name': ['vulkan', 'memory', 'model', 'device', 'scope']},
        'vulkanMemoryModelAvailabilityVisibilityChains': {'python_name': ['vulkan', 'memory', 'model', 'availability', 'visibility', 'chains']},
        'shaderOutputViewportIndex': {'python_name': ['shader', 'output', 'viewport', 'index']},
        'shaderOutputLayer': {'python_name': ['shader', 'output', 'layer']},
        'subgroupBroadcastDynamicId': {'python_name': ['subgroup', 'broadcast', 'dynamic', 'id']},
    }
}
