import ctypes

class CType(ctypes.Structure):
    pass

from .VkPhysicalDeviceFeatures import CType as VkPhysicalDeviceFeatures

CType._fields_ = [
    ('sType', ctypes.c_int),
    ('pNext', ctypes.c_void_p),
    ('features', VkPhysicalDeviceFeatures),
]

descriptor = {
    'extends': {
        'VkDeviceCreateInfo',
    },
    'extended_by': {
        'VkPhysicalDevice16BitStorageFeatures',
        'VkPhysicalDevice4444FormatsFeaturesEXT',
        'VkPhysicalDevice8BitStorageFeatures',
        'VkPhysicalDeviceASTCDecodeFeaturesEXT',
        'VkPhysicalDeviceAccelerationStructureFeaturesKHR',
        'VkPhysicalDeviceAddressBindingReportFeaturesEXT',
        'VkPhysicalDeviceAmigoProfilingFeaturesSEC',
        'VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXT',
        'VkPhysicalDeviceAttachmentFeedbackLoopLayoutFeaturesEXT',
        'VkPhysicalDeviceBlendOperationAdvancedFeaturesEXT',
        'VkPhysicalDeviceBorderColorSwizzleFeaturesEXT',
        'VkPhysicalDeviceBufferDeviceAddressFeatures',
        'VkPhysicalDeviceBufferDeviceAddressFeaturesEXT',
        'VkPhysicalDeviceClusterCullingShaderFeaturesHUAWEI',
        'VkPhysicalDeviceCoherentMemoryFeaturesAMD',
        'VkPhysicalDeviceColorWriteEnableFeaturesEXT',
        'VkPhysicalDeviceComputeShaderDerivativesFeaturesNV',
        'VkPhysicalDeviceConditionalRenderingFeaturesEXT',
        'VkPhysicalDeviceCooperativeMatrixFeaturesKHR',
        'VkPhysicalDeviceCooperativeMatrixFeaturesNV',
        'VkPhysicalDeviceCopyMemoryIndirectFeaturesNV',
        'VkPhysicalDeviceCornerSampledImageFeaturesNV',
        'VkPhysicalDeviceCoverageReductionModeFeaturesNV',
        'VkPhysicalDeviceCubicClampFeaturesQCOM',
        'VkPhysicalDeviceCubicWeightsFeaturesQCOM',
        'VkPhysicalDeviceCudaKernelLaunchFeaturesNV',
        'VkPhysicalDeviceCustomBorderColorFeaturesEXT',
        'VkPhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV',
        'VkPhysicalDeviceDepthBiasControlFeaturesEXT',
        'VkPhysicalDeviceDepthClampZeroOneFeaturesEXT',
        'VkPhysicalDeviceDepthClipControlFeaturesEXT',
        'VkPhysicalDeviceDepthClipEnableFeaturesEXT',
        'VkPhysicalDeviceDescriptorBufferFeaturesEXT',
        'VkPhysicalDeviceDescriptorIndexingFeatures',
        'VkPhysicalDeviceDescriptorPoolOverallocationFeaturesNV',
        'VkPhysicalDeviceDescriptorSetHostMappingFeaturesVALVE',
        'VkPhysicalDeviceDeviceGeneratedCommandsComputeFeaturesNV',
        'VkPhysicalDeviceDeviceGeneratedCommandsFeaturesNV',
        'VkPhysicalDeviceDeviceMemoryReportFeaturesEXT',
        'VkPhysicalDeviceDiagnosticsConfigFeaturesNV',
        'VkPhysicalDeviceDisplacementMicromapFeaturesNV',
        'VkPhysicalDeviceDynamicRenderingFeatures',
        'VkPhysicalDeviceDynamicRenderingLocalReadFeaturesKHR',
        'VkPhysicalDeviceDynamicRenderingUnusedAttachmentsFeaturesEXT',
        'VkPhysicalDeviceExclusiveScissorFeaturesNV',
        'VkPhysicalDeviceExtendedDynamicState2FeaturesEXT',
        'VkPhysicalDeviceExtendedDynamicState3FeaturesEXT',
        'VkPhysicalDeviceExtendedDynamicStateFeaturesEXT',
        'VkPhysicalDeviceExtendedSparseAddressSpaceFeaturesNV',
        'VkPhysicalDeviceExternalFormatResolveFeaturesANDROID',
        'VkPhysicalDeviceExternalMemoryRDMAFeaturesNV',
        'VkPhysicalDeviceExternalMemorySciBufFeaturesNV',
        'VkPhysicalDeviceExternalMemoryScreenBufferFeaturesQNX',
        'VkPhysicalDeviceExternalSciSync2FeaturesNV',
        'VkPhysicalDeviceExternalSciSyncFeaturesNV',
        'VkPhysicalDeviceFaultFeaturesEXT',
        'VkPhysicalDeviceFragmentDensityMap2FeaturesEXT',
        'VkPhysicalDeviceFragmentDensityMapFeaturesEXT',
        'VkPhysicalDeviceFragmentDensityMapOffsetFeaturesQCOM',
        'VkPhysicalDeviceFragmentShaderBarycentricFeaturesKHR',
        'VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT',
        'VkPhysicalDeviceFragmentShadingRateEnumsFeaturesNV',
        'VkPhysicalDeviceFragmentShadingRateFeaturesKHR',
        'VkPhysicalDeviceFrameBoundaryFeaturesEXT',
        'VkPhysicalDeviceGlobalPriorityQueryFeaturesKHR',
        'VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT',
        'VkPhysicalDeviceHostImageCopyFeaturesEXT',
        'VkPhysicalDeviceHostQueryResetFeatures',
        'VkPhysicalDeviceImage2DViewOf3DFeaturesEXT',
        'VkPhysicalDeviceImageAlignmentControlFeaturesMESA',
        'VkPhysicalDeviceImageCompressionControlFeaturesEXT',
        'VkPhysicalDeviceImageCompressionControlSwapchainFeaturesEXT',
        'VkPhysicalDeviceImageProcessing2FeaturesQCOM',
        'VkPhysicalDeviceImageProcessingFeaturesQCOM',
        'VkPhysicalDeviceImageRobustnessFeatures',
        'VkPhysicalDeviceImageSlicedViewOf3DFeaturesEXT',
        'VkPhysicalDeviceImageViewMinLodFeaturesEXT',
        'VkPhysicalDeviceImagelessFramebufferFeatures',
        'VkPhysicalDeviceIndexTypeUint8FeaturesKHR',
        'VkPhysicalDeviceInheritedViewportScissorFeaturesNV',
        'VkPhysicalDeviceInlineUniformBlockFeatures',
        'VkPhysicalDeviceInvocationMaskFeaturesHUAWEI',
        'VkPhysicalDeviceLegacyDitheringFeaturesEXT',
        'VkPhysicalDeviceLegacyVertexAttributesFeaturesEXT',
        'VkPhysicalDeviceLineRasterizationFeaturesKHR',
        'VkPhysicalDeviceLinearColorAttachmentFeaturesNV',
        'VkPhysicalDeviceMaintenance4Features',
        'VkPhysicalDeviceMaintenance5FeaturesKHR',
        'VkPhysicalDeviceMaintenance6FeaturesKHR',
        'VkPhysicalDeviceMapMemoryPlacedFeaturesEXT',
        'VkPhysicalDeviceMemoryDecompressionFeaturesNV',
        'VkPhysicalDeviceMemoryPriorityFeaturesEXT',
        'VkPhysicalDeviceMeshShaderFeaturesEXT',
        'VkPhysicalDeviceMeshShaderFeaturesNV',
        'VkPhysicalDeviceMultiDrawFeaturesEXT',
        'VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT',
        'VkPhysicalDeviceMultiviewFeatures',
        'VkPhysicalDeviceMultiviewPerViewRenderAreasFeaturesQCOM',
        'VkPhysicalDeviceMultiviewPerViewViewportsFeaturesQCOM',
        'VkPhysicalDeviceMutableDescriptorTypeFeaturesEXT',
        'VkPhysicalDeviceNestedCommandBufferFeaturesEXT',
        'VkPhysicalDeviceNonSeamlessCubeMapFeaturesEXT',
        'VkPhysicalDeviceOpacityMicromapFeaturesEXT',
        'VkPhysicalDeviceOpticalFlowFeaturesNV',
        'VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT',
        'VkPhysicalDevicePerStageDescriptorSetFeaturesNV',
        'VkPhysicalDevicePerformanceQueryFeaturesKHR',
        'VkPhysicalDevicePipelineCreationCacheControlFeatures',
        'VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR',
        'VkPhysicalDevicePipelineLibraryGroupHandlesFeaturesEXT',
        'VkPhysicalDevicePipelinePropertiesFeaturesEXT',
        'VkPhysicalDevicePipelineProtectedAccessFeaturesEXT',
        'VkPhysicalDevicePipelineRobustnessFeaturesEXT',
        'VkPhysicalDevicePortabilitySubsetFeaturesKHR',
        'VkPhysicalDevicePresentBarrierFeaturesNV',
        'VkPhysicalDevicePresentIdFeaturesKHR',
        'VkPhysicalDevicePresentWaitFeaturesKHR',
        'VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT',
        'VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT',
        'VkPhysicalDevicePrivateDataFeatures',
        'VkPhysicalDeviceProtectedMemoryFeatures',
        'VkPhysicalDeviceProvokingVertexFeaturesEXT',
        'VkPhysicalDeviceRGBA10X6FormatsFeaturesEXT',
        'VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT',
        'VkPhysicalDeviceRawAccessChainsFeaturesNV',
        'VkPhysicalDeviceRayQueryFeaturesKHR',
        'VkPhysicalDeviceRayTracingInvocationReorderFeaturesNV',
        'VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR',
        'VkPhysicalDeviceRayTracingMotionBlurFeaturesNV',
        'VkPhysicalDeviceRayTracingPipelineFeaturesKHR',
        'VkPhysicalDeviceRayTracingPositionFetchFeaturesKHR',
        'VkPhysicalDeviceRayTracingValidationFeaturesNV',
        'VkPhysicalDeviceRelaxedLineRasterizationFeaturesIMG',
        'VkPhysicalDeviceRenderPassStripedFeaturesARM',
        'VkPhysicalDeviceRepresentativeFragmentTestFeaturesNV',
        'VkPhysicalDeviceRobustness2FeaturesEXT',
        'VkPhysicalDeviceSamplerYcbcrConversionFeatures',
        'VkPhysicalDeviceScalarBlockLayoutFeatures',
        'VkPhysicalDeviceSchedulingControlsFeaturesARM',
        'VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures',
        'VkPhysicalDeviceShaderAtomicFloat16VectorFeaturesNV',
        'VkPhysicalDeviceShaderAtomicFloat2FeaturesEXT',
        'VkPhysicalDeviceShaderAtomicFloatFeaturesEXT',
        'VkPhysicalDeviceShaderAtomicInt64Features',
        'VkPhysicalDeviceShaderClockFeaturesKHR',
        'VkPhysicalDeviceShaderCoreBuiltinsFeaturesARM',
        'VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures',
        'VkPhysicalDeviceShaderDrawParametersFeatures',
        'VkPhysicalDeviceShaderEarlyAndLateFragmentTestsFeaturesAMD',
        'VkPhysicalDeviceShaderEnqueueFeaturesAMDX',
        'VkPhysicalDeviceShaderExpectAssumeFeaturesKHR',
        'VkPhysicalDeviceShaderFloat16Int8Features',
        'VkPhysicalDeviceShaderFloatControls2FeaturesKHR',
        'VkPhysicalDeviceShaderImageAtomicInt64FeaturesEXT',
        'VkPhysicalDeviceShaderImageFootprintFeaturesNV',
        'VkPhysicalDeviceShaderIntegerDotProductFeatures',
        'VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL',
        'VkPhysicalDeviceShaderMaximalReconvergenceFeaturesKHR',
        'VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT',
        'VkPhysicalDeviceShaderObjectFeaturesEXT',
        'VkPhysicalDeviceShaderQuadControlFeaturesKHR',
        'VkPhysicalDeviceShaderRelaxedExtendedInstructionFeaturesKHR',
        'VkPhysicalDeviceShaderReplicatedCompositesFeaturesEXT',
        'VkPhysicalDeviceShaderSMBuiltinsFeaturesNV',
        'VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures',
        'VkPhysicalDeviceShaderSubgroupRotateFeaturesKHR',
        'VkPhysicalDeviceShaderSubgroupUniformControlFlowFeaturesKHR',
        'VkPhysicalDeviceShaderTerminateInvocationFeatures',
        'VkPhysicalDeviceShaderTileImageFeaturesEXT',
        'VkPhysicalDeviceShadingRateImageFeaturesNV',
        'VkPhysicalDeviceSubgroupSizeControlFeatures',
        'VkPhysicalDeviceSubpassMergeFeedbackFeaturesEXT',
        'VkPhysicalDeviceSubpassShadingFeaturesHUAWEI',
        'VkPhysicalDeviceSwapchainMaintenance1FeaturesEXT',
        'VkPhysicalDeviceSynchronization2Features',
        'VkPhysicalDeviceTexelBufferAlignmentFeaturesEXT',
        'VkPhysicalDeviceTextureCompressionASTCHDRFeatures',
        'VkPhysicalDeviceTilePropertiesFeaturesQCOM',
        'VkPhysicalDeviceTimelineSemaphoreFeatures',
        'VkPhysicalDeviceTransformFeedbackFeaturesEXT',
        'VkPhysicalDeviceUniformBufferStandardLayoutFeatures',
        'VkPhysicalDeviceVariablePointersFeatures',
        'VkPhysicalDeviceVertexAttributeDivisorFeaturesKHR',
        'VkPhysicalDeviceVertexInputDynamicStateFeaturesEXT',
        'VkPhysicalDeviceVideoMaintenance1FeaturesKHR',
        'VkPhysicalDeviceVulkan11Features',
        'VkPhysicalDeviceVulkan12Features',
        'VkPhysicalDeviceVulkan13Features',
        'VkPhysicalDeviceVulkanMemoryModelFeatures',
        'VkPhysicalDeviceVulkanSC10Features',
        'VkPhysicalDeviceWorkgroupMemoryExplicitLayoutFeaturesKHR',
        'VkPhysicalDeviceYcbcr2Plane444FormatsFeaturesEXT',
        'VkPhysicalDeviceYcbcrDegammaFeaturesQCOM',
        'VkPhysicalDeviceYcbcrImageArraysFeaturesEXT',
        'VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures',
    },
    'includes': {
        'VkPhysicalDeviceFeatures',
    },
    'included_in': set(),
    'input_of': set(),
    'output_of': {
        'vkGetPhysicalDeviceFeatures2',
    },
    'member_map': {
        'sType': {'python_name': ['s', 'type'], 'value': 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2', 'type': 'VkStructureType'},
        'pNext': {'python_name': ['p', 'next']},
        'features': {'python_name': ['features'], 'type': 'VkPhysicalDeviceFeatures'},
    }
}
