import ctypes
from ..vulkan_base import VKAPI_CALL

from .._vulkan_type.VkAccelerationStructureDeviceAddressInfoKHR import VkAccelerationStructureDeviceAddressInfoKHR

vkGetAccelerationStructureDeviceAddressKHR = VKAPI_CALL(ctypes.c_uint64, ctypes.c_void_p, ctypes.POINTER(VkAccelerationStructureDeviceAddressInfoKHR))
