import ctypes
from ..vulkan_base import VKAPI_CALL

from .._vulkan_type.VkAccelerationStructureCaptureDescriptorDataInfoEXT import VkAccelerationStructureCaptureDescriptorDataInfoEXT

vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT = VKAPI_CALL(ctypes.c_int, ctypes.c_void_p, ctypes.POINTER(VkAccelerationStructureCaptureDescriptorDataInfoEXT), ctypes.c_void_p)
