from enum import IntEnum

class Value(IntEnum):
    STD_VIDEO_AV1_PROFILE_HIGH = 1
    STD_VIDEO_AV1_PROFILE_INVALID = 2147483647
    STD_VIDEO_AV1_PROFILE_MAIN = 0
    STD_VIDEO_AV1_PROFILE_PROFESSIONAL = 2
