from enum import IntEnum

class Value(IntEnum):
    STD_VIDEO_AV1_REFERENCE_NAME_ALTREF2_FRAME = 6
    STD_VIDEO_AV1_REFERENCE_NAME_ALTREF_FRAME = 7
    STD_VIDEO_AV1_REFERENCE_NAME_BWDREF_FRAME = 5
    STD_VIDEO_AV1_REFERENCE_NAME_GOLDEN_FRAME = 4
    STD_VIDEO_AV1_REFERENCE_NAME_INTRA_FRAME = 0
    STD_VIDEO_AV1_REFERENCE_NAME_INVALID = 2147483647
    STD_VIDEO_AV1_REFERENCE_NAME_LAST2_FRAME = 2
    STD_VIDEO_AV1_REFERENCE_NAME_LAST3_FRAME = 3
    STD_VIDEO_AV1_REFERENCE_NAME_LAST_FRAME = 1
