from enum import IntEnum

class Value(IntEnum):
    STD_VIDEO_AV1_CHROMA_SAMPLE_POSITION_COLOCATED = 2
    STD_VIDEO_AV1_CHROMA_SAMPLE_POSITION_INVALID = 2147483647
    STD_VIDEO_AV1_CHROMA_SAMPLE_POSITION_RESERVED = 3
    STD_VIDEO_AV1_CHROMA_SAMPLE_POSITION_UNKNOWN = 0
    STD_VIDEO_AV1_CHROMA_SAMPLE_POSITION_VERTICAL = 1
