from enum import IntFlag

class Value(IntFlag):
    VK_BUILD_MICROMAP_ALLOW_COMPACTION_BIT_EXT = 4
    VK_BUILD_MICROMAP_PREFER_FAST_BUILD_BIT_EXT = 2
    VK_BUILD_MICROMAP_PREFER_FAST_TRACE_BIT_EXT = 1
