from enum import IntFlag

class Value(IntFlag):
    VK_IMAGE_COMPRESSION_FIXED_RATE_10BPC_BIT_EXT = 512
    VK_IMAGE_COMPRESSION_FIXED_RATE_11BPC_BIT_EXT = 1024
    VK_IMAGE_COMPRESSION_FIXED_RATE_12BPC_BIT_EXT = 2048
    VK_IMAGE_COMPRESSION_FIXED_RATE_13BPC_BIT_EXT = 4096
    VK_IMAGE_COMPRESSION_FIXED_RATE_14BPC_BIT_EXT = 8192
    VK_IMAGE_COMPRESSION_FIXED_RATE_15BPC_BIT_EXT = 16384
    VK_IMAGE_COMPRESSION_FIXED_RATE_16BPC_BIT_EXT = 32768
    VK_IMAGE_COMPRESSION_FIXED_RATE_17BPC_BIT_EXT = 65536
    VK_IMAGE_COMPRESSION_FIXED_RATE_18BPC_BIT_EXT = 131072
    VK_IMAGE_COMPRESSION_FIXED_RATE_19BPC_BIT_EXT = 262144
    VK_IMAGE_COMPRESSION_FIXED_RATE_1BPC_BIT_EXT = 1
    VK_IMAGE_COMPRESSION_FIXED_RATE_20BPC_BIT_EXT = 524288
    VK_IMAGE_COMPRESSION_FIXED_RATE_21BPC_BIT_EXT = 1048576
    VK_IMAGE_COMPRESSION_FIXED_RATE_22BPC_BIT_EXT = 2097152
    VK_IMAGE_COMPRESSION_FIXED_RATE_23BPC_BIT_EXT = 4194304
    VK_IMAGE_COMPRESSION_FIXED_RATE_24BPC_BIT_EXT = 8388608
    VK_IMAGE_COMPRESSION_FIXED_RATE_2BPC_BIT_EXT = 2
    VK_IMAGE_COMPRESSION_FIXED_RATE_3BPC_BIT_EXT = 4
    VK_IMAGE_COMPRESSION_FIXED_RATE_4BPC_BIT_EXT = 8
    VK_IMAGE_COMPRESSION_FIXED_RATE_5BPC_BIT_EXT = 16
    VK_IMAGE_COMPRESSION_FIXED_RATE_6BPC_BIT_EXT = 32
    VK_IMAGE_COMPRESSION_FIXED_RATE_7BPC_BIT_EXT = 64
    VK_IMAGE_COMPRESSION_FIXED_RATE_8BPC_BIT_EXT = 128
    VK_IMAGE_COMPRESSION_FIXED_RATE_9BPC_BIT_EXT = 256
    VK_IMAGE_COMPRESSION_FIXED_RATE_NONE_EXT = 0
