from enum import IntFlag

class Value(IntFlag):
    VK_IMAGE_USAGE_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT = 524288
    VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT = 16
    VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT = 32
    VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT = 512
    VK_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR = 256
    VK_IMAGE_USAGE_HOST_TRANSFER_BIT_EXT = 4194304
    VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT = 128
    VK_IMAGE_USAGE_INVOCATION_MASK_BIT_HUAWEI = 262144
    VK_IMAGE_USAGE_SAMPLED_BIT = 4
    VK_IMAGE_USAGE_SAMPLE_BLOCK_MATCH_BIT_QCOM = 2097152
    VK_IMAGE_USAGE_SAMPLE_WEIGHT_BIT_QCOM = 1048576
    VK_IMAGE_USAGE_STORAGE_BIT = 8
    VK_IMAGE_USAGE_TRANSFER_DST_BIT = 2
    VK_IMAGE_USAGE_TRANSFER_SRC_BIT = 1
    VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT = 64
    VK_IMAGE_USAGE_VIDEO_DECODE_DPB_BIT_KHR = 4096
    VK_IMAGE_USAGE_VIDEO_DECODE_DST_BIT_KHR = 1024
    VK_IMAGE_USAGE_VIDEO_DECODE_SRC_BIT_KHR = 2048
    VK_IMAGE_USAGE_VIDEO_ENCODE_DPB_BIT_KHR = 32768
    VK_IMAGE_USAGE_VIDEO_ENCODE_DST_BIT_KHR = 8192
    VK_IMAGE_USAGE_VIDEO_ENCODE_SRC_BIT_KHR = 16384
    VK_IMAGE_USAGE_SHADING_RATE_IMAGE_BIT_NV = VK_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR
