from enum import IntEnum

class Value(IntEnum):
    VK_INDEX_TYPE_NONE_KHR = 1000165000
    VK_INDEX_TYPE_UINT16 = 0
    VK_INDEX_TYPE_UINT32 = 1
    VK_INDEX_TYPE_UINT8_KHR = 1000265000
    VK_INDEX_TYPE_NONE_NV = VK_INDEX_TYPE_NONE_KHR
    VK_INDEX_TYPE_UINT8_EXT = VK_INDEX_TYPE_UINT8_KHR
