from enum import IntFlag

class Value(IntFlag):
    VK_RENDERING_CONTENTS_INLINE_BIT_EXT = 16
    VK_RENDERING_CONTENTS_SECONDARY_COMMAND_BUFFERS_BIT = 1
    VK_RENDERING_ENABLE_LEGACY_DITHERING_BIT_EXT = 8
    VK_RENDERING_RESUMING_BIT = 4
    VK_RENDERING_SUSPENDING_BIT = 2
    VK_RENDERING_CONTENTS_SECONDARY_COMMAND_BUFFERS_BIT_KHR = VK_RENDERING_CONTENTS_SECONDARY_COMMAND_BUFFERS_BIT
    VK_RENDERING_RESUMING_BIT_KHR = VK_RENDERING_RESUMING_BIT
    VK_RENDERING_SUSPENDING_BIT_KHR = VK_RENDERING_SUSPENDING_BIT
