from enum import IntEnum

class Value(IntEnum):
    VK_SUBPASS_CONTENTS_INLINE = 0
    VK_SUBPASS_CONTENTS_INLINE_AND_SECONDARY_COMMAND_BUFFERS_EXT = 1000451000
    VK_SUBPASS_CONTENTS_SECONDARY_COMMAND_BUFFERS = 1
