from enum import IntFlag

class Value(IntFlag):
    VK_TOOL_PURPOSE_ADDITIONAL_FEATURES_BIT = 8
    VK_TOOL_PURPOSE_DEBUG_MARKERS_BIT_EXT = 64
    VK_TOOL_PURPOSE_DEBUG_REPORTING_BIT_EXT = 32
    VK_TOOL_PURPOSE_MODIFYING_FEATURES_BIT = 16
    VK_TOOL_PURPOSE_PROFILING_BIT = 2
    VK_TOOL_PURPOSE_TRACING_BIT = 4
    VK_TOOL_PURPOSE_VALIDATION_BIT = 1
    VK_TOOL_PURPOSE_ADDITIONAL_FEATURES_BIT_EXT = VK_TOOL_PURPOSE_ADDITIONAL_FEATURES_BIT
    VK_TOOL_PURPOSE_MODIFYING_FEATURES_BIT_EXT = VK_TOOL_PURPOSE_MODIFYING_FEATURES_BIT
    VK_TOOL_PURPOSE_PROFILING_BIT_EXT = VK_TOOL_PURPOSE_PROFILING_BIT
    VK_TOOL_PURPOSE_TRACING_BIT_EXT = VK_TOOL_PURPOSE_TRACING_BIT
    VK_TOOL_PURPOSE_VALIDATION_BIT_EXT = VK_TOOL_PURPOSE_VALIDATION_BIT
