from enum import IntFlag

class Value(IntFlag):
    VK_VIDEO_CODING_CONTROL_ENCODE_QUALITY_LEVEL_BIT_KHR = 4
    VK_VIDEO_CODING_CONTROL_ENCODE_RATE_CONTROL_BIT_KHR = 2
    VK_VIDEO_CODING_CONTROL_RESET_BIT_KHR = 1
